ilios/ilios

sfi/src/Ilios/CoreBundle/Controller/CompetencyController.php, sfi/src/Ilios/CoreBundle/Entity/Course.php, sfi/src/Ilios/CoreBundle/Entity/LearningMaterial.php, sfi/src/Ilios/CoreBundle/Entity/MeshDescriptor.php, sfi/src/Ilios/CoreBundle/Entity/Offering.php, sfi/src/Ilios/CoreBundle/Entity/Session.php, sfi/src/Ilios/CoreBundle/Entity/SessionType.php
Format dates in the api according to ISO 8601.  Also fixed a typo in the competency controller.
=> Serialize Dates

app/phpcs.xml
and now my lunch break is over.
=> fixed typo

src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Acceptance/UsersTest.php
=> Use q= instead of searchTerm= for finding by string

src/Ilios/CoreBundle/Entity/SessionDescription.php
=> Add description and ID to session description endpoint

src/Ilios/CoreBundle/Tests/Entity/CourseTest.php, src/Ilios/CoreBundle/Tests/Entity/EntityBase.php
@dartajax if the tests pass this can be merged.
=> Slightly cleaner test code for the course entity

Puppetfile, Vagrantfile, provision/shell/local_modules.sh
Moves php from a hard install to being managed by librarian.
=> Move php to Puppetfile

Vagrantfile
Fixes #779
@dartajax please test.
=> Branch vagrant shared folder config on windows.

src/Ilios/CoreBundle/Entity/IlmSessionFacet.php, src/Ilios/CoreBundle/Entity/InstructionHours.php, src/Ilios/CoreBundle/Entity/LearningMaterial.php, src/Ilios/CoreBundle/Entity/MeshConcept.php, src/Ilios/CoreBundle/Entity/MeshDescriptor.php, src/Ilios/CoreBundle/Entity/MeshQualifier.php, src/Ilios/CoreBundle/Entity/MeshSemanticType.php, src/Ilios/CoreBundle/Entity/MeshTerm.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php, src/Ilios/CoreBundle/EventListener/TimestampListener.php, src/Ilios/CoreBundle/Form/SessionType.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Tests/Entity/MeshConceptTest.php, src/Ilios/CoreBundle/Tests/Entity/MeshDescriptorTest.php, src/Ilios/CoreBundle/Tests/Entity/MeshQualifierTest.php, src/Ilios/CoreBundle/Tests/Entity/MeshSemanticTypeTest.php, src/Ilios/CoreBundle/Tests/Entity/MeshTermTest.php, src/Ilios/CoreBundle/Tests/Entity/SessionTest.php, src/Ilios/CoreBundle/Traits/TimestampableEntity.php, src/Ilios/CoreBundle/Traits/TimestampableEntityInterface.php
Create timestampable trait
Use this trait to update records with un updatedAt column.
=> Fix session creation in API

.gitattributes
left out an equals sign in the original declaration.... shouldn't change the behavior or handing...
=> added equals sign for proper handling

src/Ilios/CoreBundle/Traits/IdentifiableEntity.php, src/Ilios/CoreBundle/Traits/IdentifiableEntityInterface.php
=> id attribute of identifiable entity can be string or int.

src/Ilios/CoreBundle/Controller/CurrentsessionController.php, src/Ilios/CoreBundle/Entity/Cohort.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/OfferingInterface.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Tests/Entity/OfferingTest.php
Added some relationships and cleaned up a bad method signature in the session entity
=> Assorted API Improvements

src/Ilios/CoreBundle/Controller/AamcPcrsController.php, src/Ilios/CoreBundle/Traits/IdentifiableEntity.php, src/Ilios/CoreBundle/Traits/IdentifiableEntityInterface.php
http://ilios.local/app_dev.php/api/v1/aamcpcrs?limit=200&orderBy[id]=ASC&offset=0
=> Get all the pcrses

src/Ilios/CoreBundle/Entity/LearningMaterials/Citation.php, src/Ilios/CoreBundle/Entity/LearningMaterials/CitationInterface.php, src/Ilios/CoreBundle/Entity/LearningMaterials/File.php, src/Ilios/CoreBundle/Entity/LearningMaterials/Link.php, src/Ilios/CoreBundle/Entity/LearningMaterials/LinkInterface.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php
Changed text to citation and webLink to link.
=> Better API for learning materials

app/AppKernel.php, app/config/routing.yml, src/Ilios/CoreBundle/Controller/BadRequestController.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Controller/BadRequestControllerTest.php, src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/DependencyInjection/Configuration.php, src/Ilios/WebBundle/DependencyInjection/IliosWebExtension.php, src/Ilios/WebBundle/IliosWebBundle.php, src/Ilios/WebBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Resources/config/services.yml, src/Ilios/WebBundle/Tests/Controller/IndexControllerTest.php
Added the routes and changes to pull the frontend bootstrap out of ec3
and serve it from the symphony api backend.
=> Serve the frontend from symfony

app/config/config.yml, src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/DependencyInjection/Configuration.php, src/Ilios/WebBundle/DependencyInjection/IliosWebExtension.php, src/Ilios/WebBundle/Resources/config/services.yml, src/Ilios/WebBundle/Service/WebAssets.php, src/Ilios/WebBundle/Tests/DependencyInjection/ConfigurationTest.php, src/Ilios/WebBundle/Tests/DependencyInjection/IliosWebExtensionTest.php
This allows us to lock in a version and a source for the index file and
to change it easily with a configuration parameter.
=> Make the index file location configurable

app/config/routing.yml, src/Ilios/CoreBundle/Classes/UserEvent.php, src/Ilios/CoreBundle/Controller/CurrentsessionController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Acceptance/UsereventsTest.php
Currently only handles offerings by learner group association.
=> Added User Events API endpoint

app/AppKernel.php, src/Ilios/CoreBundle/Form/DataTransformer/SingleRelatedTransformer.php
Bad Code.  Bad Jon.
This should fix a lot of the PUT errors we’re seeing.
=> Fix issue with API relationships

CHANGELOG.md, app/config/config.yml
Update frontend to Baldwin Park
Update change log
=> Beta 3 Release Prep

provision/puppet/modules/profile/manifests/shibbolethsp.pp
=> Better puppet config for apache and shibboleth

app/Resources/migrations/fromIlios2.sql, app/Resources/migrations/generateMigration.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryExport.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryExportInterface.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryInstitution.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryInstitutionInterface.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequence.php, src/Ilios/CoreBundle/Entity/School.php
=> retrofitted curriculum inventory entities with new ids

INSTALL.md, UPGRADE.md
=> added INSTALL.md and updated UPGRADE.md files

src/Ilios/CoreBundle/Entity/LearningMaterial.php
=> fixed typo in code comment.

src/Ilios/CoreBundle/Tests/Controller/InstructorGroupControllerTest.php
The ilmSessions should be posted with the request.
=> Fix broken instructor groups controller test

src/Ilios/AuthenticationBundle/Controller/AuthenticationController.php, src/Ilios/AuthenticationBundle/Jwt/Token.php
=> fixes "refresh token" controller action

src/Ilios/AuthenticationBundle/Controller/AuthenticationController.php, src/Ilios/AuthenticationBundle/Jwt/Token.php, src/Ilios/AuthenticationBundle/Tests/Controller/AuthenticationControllerTest.php
=> refreshing api tokens should honor given TTL

src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseInterface.php, src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/ProgramYearInterface.php, src/Ilios/CoreBundle/Traits/ArchivableEntity.php, src/Ilios/CoreBundle/Traits/ArchivableEntityInterface.php, src/Ilios/CoreBundle/Traits/LockableEntity.php, src/Ilios/CoreBundle/Traits/LockableEntityInterface.php
Courses and program years are both lockable as well as archivable.
I pulled these out into traits an interfaces - this will make it easier/cleaner to authorize access to lockables/archivables.
=> Added lockable and archivable entity traits and interfaces

src/Ilios/CoreBundle/Classes/SchoolEvent.php, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Controller/SchooleventsControllerTest.php
Currently handles only direct owningSchool relationship for a course.
Fixes #927
=> Add schoolevents api

src/Ilios/CoreBundle/Controller/PublishEventController.php, src/Ilios/CoreBundle/Entity/Manager/PublishEventManager.php, src/Ilios/CoreBundle/Entity/Manager/PublishEventManagerInterface.php, src/Ilios/CoreBundle/Entity/PublishEvent.php, src/Ilios/CoreBundle/Entity/PublishEventInterface.php, src/Ilios/CoreBundle/Form/Type/PublishEventType.php, src/Ilios/CoreBundle/Handler/PublishEventHandler.php
=> deprecated publish event components

src/Ilios/CoreBundle/Controller/PublishEventController.php, src/Ilios/CoreBundle/Entity/Manager/PublishEventManager.php, src/Ilios/CoreBundle/Entity/Manager/PublishEventManagerInterface.php, src/Ilios/CoreBundle/Handler/PublishEventHandler.php, src/Ilios/CoreBundle/Resources/config/managers.yml, src/Ilios/CoreBundle/Tests/Controller/PublishEventControllerTest.php
=> set admin user on publish event creation.

src/Ilios/AuthenticationBundle/Jwt/Provider.php, src/Ilios/AuthenticationBundle/Jwt/Token.php
=> removed broken code from jwt token class

src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseInterface.php, src/Ilios/CoreBundle/Entity/Department.php, src/Ilios/CoreBundle/Entity/DepartmentInterface.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/OfferingInterface.php, src/Ilios/CoreBundle/Entity/Program.php, src/Ilios/CoreBundle/Entity/ProgramInterface.php, src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/ProgramYearInterface.php, src/Ilios/CoreBundle/Entity/Report.php, src/Ilios/CoreBundle/Entity/ReportInterface.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/SchoolInterface.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php, src/Ilios/CoreBundle/Traits/DeletableEntity.php, src/Ilios/CoreBundle/Traits/DeletableEntityInterface.php
=> implements "deletable entity" interface and trait 

src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php, src/Ilios/CoreBundle/Form/Type/CourseLearningMaterialType.php, src/Ilios/CoreBundle/Form/Type/SessionLearningMaterialType.php, src/Ilios/CoreBundle/Tests/Controller/SessionLearningMaterialControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/SessionLearningMaterialData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadSessionLearningMaterialData.php
=> Add notes to course and session learning materials

src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Tests/Controller/ApiDocsControllerTest.php
Also added a very simple test to ensure that the API docs are loading
at all.
Fixes #972
=> Fix annotation for Schoolevents endpoint

src/Ilios/CoreBundle/Classes/AcademicYear.php, src/Ilios/CoreBundle/Controller/AcademicYearController.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Classes/AcademicYearTest.php, src/Ilios/CoreBundle/Tests/Controller/AcademicYearControllerTest.php
=> Change educational year to academic year

src/Ilios/CoreBundle/Entity/Program.php, src/Ilios/CoreBundle/Entity/ProgramInterface.php
=> defined setter/getter methods for curr inv report in program interface.

app/config/config_prod.yml, provision/puppet/modules/profile/manifests/common/php.pp
=> Enable APC cache in production

src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/CoreBundle/Controller/UploadController.php, src/Ilios/CoreBundle/Tests/Controller/AbstractControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UploadControllerTest.php, src/Ilios/CoreBundle/Tests/Traits/JsonControllerTest.php
The TemporaryFileSystemVoter was not being registered.
I also added tests for file uploading.
Fixes #983
=> Fix file upload

src/Ilios/CoreBundle/Form/Type/UserType.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php
We were missing instructedOfferings and cohorts which prevented the
fronted from saving users.
=> Add missing properties to userType

src/Ilios/CliBundle/Command/AuditLogExportCommand.php, src/Ilios/CliBundle/Command/AuditlogExportCommand.php, src/Ilios/CliBundle/DependencyInjection/IliosCliExtension.php, src/Ilios/CliBundle/Resources/config/dataloaders.yml, src/Ilios/CliBundle/Tests/Command/AuditLogExportCommandTest.php, src/Ilios/CliBundle/Tests/DataLoader/AuditLogData.php, src/Ilios/CliBundle/Tests/Fixture/LoadAuditLogData.php, src/Ilios/CoreBundle/Entity/AuditLog.php, src/Ilios/CoreBundle/Entity/AuditLogInterface.php, src/Ilios/CoreBundle/Entity/Manager/AuditLogManager.php, src/Ilios/CoreBundle/Entity/Manager/AuditLogManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/AuditLogRepository.php
`bin/console ilios:maintenance:export-audit-log --help`
_still WIP obviously._
=> 994 auditlog export

CHANGELOG.md, app/config/config.yml
=> Prepare for v3.0.0-beta6 release

src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/PendingUserUpdateVoter.php, src/Ilios/CoreBundle/Controller/PendingUserUpdateController.php, src/Ilios/CoreBundle/Entity/PendingUserUpdate.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php, src/Ilios/CoreBundle/Form/Type/PendingUserUpdateType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, src/Ilios/CoreBundle/Handler/PendingUserUpdateHandler.php, src/Ilios/CoreBundle/Resources/config/dataloaders.yml, src/Ilios/CoreBundle/Resources/config/handlers.yml, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Controller/PendingUserUpdateControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/PendingUserUpdateData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadPendingUserUpdateData.php
Provides get, post, put, delete for pending user updates.
Also added pendingUserUpdate to the User API.
Fixes #1016
=> Add PendingUserUpdate API endpoint

src/Ilios/CoreBundle/Entity/CohortInterface.php, src/Ilios/CoreBundle/Entity/CourseInterface.php
found these while working on other stuff.
=> declared getters/setters in entity interfaces.

app/config/config.yml
I think this is a good idea.  I might be wrong though, does anyone know better?
=> A more open CORS policy for the entire backend

src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/IlmSessionInterface.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/OfferingInterface.php, src/Ilios/WebBundle/Controller/IcsController.php
The ICS now includes details about the session and course including
objectives and learning materials.
Fixes #1020
=> Add details to ics feed

src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php
this addresses the issue of duplicates and random results when search is used in combination with offset/limit.
=> fix mesh descriptor search

src/Ilios/CoreBundle/Controller/LearningMaterialController.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Tests/Controller/LearningMaterialControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/LearningMaterialData.php
This allows for searching for a material by partial name
=> Add a q (query) to get learningmaterials

src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/PublishEvent.php, src/Ilios/CoreBundle/Form/Type/OfferingType.php, src/Ilios/CoreBundle/Tests/Controller/OfferingControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/PublishEventControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/OfferingData.php, src/Ilios/CoreBundle/Tests/DataLoader/PublishEventData.php, src/Ilios/CoreBundle/Tests/Entity/PublishEventTest.php, src/Ilios/CoreBundle/Tests/Fixture/LoadOfferingData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadPublishEventData.php
This is in our schema and we may want it before we have a v2 of the API.
=> Allows offerings to save publishEvents

src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php
this is needed for the user search for directors in the course manager.
=> add filtering by role to user search

src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/CourseVoter.php, src/Ilios/AuthenticationBundle/Voter/IlmSessionVoter.php, src/Ilios/CoreBundle/Entity/Manager/CourseManager.php, src/Ilios/CoreBundle/Entity/Manager/CourseManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
=> added additional visibility checks on courses.

app/Resources/DoctrineMigrations/Version20151106022409.php, src/Ilios/CoreBundle/Entity/Program.php, src/Ilios/CoreBundle/Form/Type/ProgramType.php, src/Ilios/CoreBundle/Tests/Entity/ProgramTest.php
=> makes program title required and short title optional

phpunit.xml.dist
=> have PHPUnit stop on first failure by default.

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
Instead of doing this calculation on the fronted which was annoying I just added an endDate to the API so ILMs appear to last for 15 minutes.
Fixes ilios/frontend#839
=> Add endDate to ILMs 15 minutes after dueDate

src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Tests/Controller/LearningMaterialControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/LearningMaterialData.php
=> Match description in learning material search

src/Ilios/AuthenticationBundle/Voter/LearnerGroupVoter.php
=> Allow users to access the groups they belong to

src/Ilios/CoreBundle/Form/Type/ReportType.php, src/Ilios/CoreBundle/Tests/DataLoader/ReportData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadReportData.php
This allows saving reports correctly.
=> Add prepositionalObjectTableRowId to ReportType

src/Ilios/CoreBundle/Controller/CourseController.php, src/Ilios/CoreBundle/Controller/DepartmentController.php, src/Ilios/CoreBundle/Controller/OfferingController.php, src/Ilios/CoreBundle/Controller/ProgramController.php, src/Ilios/CoreBundle/Controller/ProgramYearController.php, src/Ilios/CoreBundle/Controller/ReportController.php, src/Ilios/CoreBundle/Controller/SchoolController.php, src/Ilios/CoreBundle/Controller/SessionController.php
refs #1087.
refs ilios/moodle-enrol-ilios#10.
=> removed obsolete code.

src/Ilios/CoreBundle/Entity/LearningMaterial.php, src/Ilios/CoreBundle/Tests/Entity/LearningMaterialTest.php
=> Learning material description should not be required

src/Ilios/CliBundle/Command/CleanupStringsCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/CleanupStringsCommandTest.php, src/Ilios/CoreBundle/Entity/Manager/CourseLearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/CourseLearningMaterialManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/ObjectiveManager.php, src/Ilios/CoreBundle/Entity/Manager/ObjectiveManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/SessionDescriptionManager.php, src/Ilios/CoreBundle/Entity/Manager/SessionDescriptionManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/SessionLearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/SessionLearningMaterialManagerInterface.php
This adds a command with a set of flags for cleaning up bad HTML already in the database.
Fixes #1128
=> Cleanup HTML in database

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/SchooleventsControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UsereventControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/OfferingData.php
Corrects an issue where multi day events which were covered by the
query were not included in the results.
Fixes #1131
=> Correct handling of milti day events for users and schools

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Tests/Controller/SessionControllerTest.php
=> include ilm sessions when filtering by instructor/instructor-groups.

src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Entity/SessionType.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php
=> filter session types by associated entities

src/Ilios/CoreBundle/Entity/Program.php, src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/Repository/ProgramRepository.php, src/Ilios/CoreBundle/Tests/Controller/ProgramControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/ProgramData.php, src/Ilios/CoreBundle/Tests/DataLoader/ProgramYearData.php, src/Ilios/CoreBundle/Tests/DataLoader/SchoolData.php, src/Ilios/CoreBundle/Tests/DataLoader/TopicData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadProgramYearData.php
Filtering by:
- Courses
- Sessions
- Topics
Fixes #1132
=> Filter programs be relationships

src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php, src/Ilios/CoreBundle/Tests/Controller/MeshDescriptorControllerTest.php
=> filter mesh descriptors by associated entities

src/Ilios/CoreBundle/Entity/Competency.php, src/Ilios/CoreBundle/Entity/Repository/CompetencyRepository.php, src/Ilios/CoreBundle/Tests/Controller/CompetencyControllerTest.php
=> filter competencies by associated entities

src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/Repository/ProgramYearRepository.php, src/Ilios/CoreBundle/Tests/Controller/ProgramYearControllerTest.php
=> implemented custom findBy() in programyear repo.

src/Ilios/CoreBundle/Entity/Repository/TopicRepository.php, src/Ilios/CoreBundle/Entity/Topic.php, src/Ilios/CoreBundle/Tests/Controller/TopicControllerTest.php
=> filter topics by associated entities

src/Ilios/CoreBundle/Entity/InstructorGroup.php, src/Ilios/CoreBundle/Entity/Repository/InstructorGroupRepository.php, src/Ilios/CoreBundle/Tests/Controller/InstructorGroupControllerTest.php
=> filter instructor groups by associated entities

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php
fixes #1134.
please note the filter keys, `instructedCourses` etc.
=> filter instructors by associated entities

composer.json, composer.lock, src/Ilios/AuthenticationBundle/Service/JsonWebTokenManager.php, src/Ilios/AuthenticationBundle/Tests/Controller/AuthenticationControllerTest.php, src/Ilios/AuthenticationBundle/Tests/Service/JsonWebTokenManagerTest.php
=> updated JWT libs.

app/config/config.yml, src/Ilios/WebBundle/DependencyInjection/Configuration.php, src/Ilios/WebBundle/Service/WebAssets.php, src/Ilios/WebBundle/Tests/Controller/IndexControllerTest.php, src/Ilios/WebBundle/Tests/DependencyInjection/ConfigurationTest.php, src/Ilios/WebBundle/Tests/DependencyInjection/IliosWebExtensionTest.php
Our new fronted deploy process has new requirements in https://github.com/ilios/frontend/pull/1196
=> Update web config with new AWS URLs

composer.lock, src/Ilios/AuthenticationBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Controller/ConfigController.php, src/Ilios/WebBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Tests/Controller/ConfigControllerTest.php
_Note_: the new route is `/config`, not `app/config`.
fixes #1176 
fixes #1175
=> moved config route/expose locale

app/Resources/DoctrineMigrations/Version20151204220022.php, src/Ilios/CoreBundle/Entity/Report.php, src/Ilios/CoreBundle/Entity/ReportInterface.php, src/Ilios/CoreBundle/Form/Type/ReportType.php, src/Ilios/CoreBundle/Tests/Controller/SchoolControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/ReportData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/Entity/ReportTest.php, src/Ilios/CoreBundle/Tests/Fixture/LoadReportData.php
This will allow us to scope a report by school to make it *better,
stronger, and faster*
Fixes #1180
=> Add school relationship to reports

src/Ilios/CoreBundle/Entity/Repository/CompetencyRepository.php, src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Entity/Repository/InstructorGroupRepository.php, src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Entity/Repository/ProgramRepository.php, src/Ilios/CoreBundle/Entity/Repository/ProgramYearRepository.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Entity/Repository/TopicRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/CompetencyControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/InstructorGroupControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/ProgramControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/ProgramYearControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/SessionControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/TopicControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php
=> filter entities by schools

src/Ilios/AuthenticationBundle/Voter/SchoolVoter.php
=> Give developers read access to schools

src/Ilios/CliBundle/Command/CreateUserTokenCommand.php, src/Ilios/CliBundle/Command/InvalidateUserTokenCommand.php, src/Ilios/CliBundle/Command/ValidateLearningMaterialPathsCommand.php, src/Ilios/CliBundle/Tests/Command/CreateUserTokenCommandTest.php, src/Ilios/CliBundle/Tests/Command/InvalidateUserTokenCommandTest.php, src/Ilios/CliBundle/Tests/Command/ValidateLearningMaterialPathsCommandTest.php
- Create User Token
- Invalidate User Tokens
- Validate Learning Material Paths
This makes more sense
=> Move some setup commands to maintenance

INSTALL.md, UPGRADE.md
=> Updates to installation and upgrade documentation

bin/symfony_requirements, composer.json, composer.lock, src/Ilios/AuthenticationBundle/Voter/LearningMaterialVoter.php, src/Ilios/AuthenticationBundle/Voter/SchoolVoter.php
Fixes #1206
I tested the frontend manually as well - everything seems to be working.
=> Update symphony to 2.8

src/Ilios/CoreBundle/Controller/CourseController.php, src/Ilios/CoreBundle/Entity/Manager/CourseManager.php, src/Ilios/CoreBundle/Entity/Manager/CourseManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
=> Gimme my courses

app/config/config.yml, app/config/parameters.yml.dist, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/DependencyInjection/Configuration.php, src/Ilios/CoreBundle/DependencyInjection/IliosCoreExtension.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/DependencyInjection/IliosCoreExtensionTest.php, src/Ilios/WebBundle/Controller/IcsController.php
=> adjust user/school event query ranges for ILMs

src/Ilios/WebBundle/Controller/IcsController.php
=> return response from controller, don't send it.

app/config/config.yml, app/config/parameters.yml.dist, src/Ilios/CliBundle/Command/SendChangeAlertsCommand.php, src/Ilios/CliBundle/Command/SendTeachingRemindersCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/SendChangeAlertsCommandTest.php, src/Ilios/CliBundle/Tests/Command/SendTeachingRemindersCommandTest.php, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/DependencyInjection/Configuration.php, src/Ilios/CoreBundle/DependencyInjection/IliosCoreExtension.php, src/Ilios/CoreBundle/Resources/views/Email/offeringchangealert.text.twig, src/Ilios/CoreBundle/Resources/views/Email/teachingreminder.text.twig, src/Ilios/CoreBundle/Tests/DependencyInjection/IliosCoreExtensionTest.php, src/Ilios/WebBundle/Controller/IcsController.php
=> Fix timezone offset in notifications

src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/WebBundle/Controller/IcsController.php
=> date time adjustment hack for ILMs in ICS calendar feed.

composer.json, composer.lock
Had to go back a version to one that has correct line endings for
descriptions.
Fixes #1225
=> Backup to a working version of our ical library

app/Resources/DoctrineMigrations/Version20160104231711.php, app/Resources/DoctrineMigrations/Version20160105002207.php, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/WebBundle/Controller/IcsController.php
=> Ilm due date datetime conversion

src/Ilios/AuthenticationBundle/Voter/AbstractVoter.php, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php
Students don’t get to see anything for scheduled events.
Fixes #1237
=> Limit Data in Scheduled Events

src/Ilios/CoreBundle/Entity/Manager/OfferingManager.php
=> filter out offerings belonging to unpublished courses.

app/Resources/DoctrineMigrations/Version20160106190703.php, app/Resources/DoctrineMigrations/Version20160106235355.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/SessionDescription.php, src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php
=> Cascading session deletes

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> streamlines school events queries

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> checks courses for published as tbd status when flagging events as scheduled

src/Ilios/CliBundle/Tests/Command/SendChangeAlertsCommandTest.php, src/Ilios/CliBundle/Tests/Command/SendTeachingRemindersCommandTest.php, src/Ilios/CoreBundle/Resources/views/Email/offeringchangealert.text.twig, src/Ilios/CoreBundle/Resources/views/Email/teachingreminder.text.twig
=> Html entity escaping in notifications

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> expanded queries to pull ILm-based events for directed courses

src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/SchooleventsControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UsereventControllerTest.php
=> expose course title on calendar events

src/Ilios/CoreBundle/Entity/IlmSession.php
=> check for pre-existing relationship before adding learner group to ilm

src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php
=> allow for un-setting of ilm on session.

src/Ilios/WebBundle/Service/WebAssets.php
=> throw an exception if remote file could not be loaded.

src/Ilios/AuthenticationBundle/Voter/CourseLearningMaterialVoter.php, src/Ilios/AuthenticationBundle/Voter/LearningMaterialVoter.php, src/Ilios/AuthenticationBundle/Voter/SessionLearningMaterialVoter.php, src/Ilios/CoreBundle/Entity/LearningMaterialStatusInterface.php
=> reject student access to in-draft LMs

CHANGELOG.md, app/config/config.yml
=> updated frontend build hash to non-corrupted one

src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/ProgramYearInterface.php
=> declared cohort-getter/setters in program-year entity interface.

src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Entity/School.php
=> replaced id-getter/setters with identifable entity trait.

src/Ilios/CoreBundle/Traits/StringableIdEntity.php
=> fixed typo in class docblock.

.travis.yml
This is what we are using in production at UCSF so it would behoove us to test it.
=> Add PHP 5.6 to the PHP versions we test against

app/Resources/DoctrineMigrations/Version20160128223548.php, src/Ilios/CliBundle/Command/AddDirectoryUserCommand.php, src/Ilios/CliBundle/Command/AddUserCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/AddDirectoryUserCommandTest.php, src/Ilios/CliBundle/Tests/Command/AddUserCommandTest.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Tests/DataLoader/SchoolData.php
This allows a new user to be created without being in the campus directory first.
Fixes #1361
=> Created Add User Command

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> uses newer updated-timestamp from offerings and sessions in calendar events.

src/Ilios/CoreBundle/Entity/Manager/OfferingManager.php, src/Ilios/CoreBundle/Tests/Entity/Manager/OfferingManagerTest.php
=> filter unpublished offerings out of teaching reminders

src/Ilios/CoreBundle/Entity/Manager/OfferingManager.php
=> rm obsolete, soft-deletes-related code.

src/Ilios/AuthenticationBundle/Voter/LearnerGroupVoter.php, src/Ilios/AuthenticationBundle/Voter/SchoolVoter.php, src/Ilios/AuthenticationBundle/Voter/SessionTypeVoter.php, src/Ilios/CoreBundle/Entity/Manager/PermissionManager.php, src/Ilios/CoreBundle/Entity/Manager/PermissionManagerInterface.php, src/Ilios/CoreBundle/Tests/Entity/Manager/PermissionManagerTest.php
=> reworked various read permissions checks

src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php
=> filter session type by courses.

src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php
=> filter session type by learning material.

src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php
=> filter session type by program.

src/Ilios/AuthenticationBundle/Voter/InstructorGroupVoter.php
=> losened up view perms on instructor groups.

src/Ilios/AuthenticationBundle/Voter/LearnerGroupVoter.php, src/Ilios/AuthenticationBundle/Voter/ProgramVoter.php, src/Ilios/AuthenticationBundle/Voter/ProgramYearVoter.php
fixes #1307 
@saschaben please review and sign of on changes in business logic.
=> losened up views perms.

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/SessionDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/SessionEntityVoter.php, src/Ilios/AuthenticationBundle/Voter/IlmSessionVoter.php, src/Ilios/AuthenticationBundle/Voter/OfferingVoter.php, src/Ilios/AuthenticationBundle/Voter/SessionDescriptionVoter.php, src/Ilios/AuthenticationBundle/Voter/SessionLearningMaterialVoter.php, src/Ilios/CoreBundle/Controller/SessionController.php, src/Ilios/CoreBundle/Entity/DTO/SessionDTO.php, src/Ilios/CoreBundle/Entity/Manager/SessionManager.php, src/Ilios/CoreBundle/Entity/Manager/SessionManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php
=> session DTO

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/UserDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/UserEntityVoter.php, src/Ilios/AuthenticationBundle/Voter/PendingUserUpdateVoter.php, src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/DTO/UserDTO.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/User.php
Use it in GET requests for speedup.
=> Add UserDTO

src/Ilios/CoreBundle/Entity/Repository/PendingUserUpdateRepository.php, src/Ilios/CoreBundle/Tests/Controller/PendingUserUpdateControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/PendingUserUpdateData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php
Allow pending user updates to be filtered by school.  Added users filter as well - just in case.
=> New PendingUsers filters

app/Resources/DoctrineMigrations/Version20160223211000.php, src/Ilios/CoreBundle/Entity/LearningMaterial.php, src/Ilios/CoreBundle/Tests/Controller/LearningMaterialControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/LearningMaterialData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadLearningMaterialData.php
=> Link and Citation learning materials get a corresponding mimetype

bin/symfony_requirements, composer.lock
sensio/distribution-bundle (v4.0.4 -v4.0.5 )
sensio/framework-extra-bundle (v3.0.12 - v3.0.13)
jms/di-extra-bundle (1.6.0 - 1.7.0)
phpspec/prophecy (v1.5.0 - v1.6.0)
phpunit/phpunit (4.8.22 - 4.8.23)
liip/functional-test-bundle (1.4.1 - 1.5.0)
zendframework/zend-eventmanager (3.0.0 - 3.0.1)
doctrine/migrations (v1.3.0 - v1.4.0)
=> Update composer libraries

src/Ilios/WebBundle/Service/WebIndexFromJson.php
Big change with the removal of topics, lets increment the API version
we provide accordingly.
=> Bump the api version to 1.2

app/Resources/DoctrineMigrations/Version20160308211000.php
Topics are gone, long live vocabularies.
Fixes #1257
=> Remove topic reports which are no longer valid

web/app.php
=> enabled APC loader.

src/Ilios/CoreBundle/Controller/MeshSemanticTypeController.php, src/Ilios/CoreBundle/DataFixtures/ORM/LoadMeshConceptSemanticTypeData.php, src/Ilios/CoreBundle/DataFixtures/ORM/LoadMeshSemanticTypeData.php, src/Ilios/CoreBundle/Entity/Manager/MeshSemanticTypeManager.php, src/Ilios/CoreBundle/Entity/Manager/MeshSemanticTypeManagerInterface.php, src/Ilios/CoreBundle/Entity/MeshSemanticType.php, src/Ilios/CoreBundle/Entity/MeshSemanticTypeInterface.php, src/Ilios/CoreBundle/Handler/MeshSemanticTypeHandler.php
=> flagged semantic type components as deprecated.

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/TermDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/TermEntityVoter.php, src/Ilios/CoreBundle/Controller/TermController.php, src/Ilios/CoreBundle/Entity/DTO/TermDTO.php, src/Ilios/CoreBundle/Entity/Manager/TermManager.php, src/Ilios/CoreBundle/Entity/Manager/TermManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, src/Ilios/CoreBundle/Entity/Term.php, src/Ilios/CoreBundle/Form/Type/TermType.php, src/Ilios/CoreBundle/Tests/Controller/TermControllerTest.php
Adds relationships (courses, sessions, programYears, children) to the terms endpoint both saving and loading.  Converts GET requests to use a DTO which is the only way to do this fast enough to be reasonable.
=> Save and Load terms completly

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
=> include directors when filtering courses by instructors.

src/Ilios/WebBundle/Controller/ErrorController.php, src/Ilios/WebBundle/Tests/Controller/ErrorControllerTest.php
We were treating the string that comes from $data as an array.
=> Fix error handling

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> added distinct clause to queries.

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/MeshDescriptorDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/MeshEntityVoter.php, src/Ilios/CoreBundle/Controller/MeshDescriptorController.php, src/Ilios/CoreBundle/Entity/DTO/MeshDescriptorDTO.php, src/Ilios/CoreBundle/Entity/Manager/MeshDescriptorManager.php, src/Ilios/CoreBundle/Entity/Manager/MeshDescriptorManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php
=> use DTOs for MeSH descriptor queries

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/CohortVoter.php, src/Ilios/AuthenticationBundle/Voter/DTO/ProgramYearDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/ProgramYearEntityVoter.php, src/Ilios/CoreBundle/Controller/ProgramYearController.php, src/Ilios/CoreBundle/Entity/DTO/ProgramYearDTO.php, src/Ilios/CoreBundle/Entity/Manager/ProgramYearManager.php, src/Ilios/CoreBundle/Entity/Manager/ProgramYearManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/ProgramYearRepository.php, src/Ilios/CoreBundle/Tests/Controller/ProgramYearControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/ProgramYearData.php
Also added startYears as an option that can take multiple startYears and return all matching program years.
=> Program Years as DTOs

src/Ilios/CoreBundle/Entity/Cohort.php, src/Ilios/CoreBundle/Entity/Repository/CohortRepository.php, src/Ilios/CoreBundle/Tests/Controller/CohortControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/ProgramControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/CohortData.php, src/Ilios/CoreBundle/Tests/DataLoader/ProgramData.php, src/Ilios/CoreBundle/Tests/DataLoader/ProgramYearData.php
Filters by:
- Courses
- Learner Groups
- Users
- Schools
=> Added filtering by relationships for cohorts API

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php
=> Fix typo in select query from SchoolRepository:findBy

src/Ilios/WebBundle/Service/WebIndexFromJson.php
This is needed as the cohort filters provide new features.
Should have been done in #1367
=> Bump the API version to v1.3

app/Resources/DoctrineMigrations/Version20160419233601.php, src/Ilios/CoreBundle/Entity/Offering.php
=> bumped up size of offering::room column.

app/Resources/DoctrineMigrations/Version20160421221726.php, src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseLearningMaterial.php, src/Ilios/CoreBundle/Entity/Session.php
=> updated foreign key constraints to allow for cascading deletes.

src/Ilios/CliBundle/Resources/config/services.yml
=> rm redundant commas in args list.

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/LearnerGroupDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/LearnerGroupEntityVoter.php, src/Ilios/CoreBundle/Controller/LearnerGroupController.php, src/Ilios/CoreBundle/Entity/DTO/LearnerGroupDTO.php, src/Ilios/CoreBundle/Entity/LearnerGroup.php, src/Ilios/CoreBundle/Entity/Manager/LearnerGroupManager.php, src/Ilios/CoreBundle/Entity/Manager/LearnerGroupManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/LearnerGroupRepository.php
These are way faster and more memory efficient.
Fixes #1392
=> Convert LearnerGroups endpoint to use DTOs

app/Resources/DoctrineMigrations/Version20160422180552.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/OfferingInterface.php, src/Ilios/CoreBundle/Form/Type/OfferingType.php, src/Ilios/CoreBundle/Tests/DataLoader/OfferingData.php, src/Ilios/CoreBundle/Tests/Entity/OfferingTest.php, src/Ilios/CoreBundle/Tests/Fixture/LoadOfferingData.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php
=> add 'site' attribute to 'offering' entity.

src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/Manager/AbstractManager.php, src/Ilios/CoreBundle/Entity/Manager/ManagerInterface.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php
Takes a 'users' data from JSON as POST and adds every user.
Fixes #1375
=> Allow multiple users to be added simultaneously

src/Ilios/CoreBundle/Resources/config/abstract_types.yml, src/Ilios/CoreBundle/Resources/config/dataloaders.yml, src/Ilios/CoreBundle/Resources/config/handlers.yml, src/Ilios/CoreBundle/Resources/config/managers.yml
=> quoted scalar values to get rid of deprecation warnings.

src/Ilios/CoreBundle/Classes/LearningMaterialDecorator.php
=> fixed deprecation.

src/Ilios/CoreBundle/Entity/Repository/LearnerGroupRepository.php, src/Ilios/CoreBundle/Tests/Controller/CohortControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/LearnerGroupControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/CohortData.php, src/Ilios/CoreBundle/Tests/DataLoader/LearnerGroupData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadLearnerGroupData.php
=> Filter learner groups by parent and cohort

composer.lock
=> updated to symfony 2.8.6

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/ProgramDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/ProgramEntityVoter.php, src/Ilios/CoreBundle/Controller/ProgramController.php, src/Ilios/CoreBundle/Entity/DTO/ProgramDTO.php, src/Ilios/CoreBundle/Entity/Manager/ProgramManager.php, src/Ilios/CoreBundle/Entity/Manager/ProgramManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/ProgramRepository.php
Harder, Better, Faster, Stronger...
Fixes #1415
=> Use DTO pattern for Programs API

UPGRADE.md
see https://github.com/ilios/ilios/pull/1399#issuecomment-218521018 for reference.
=> provided general upgrade notes for ilios3.

src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
=> added min and max attributes on sequence blocks to ci export.

src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Form/Type/CourseType.php, src/Ilios/CoreBundle/Tests/Entity/CourseTest.php
=> reject course input without school.

src/Ilios/WebBundle/Service/WebIndexFromJson.php
Required change to provide AAMC resource types added in #1399
=> Update API to v1.5

src/Ilios/AuthenticationBundle/Controller/AuthenticationController.php, src/Ilios/AuthenticationBundle/Resources/config/routing.yml, src/Ilios/AuthenticationBundle/Service/JsonWebTokenAuthenticator.php, src/Ilios/AuthenticationBundle/Tests/Controller/AuthenticationControllerTest.php
Allows for the addition of invalidation ability to the frontend
Fixes #1439
=> Allow tokens to be invalidated at /auth/invalidatetokens

composer.json, composer.lock
- composer update
- removed abandoned php-unit-skeleton-generator package
=> Update dependencies and remove dead packages

app/Resources/DoctrineMigrations/Version20160607171112.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryAcademicLevel.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequence.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlockSession.php
=> enable cascading deletes from curriculum inventory reports.

app/config/config.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis, src/Ilios/AuthenticationBundle/DependencyInjection/Configuration.php, src/Ilios/AuthenticationBundle/DependencyInjection/IliosAuthenticationExtension.php, src/Ilios/AuthenticationBundle/Resources/config/services.yml, src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, src/Ilios/AuthenticationBundle/Tests/DependencyInjection/IliosAuthenticationExtensionTest.php, src/Ilios/AuthenticationBundle/Tests/Service/ShibbolethAuthenticationTest.php, src/Ilios/WebBundle/Controller/ConfigController.php
=> made shibb login/logout path and asserted user id attr configurable.

app/Resources/updateSchemaFromIlios2toIlios3.sql
This resolves some conflicts which result from FK references in some
versions of mysql (5.1, 5.6).
Fixes #1452
=> Move drop tables further up in update script

src/Ilios/CoreBundle/Classes/LoggerQueue.php, src/Ilios/CoreBundle/EventListener/LogEntityChanges.php, src/Ilios/CoreBundle/EventListener/LoggerQueueListener.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/Logger.php, src/Ilios/CoreBundle/Tests/Classes/LoggerQueueTest.php
=> log auditable entity creation with record ids.

src/Ilios/CoreBundle/Entity/CurriculumInventorySequence.php
=> fixed toString magic method.

src/Ilios/CoreBundle/Entity/Competency.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequence.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/Offering.php, src/Ilios/CoreBundle/Entity/ProgramYear.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/SessionType.php
=> replaced __toString method with trait.

app/Resources/DoctrineMigrations/Version20160615223611.php, app/config/routing.yml, src/Ilios/CoreBundle/Classes/CurriculumInventoryReportDecorator.php, src/Ilios/CoreBundle/Controller/CurriculumInventoryDownloadController.php, src/Ilios/CoreBundle/Controller/CurriculumInventoryReportController.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryReport.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryReportInterface.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/CurriculumInventoryReportDecoratorFactory.php, src/Ilios/CoreBundle/Tests/Controller/CurriculumInventoryDownloadControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/CurriculumInventoryReportControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/CurriculumInventoryReportData.php, src/Ilios/CoreBundle/Tests/DataLoader/CurriculumInventorySequenceData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadCurriculumInventoryReportData.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php
=> Ci report dl token

src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Tests/Controller/SessionControllerTest.php
=> Allow sessions to be filtered by multiple courses

src/Ilios/CoreBundle/Classes/CourseRollover.php
this was emitting a warning when zero week offset was calculated.
fixed.
=> fixed rollover offset bug.

UPGRADE.md
2nd try. 
i foolishly put that flag into the wrong place last night. hereby fixed.
=> moved the --append flag to the right place.

src/Ilios/CoreBundle/Resources/dataimport/aamc_resource_type.csv
Copied straight out of MS Word originally, b/c that never goes wrong.
=> replaced hokey dash with default dash.

src/Ilios/CoreBundle/Classes/CourseRollover.php, src/Ilios/CoreBundle/Tests/Classes/CourseRolloverTest.php
=> Functional changes to original course rollover to account for date drifting over years

src/Ilios/CoreBundle/Classes/CourseRollover.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Tests/Classes/CourseRolloverTest.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php, src/Ilios/CoreBundle/Tests/Entity/SessionTest.php
Fixes #1496 
Fixes #1487
Needs:
=> Course rollover sessions and ilm bugfix

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
bug! this affects the list of courses returned for the current user's "my courses" list.
=> corrected table joins in query.

CHANGELOG.md
=> updating changelog for the v3.14.1 release

CHANGELOG.md
=> updating changelog for the v3.15.0 release

src/Ilios/CliBundle/Command/InstallFirstUserCommand.php
=> grant dev role to first user instead of course director.

src/Ilios/CoreBundle/DataFixtures/ORM/LoadCompetencyData.php, src/Ilios/CoreBundle/DataFixtures/ORM/LoadTermData.php, src/Ilios/CoreBundle/DataFixtures/ORM/LoadVocabularyData.php, src/Ilios/CoreBundle/Resources/dataimport/competency.csv, src/Ilios/CoreBundle/Resources/dataimport/term.csv, src/Ilios/CoreBundle/Resources/dataimport/vocabulary.csv, src/Ilios/CoreBundle/Tests/DataFixtures/ORM/LoadCompetencyDataTest.php, src/Ilios/CoreBundle/Tests/DataFixtures/ORM/LoadTermDataTest.php, src/Ilios/CoreBundle/Tests/DataFixtures/ORM/LoadVocabularyDataTest.php
refs #1519.
follow-up item to #1520.
=> added active flag to competency/vocab/term initial data set.

src/Ilios/CliBundle/Command/InstallFirstUserCommand.php, src/Ilios/CliBundle/Tests/Command/InstallFirstUserCommandTest.php
=> make "user zero" a course director again.

app/Resources/DoctrineMigrations/Version20150805000000.php
refs https://github.com/ilios/ilios/pull/1451#issuecomment-235162607
=> replaced call to non-existent method with one of the same intent that works.

src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Form/Type/CurriculumInventorySequenceBlockType.php, src/Ilios/CoreBundle/Tests/Entity/CurriculumInventorySequenceBlockTest.php
start/end date are not required per se. removed constraints.
=> make sequence block start/end date optional

src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Tests/DataLoader/CurriculumInventorySequenceBlockData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadCurriculumInventorySequenceBlockData.php
=> annotate the track property as exposed.

src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlockInterface.php
=> allow course prop to be set to null.

app/config/config.yml, app/config/config_dev.yml, app/config/services.yml, composer.json, composer.lock
Makes development logs much easier to read.
Fixes #1551
=> Add EasyLog logger

src/Ilios/WebBundle/Controller/DirectoryController.php, src/Ilios/WebBundle/Resources/config/routing.yml, tests/WebBundle/Controller/DirectoryControllerTest.php
This searches for a user by id and returns their LDAP record.
Fixes #1556
=> Add find to directory lookup

src/Ilios/WebBundle/Service/WebIndexFromJson.php
Added the single user sync endpoint.
=> Bump the supplied API version to v1.9

CHANGELOG.md
=> updating CHANGELOG.md file for v3.18.0 release

src/Ilios/WebBundle/Service/WebIndexFromJson.php
=> Correct typo for AWS_BUCKET

src/Ilios/WebBundle/Controller/IcsController.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/LearningMaterialControllerTest.php, tests/CoreBundle/Controller/OfferingControllerTest.php, tests/CoreBundle/Controller/UsereventControllerTest.php, tests/CoreBundle/DataLoader/CourseData.php, tests/CoreBundle/DataLoader/CourseLearningMaterialData.php, tests/CoreBundle/DataLoader/LearningMaterialData.php, tests/CoreBundle/DataLoader/OfferingData.php, tests/CoreBundle/DataLoader/SessionData.php, tests/CoreBundle/DataLoader/UserData.php, tests/CoreBundle/Fixture/LoadLearningMaterialData.php, tests/WebBundle/Controller/IcsControllerTest.php
Symfony 3 introduced a new way of getting the absolute path.
WIP:
Fixes #1574
=> Fix Learning Material absolute path

CHANGELOG.md
=> updating changelog for the v3.18.1 release

src/Ilios/AuthenticationBundle/Voter/LockableVoter.php, src/Ilios/CoreBundle/Controller/CourseController.php, src/Ilios/CoreBundle/Controller/ProgramYearController.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/ProgramYearControllerTest.php
Courses and program years can be unlocked by developers
Fixes #1582
=> Allow lockable entities to be unlocked

CHANGELOG.md
=> Updating the CHANGELOG.md file v3.19.0 release

app/Resources/DoctrineMigrations/Version20160919224121.php, src/Ilios/CoreBundle/Entity/LearnerGroup.php
=> Cascade learner group deletes to sub groups

app/Resources/DoctrineMigrations/Version20160921175624.php, src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php
This gives more space for automated tools to store long descriptive IDs
in this field.
Fixes #1598
=> Expand Course externalId to 255 characters

src/Ilios/AuthenticationBundle/Service/FormAuthentication.php, src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php, src/Ilios/CoreBundle/Entity/Repository/AuthenticationRepository.php, tests/AuthenticationBundle/Controller/AuthenticationControllerTest.php
=> issue correct HTTP response on authn failure

CHANGELOG.md
=> updating changelog for the v3.20.0 release

src/Ilios/CoreBundle/Controller/CurriculumInventoryDownloadController.php, tests/CoreBundle/Controller/CurriculumInventoryDownloadControllerTest.php
=> set a cookie to report download response.

app/Resources/DoctrineMigrations/Version20161012025413.php, src/Ilios/CoreBundle/Entity/DTO/SchoolDTO.php, src/Ilios/CoreBundle/Entity/DTO/UserDTO.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/SchoolInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php, src/Ilios/CoreBundle/Form/Type/SchoolType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/CoreBundle/Controller/SchoolControllerTest.php, tests/CoreBundle/Controller/UserControllerTest.php, tests/CoreBundle/DataLoader/SchoolData.php, tests/CoreBundle/DataLoader/UserData.php, tests/CoreBundle/Entity/SchoolTest.php, tests/CoreBundle/Entity/UserTest.php, tests/CoreBundle/Fixture/LoadUserData.php
This allows school directors to be specified which will eventually be
used to validate permissions.
Fixes #1617
=> Add directors relationship to school

app/Resources/DoctrineMigrations/Version20161013164943.php, src/Ilios/CoreBundle/Entity/DTO/SessionDTO.php, src/Ilios/CoreBundle/Entity/DTO/UserDTO.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php, src/Ilios/CoreBundle/Form/Type/SessionType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, src/Ilios/CoreBundle/Traits/AdministratorsEntity.php, src/Ilios/CoreBundle/Traits/AdministratorsEntityInterface.php, tests/CoreBundle/Controller/SessionControllerTest.php, tests/CoreBundle/Controller/UserControllerTest.php, tests/CoreBundle/DataLoader/SessionData.php, tests/CoreBundle/DataLoader/UserData.php, tests/CoreBundle/Entity/SessionTest.php, tests/CoreBundle/Entity/UserTest.php, tests/CoreBundle/Fixture/LoadSessionData.php
This will allow us to offer instructor access to sessions to non-instructors.
Fixes #1624
=> Add administrator relationship to session

app/Resources/DoctrineMigrations/Version20161013205034.php, src/Ilios/CoreBundle/Entity/DTO/SchoolDTO.php, src/Ilios/CoreBundle/Entity/DTO/UserDTO.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/SchoolInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php, src/Ilios/CoreBundle/Form/Type/SchoolType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, tests/CoreBundle/Controller/SchoolControllerTest.php, tests/CoreBundle/DataLoader/SchoolData.php, tests/CoreBundle/DataLoader/UserData.php, tests/CoreBundle/Entity/SchoolTest.php, tests/CoreBundle/Entity/UserTest.php, tests/CoreBundle/Fixture/LoadUserData.php
=> Add administrator relationship to school

app/Resources/DoctrineMigrations/Version20161014032909.php, src/Ilios/CoreBundle/Entity/DTO/ProgramDTO.php, src/Ilios/CoreBundle/Entity/DTO/UserDTO.php, src/Ilios/CoreBundle/Entity/Program.php, src/Ilios/CoreBundle/Entity/ProgramInterface.php, src/Ilios/CoreBundle/Entity/Repository/ProgramRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php, src/Ilios/CoreBundle/Form/Type/ProgramType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, tests/CoreBundle/Controller/ProgramControllerTest.php, tests/CoreBundle/Controller/UserControllerTest.php, tests/CoreBundle/DataLoader/ProgramData.php, tests/CoreBundle/DataLoader/UserData.php, tests/CoreBundle/Entity/ProgramTest.php, tests/CoreBundle/Entity/UserTest.php, tests/CoreBundle/Fixture/LoadUserData.php
=> Add director to program

.travis.yml, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/ProgramControllerTest.php, tests/CoreBundle/Controller/ProgramYearControllerTest.php
=> runs PHPCS against /tests dir

composer.json, composer.lock
note that PHPUnit 5.6 requires PHP 5.6.
https://phpunit.de/manual/5.6/en/installation.html
=> updated PHPUnit to version 5.6

src/Ilios/WebBundle/Controller/ConfigController.php, tests/WebBundle/Controller/ConfigControllerTest.php
This will allow the frontend to determine the maximum allowed size for
file uploads.
Fixes #1648
=> Add maxUploadSize key to config

src/Ilios/CoreBundle/Controller/CurriculumInventoryReportController.php
=> enforce create perms check on rollover request.

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/CoreBundle/Controller/UserControllerTest.php
This allows users to be found by their learner session affiliations.
Fixes #1643
=> Add learnerSessions filter to users

INSTALL.md
update MySQL version requirements to 5.5+, as discussed in our meeting.
=> updated version requirements in INSTALL.md

INSTALL.md
=> added frontend-update command instructions

src/Ilios/CoreBundle/Controller/UsermaterialsController.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/CoreBundle/Controller/UsermaterialsControllerTest.php
Allows specifying a before / after date to get materials between two
times.
Fixes #1661
=> Filter Usermaterials by date

app/config/config_dev.yml
Not doing this is deprecated in Symfony 3.
Fixes #1685
=> Quote configuration parameters

composer.lock
Ran `composer update` made these changes:
```
+------------------------------------------------+
| Production Changes         | From    | To      |
+------------------------------------------------+
| doctrine/annotations       | v1.2.7  | v1.3.0  |
| doctrine/cache             | v1.6.0  | v1.6.1  |
| doctrine/common            | v2.6.1  | v2.6.2  |
| doctrine/data-fixtures     | v1.2.1  | v1.2.2  |
| guzzlehttp/promises        | 1.2.0   | 1.3.0   |
| jms/serializer             | 1.3.1   | 1.4.2   |
| michelf/php-markdown       | 1.6.0   | 1.7.0   |
| monolog/monolog            | 1.21.0  | 1.22.0  |
| paragonie/random_compat    | v2.0.3  | v2.0.4  |
| php-http/discovery         | v1.1.0  | v1.1.1  |
| sensio/distribution-bundle | v5.0.13 | v5.0.14 |
| swiftmailer/swiftmailer    | v5.4.3 …
```
=> Updated Dependencies

src/Ilios/CoreBundle/EventListener/TrackApiUsageListener.php, tests/CoreBundle/EventListener/TrackApiUsageListenerTest.php
=> catch and log tracking exceptions.

src/Ilios/CoreBundle/EventListener/TrackApiUsageListener.php, src/Ilios/CoreBundle/Resources/config/services.yml, tests/CoreBundle/EventListener/TrackApiUsageListenerTest.php
=> refactored track api usage listener w/o container aware trait.

tests/CoreBundle/Classes/CourseRolloverTest.php
fixes #1700. hopefully permanently.
=> another attempt to make tests pass if we're rolling over year boundaries.

composer.json, composer.lock, src/Ilios/CliBundle/Resources/config/services.yml
=> fix deprecation warnings

composer.json, composer.lock
=> Composer require apcu

INSTALL.md
this should make this easier to find.
=> moving url rewriting instructions into its own section.

.travis.yml, tests/CoreBundle/Classes/CourseRolloverTest.php
=> added php 7.1 to test matrix

tests/CoreBundle/DataLoader/SessionTypeData.php
=> fixed fixture data.

src/Ilios/CoreBundle/Entity/Repository/LearnerGroupRepository.php, tests/CoreBundle/Controller/LearnerGroupControllerTest.php
refs #1725 
the SQL equivalent of this filter is
```sql
SELECT DISTINCT lg.*
FROM `group` lg
LEFT JOIN offering_x_group oxg ON oxg.group_id = lg.group_id
LEFT JOIN offering o ON o.offering_id = oxg.offering_id
LEFT JOIN `session` s1 ON s1.session_id = o.session_id
LEFT JOIN session_x_term sxt1 ON sxt1.session_id = s1.session_id
LEFT JOIN term t1 ON t1.term_id = sxt1.term_id
LEFT JOIN course c1 ON c1.course_id = s1.course_id
LEFT JOIN course_x_term cxt1 ON cxt1.course_id = c1.course_id
LEFT JOIN term t2 ON t2.term_id = cxt1.term_id
LEFT JOIN ilm_session_facet_x_group ixg ON ixg.group_id = lg.group_id
LEFT JOIN ilm_session_facet i ON i.ilm_session_facet_id = ixg.ilm_session_facet_id
LEFT JOIN `session` s2 ON s2.session_id = i.session_id
LEFT JOIN session_x_term sxt2 ON sxt2.session_id = …
```
=> implemented filter by terms.

src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, tests/CoreBundle/Controller/TermControllerTest.php
=> filter terms by program years.

src/Ilios/WebBundle/Service/WebIndexFromJson.php
We made some updates to the filters available for terms and need to bump
the API version to isolate this support.
=> Update the API version we provide

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
=> include session terms in course filter

app/Resources/DoctrineMigrations/Version20170126193201.php, app/Resources/DoctrineMigrations/Version20170210175148.php, src/Ilios/CoreBundle/Entity/CourseLearningMaterial.php, src/Ilios/CoreBundle/Entity/CourseLearningMaterialInterface.php, src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php, src/Ilios/CoreBundle/Entity/SessionLearningMaterialInterface.php, src/Ilios/CoreBundle/Form/Type/CourseLearningMaterialType.php, src/Ilios/CoreBundle/Form/Type/SessionLearningMaterialType.php, src/Ilios/CoreBundle/Traits/SortableEntity.php, src/Ilios/CoreBundle/Traits/SortableEntityInterface.php, src/Ilios/WebBundle/Controller/IcsController.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/CoreBundle/DataLoader/CourseLearningMaterialData.php, tests/CoreBundle/DataLoader/SessionLearningMaterialData.php, tests/CoreBundle/Entity/CourseLearningMaterialTest.php, tests/CoreBundle/Entity/SessionLearningMaterialTest.php, tests/CoreBundle/Fixture/LoadCourseLearningMaterialData.php, tests/CoreBundle/Fixture/LoadSessionLearningMaterialData.php
=> sortable course/session learning materials

src/Ilios/AuthenticationBundle/Voter/Entity/UserEntityVoter.php
=> consider is-root attribute in user voter

src/Ilios/CoreBundle/Resources/config/managers.yml
All of these entities were made into DTOs in #1698 and their managers
should have been changed to reflect this.
=> Fix managers that should be DTOs

app/Resources/DoctrineMigrations/Version20170309175718.php, app/Resources/DoctrineMigrations/Version20170314175718.php, src/Ilios/ApiBundle/Resources/swagger/definitions/Objective.yml, src/Ilios/CoreBundle/Entity/DTO/ObjectiveDTO.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/ObjectiveInterface.php, tests/CoreBundle/DataLoader/ObjectiveData.php, tests/CoreBundle/Entity/ObjectiveTest.php, tests/CoreBundle/Fixture/LoadObjectiveData.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php
=> Sortable objectives

CHANGELOG.md
We will exclusively use release notes for all future releases.
=> End change log

src/Ilios/CoreBundle/Service/LoggerQueue.php
By the time our entities hit the logger they have already been removed
from the database and have no ID. By recording the ID earlier in the
process we can ensure it is present for logging.
=> Log the ID of deleted items

ILIOS_API.md
Added the 'official' second dash to the X-JWT-Authorization header attribute name
=> added extra dash to X-JWT-Authorization header

src/Ilios/ApiBundle/Resources/views/swagger/description.markdown.twig
=> added second dash to X-JWT-Authorization header attribute in swagger template

src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Classes/UserEvent.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/IliosApiBundle/Endpoints/UsereventTest.php
these are:
- `externalCourseId`
- `sessionDescription`
- `sessionTypeTitle`
- `learningMaterials`
refs ilios/frontend#2756
=> Expose additional data points in user events

src/Ilios/ApiBundle/Controller/OfferingController.php, src/Ilios/CoreBundle/Entity/Offering.php, tests/IliosApiBundle/Endpoints/OfferingTest.php
=> Create an alert when offering site is modified

src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, tests/IliosApiBundle/Endpoints/LearningMaterialTest.php
This allows the free text search to include this value.
Fixes #1791
=> Add originalAuthor to learning material search

src/Ilios/WebBundle/Service/WebIndexFromJson.php
=> API version bump to 1.17.

src/Ilios/CoreBundle/Classes/UserMaterial.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Service/UserMaterialFactory.php, tests/IliosApiBundle/Endpoints/UsermaterialsTest.php
=> Add instructors to the usermaterials endpoint

app/Resources/DoctrineMigrations/Version20170510165532.php, src/Ilios/CoreBundle/Entity/DTO/SessionTypeDTO.php, src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, src/Ilios/CoreBundle/Entity/SessionType.php, src/Ilios/CoreBundle/Entity/SessionTypeInterface.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/CoreBundle/DataLoader/SessionTypeData.php, tests/CoreBundle/Entity/CompetencyTest.php, tests/CoreBundle/Entity/SessionTypeTest.php, tests/CoreBundle/Entity/TermTest.php, tests/CoreBundle/Entity/VocabularyTest.php, tests/CoreBundle/Fixture/LoadSessionTypeData.php, tests/IliosApiBundle/Endpoints/SessionTypeTest.php
This will allow session types to be deactivated so they can be prevented
from being attached to sessions.
Fixes #1824
=> Add active status for sessionType

src/Ilios/CoreBundle/Entity/Repository/OfferingRepository.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/IliosApiBundle/Endpoints/OfferingTest.php
This can be used to pre-load offerings for a course in one request.
=> Filter offerings by course

src/Ilios/ApiBundle/Controller/AcademicYearController.php, src/Ilios/ApiBundle/Controller/ApiController.php, src/Ilios/ApiBundle/Controller/AuthenticationController.php, src/Ilios/ApiBundle/Controller/CoursesController.php, src/Ilios/ApiBundle/Controller/CurrentSessionController.php, src/Ilios/ApiBundle/Controller/CurriculumInventoryExportController.php, src/Ilios/ApiBundle/Controller/CurriculumInventoryReportController.php, src/Ilios/ApiBundle/Controller/CurriculumInventorySequenceBlockController.php, src/Ilios/ApiBundle/Controller/LearningMaterialController.php, src/Ilios/ApiBundle/Controller/NonDtoApiController.php, src/Ilios/ApiBundle/Controller/OfferingController.php, src/Ilios/ApiBundle/Controller/ProgramYearController.php, src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/SwaggerDocsController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/ApiBundle/Controller/UsermaterialController.php, src/Ilios/ApiBundle/Controller/UsersController.php, src/Ilios/ApiBundle/Normalizer/DTO.php, src/Ilios/ApiBundle/Normalizer/Entity.php, src/Ilios/ApiBundle/Resources/config/services.yml
Symfony 3 provides us with some dependency injection magic that saves
effort in configuring and using services.
This is a proof of concept for making this transition and we should discuss if it is right for us at this point. More information on this can be found at:
https://symfony.com/doc/current/service_container/3.3-di-changes.html
If this works we can apply it to the other bundles in pieces and save significant effort in the setup and injection of new services.
=> Use autowire / autoconfigure in ApiBundle

src/Ilios/CoreBundle/Entity/Repository/IlmSessionRepository.php, tests/IliosApiBundle/Endpoints/IlmSessionTest.php
This is useful when loading a course
=> Filter IlmSession by courses and sessions

src/Ilios/ApiBundle/Resources/config/config.yml, src/Ilios/CoreBundle/Entity/Manager/ObjectiveManager.php, src/Ilios/CoreBundle/Entity/Repository/ObjectiveRepository.php
All the work was already done, just mis-labeled the Manager.
=> Correctly mark Objective as a DTO

composer.lock
+---------------------------------------------------+
| Production Changes              | From   | To     |
+---------------------------------------------------+
| symfony/symfony                 | v3.3.4 | v3.3.5 |
| zendframework/zend-eventmanager | 3.1.0  | 3.2.0  |
+---------------------------------------------------+
+---------------------------------------------+
| Dev Changes               | From   | To     |
+---------------------------------------------+
| sensio/generator-bundle   | v3.1.4 | v3.1.6 |
| squizlabs/php_codesniffer | 3.0.1  | 3.0.2  |
| symfony/phpunit-bridge    | v3.3.4 | v3.3.5 |
+---------------------------------------------+
=> Ran `composer update` to update dependencies

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Classes/SessionUserInterface.php, src/Ilios/AuthenticationBundle/Voter/CourseVoter.php, src/Ilios/CoreBundle/Entity/Manager/CourseManager.php, tests/WebBundle/Controller/DirectoryControllerTest.php
This really only affected directors who do not have read permission in the course's school.
Fixes #1827
=> Allow users to view courses they are directing

src/Ilios/ApiBundle/Resources/config/config.yml, src/Ilios/AuthenticationBundle/Voter/DTO/MeshDTOVoter.php, src/Ilios/CoreBundle/Entity/DTO/MeshConceptDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshPreviousIndexingDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshQualifierDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshSemanticTypeDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshTermDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshTreeDTO.php, src/Ilios/CoreBundle/Entity/MeshConcept.php, src/Ilios/CoreBundle/Entity/MeshPreviousIndexing.php, src/Ilios/CoreBundle/Entity/MeshQualifier.php, src/Ilios/CoreBundle/Entity/MeshSemanticType.php, src/Ilios/CoreBundle/Entity/MeshTerm.php, src/Ilios/CoreBundle/Entity/MeshTree.php, src/Ilios/CoreBundle/Entity/Repository/MeshConceptRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshPreviousIndexingRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshQualifierRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshSemanticTypeRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshTermRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshTreeRepository.php, src/Ilios/CoreBundle/Resources/config/dto-managers.yml, src/Ilios/CoreBundle/Resources/config/non-dto-managers.yml, tests/IliosApiBundle/Endpoints/MeshConceptTest.php, tests/IliosApiBundle/Endpoints/MeshQualifierTest.php, tests/IliosApiBundle/Endpoints/MeshSemanticTypeTest.php, tests/IliosApiBundle/Endpoints/MeshTermTest.php
Why? Well because I like it better when things are faster!
=> Convert remaining Mesh endpoints to the DTO pattern

src/Ilios/ApiBundle/Normalizer/Entity.php
Symfony is throwing a different exception here now.
Also log set exceptions in the denormalizer
Instead of just swallowing these errors we should log them so we can
correct the offending class.
=> Trap the right exception for set errors

src/Ilios/ApiBundle/Controller/SwaggerDocsController.php
=> make swagger.yml url schema relative.

src/Ilios/CoreBundle/Entity/CurriculumInventoryExport.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryReport.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryReportInterface.php
=> allow for null values in setters.

src/Ilios/AuthenticationBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/Fetch.php
=> must declare CasManager service as public.

src/Ilios/CoreBundle/Entity/LearningMaterial.php
=> prevent mimetype clobbering.

UPGRADE.md
We added a command to fix mimetypes and need to provide instructions for
running this command.
Refs #1897
=> Add Upgrade instructions for upcoming v3.36.1

src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
=> rm whitespace from url.

src/Ilios/CliBundle/Command/SetupAuthenticationCommand.php, tests/CliBundle/Command/InstallFirstUserCommandTest.php, tests/CliBundle/Command/SetupAuthenticationCommandTest.php
This makes it easier to configure the variables required for each type
of configuration.
=> Add dialog command for setting up authentication

src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php
=> Exclude orphaned descriptors from mesh search

app/Resources/DoctrineMigrations/Version20170917182423.php, app/Resources/DoctrineMigrations/Version20170917183718.php, src/Ilios/ApiBundle/Resources/swagger/definitions/Meshconcept.yml, src/Ilios/ApiBundle/Resources/swagger/definitions/Meshterm.yml, src/Ilios/CoreBundle/Entity/DTO/MeshConceptDTO.php, src/Ilios/CoreBundle/Entity/DTO/MeshTermDTO.php, src/Ilios/CoreBundle/Entity/MeshConcept.php, src/Ilios/CoreBundle/Entity/MeshConceptInterface.php, src/Ilios/CoreBundle/Entity/MeshTerm.php, src/Ilios/CoreBundle/Entity/MeshTermInterface.php, src/Ilios/CoreBundle/Entity/Repository/MeshConceptRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php, src/Ilios/CoreBundle/Entity/Repository/MeshTermRepository.php, tests/CoreBundle/DataFixtures/ORM/LoadMeshConceptDataTest.php, tests/CoreBundle/DataFixtures/ORM/LoadMeshTermDataTest.php, tests/CoreBundle/DataLoader/MeshConceptData.php, tests/CoreBundle/DataLoader/MeshTermData.php, tests/CoreBundle/Entity/MeshConceptTest.php, tests/CoreBundle/Entity/MeshTermTest.php, tests/CoreBundle/Fixture/LoadMeshConceptData.php, tests/CoreBundle/Fixture/LoadMeshTermData.php, tests/CoreBundle/Service/MeshDescriptorSetTransmogrifierTest.php, tests/IliosApiBundle/Endpoints/MeshConceptTest.php, tests/IliosApiBundle/Endpoints/MeshTermTest.php
=> Removes deprecated properties from MeSH data points.

src/Ilios/ApiBundle/Resources/swagger/definitions/UserMaterial.yml, src/Ilios/CoreBundle/Classes/UserMaterial.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Service/UserMaterialFactory.php, tests/CoreBundle/Classes/UserMaterialTest.php, tests/IliosApiBundle/Endpoints/UsereventTest.php, tests/IliosApiBundle/Endpoints/UsermaterialsTest.php
=> added missing properties to user materials.

composer.json, composer.lock, src/Ilios/CoreBundle/Service/Config.php, tests/CoreBundle/Service/ConfigTest.php
1. Bad snake casing we were converting `requireSecureConnection` into `ILIOS_REQUIRESECURECONNECTION` and it should be `ILIOS_REQUIRE_SECURE_CONNECTION`
2. Fix casting of falsy values
=> Fix two issues with our parsing of config variables

README.md, docs/custom_cli_commands.md
=> document custom commands.

CODE_OF_CONDUCT.md
=> added a code of conduct document.

docs/custom_cli_commands.md
=> Add docs for MeSH Update

.travis.yml
=> Switch Travis builds to Trusty distro

app/config/config.yml, src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/Resources/views/WebIndex/webindex.html.twig, tests/WebBundle/Controller/IndexControllerTest.php
The new version of the frontend includes more information in the deploy
for the error, loading, and noscript sections so we can use that to
build a better frontend.
=> Parse new sections of deployed index.json

src/Ilios/WebBundle/Resources/views/Index/error.html.twig
=> fixed link to frontend update docs.

src/Ilios/ApiBundle/Normalizer/Entity.php, src/Ilios/CoreBundle/Entity/MeshTerm.php, src/Ilios/CoreBundle/Entity/SessionType.php
=> trim whitespace off of "string" attributes during denormalization.

app/config/config.yml, src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/Resources/views/WebIndex/webindex.html.twig
The link element can now contain sizes and type attributes for use in
icons.
Wait to merge requires https://github.com/ilios/frontend/pull/3365
=> Handle the new attributes from the frontend

docs/ilios_php_version_policy.md, docs/install.md
=> update php version policies

src/Ilios/ApiBundle/Controller/AuthenticationController.php, src/Ilios/AuthenticationBundle/Service/CasAuthentication.php, src/Ilios/AuthenticationBundle/Service/FormAuthentication.php, src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php, src/Ilios/AuthenticationBundle/Service/SessionUserProvider.php, src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, src/Ilios/CliBundle/Command/AddUserCommand.php, src/Ilios/CliBundle/Command/InstallFirstUserCommand.php, src/Ilios/CoreBundle/Entity/Authentication.php, src/Ilios/CoreBundle/Entity/AuthenticationInterface.php, tests/AuthenticationBundle/Service/FormAuthenticationTest.php, tests/AuthenticationBundle/Service/LdapAuthenticationTest.php, tests/AuthenticationBundle/Service/ShibbolethAuthenticationTest.php, tests/CliBundle/Command/AddUserCommandTest.php, tests/CliBundle/Command/InstallFirstUserCommandTest.php
=> refactored session user instantiation

src/Ilios/AuthenticationBundle/RelationshipVoter/AamcMethod.php, src/Ilios/AuthenticationBundle/RelationshipVoter/AamcPcrs.php, src/Ilios/AuthenticationBundle/RelationshipVoter/AamcResourceType.php, tests/AuthenticationBundle/RelationshipVoter/AamcMethod.php, tests/AuthenticationBundle/RelationshipVoter/AamcPcrs.php, tests/AuthenticationBundle/RelationshipVoter/AamcResourceType.php
=> aamc* voters - root can edit, everyone else can read.

src/Ilios/AuthenticationBundle/RelationshipVoter/SessionType.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/SessionTypeTest.php
=> session types permissions/voter

src/Ilios/AuthenticationBundle/RelationshipVoter/SessionType.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php
=> 1950 session type fix

src/Ilios/AuthenticationBundle/RelationshipVoter/Department.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/DepartmentTest.php
=> new perms and voter for department.

src/Ilios/AuthenticationBundle/RelationshipVoter/SchoolConfig.php, src/Ilios/AuthenticationBundle/RelationshipVoter/SessionType.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/SchoolConfigTest.php
=> new perms and voter for school config.

tests/WebBundle/Controller/DirectoryControllerTest.php
Needed to mock out the new SessionUser setup correctly. This might not
be the final form of this test, but it does work for now.
=> Fixup directory test

src/Ilios/AuthenticationBundle/RelationshipVoter/School.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/SchoolTest.php
_of note_: new school creation is allowed to root users only, therefore there is no "create school" permission.
refs #1950
=> new perms and voter for school.

src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, tests/IliosApiBundle/Endpoints/LearningMaterialTest.php
This returns materials that are connected to a course or any session in
that course.
Required for ilios/frontend#2445
=> Filter learning materials by fullCourses

src/Ilios/AuthenticationBundle/RelationshipVoter/InstructorGroup.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Term.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Vocabulary.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, src/Ilios/CoreBundle/Entity/DTO/TermDTO.php, src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, tests/AuthenticationBundle/RelationshipVoter/AamcMethodTest.php, tests/AuthenticationBundle/RelationshipVoter/AamcPcrsTest.php, tests/AuthenticationBundle/RelationshipVoter/AamcResourceTypeTest.php, tests/AuthenticationBundle/RelationshipVoter/ApplicationConfigTest.php, tests/AuthenticationBundle/RelationshipVoter/AssessmentOptionTest.php, tests/AuthenticationBundle/RelationshipVoter/CohortTest.php, tests/AuthenticationBundle/RelationshipVoter/CompetencyTest.php, tests/AuthenticationBundle/RelationshipVoter/CourseClerkshipTypeTest.php, tests/AuthenticationBundle/RelationshipVoter/CourseTest.php, tests/AuthenticationBundle/RelationshipVoter/DepartmentTest.php, tests/AuthenticationBundle/RelationshipVoter/InstructorGroupTest.php, tests/AuthenticationBundle/RelationshipVoter/MeshTest.php, tests/AuthenticationBundle/RelationshipVoter/ProgramTest.php, tests/AuthenticationBundle/RelationshipVoter/ProgramYearTest.php, tests/AuthenticationBundle/RelationshipVoter/SchoolConfigTest.php, tests/AuthenticationBundle/RelationshipVoter/SchoolTest.php, tests/AuthenticationBundle/RelationshipVoter/SessionTest.php, tests/AuthenticationBundle/RelationshipVoter/SessionTypeTest.php, tests/AuthenticationBundle/RelationshipVoter/TermTest.php, tests/AuthenticationBundle/RelationshipVoter/VocabularyTest.php
=> new perms and voters

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Classes/SessionUserInterface.php, src/Ilios/AuthenticationBundle/Classes/UserRoles.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Course.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryAcademicLevel.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryExport.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryInstitution.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryReport.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequence.php, src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceBlock.php, src/Ilios/AuthenticationBundle/RelationshipVoter/InstructorGroup.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Service/CurriculumInventory/ReportRollover.php, tests/AuthenticationBundle/RelationshipVoter/AbstractBase.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryAcademicLevelTest.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryExportTest.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryInstitutionTest.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryReportTest.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceBlockTest.php, tests/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceTest.php, tests/WebBundle/Controller/DirectoryControllerTest.php
=> curriculum inventory perms and voters

composer.lock
trying to upgrade ourselves out of this :crossed_fingers: 
fixes #2024
=> updated dependencies.

tests/IliosApiBundle/Endpoints/CourseTest.php
=> fixed up rollover test. added rollover failure test.

tests/AuthenticationBundle/Service/PermissionCheckerTest.php
since the interfaces are fairly stable now, i started to flesh out permissions checker tests.
refs #1950
=> permission checker test coverage

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Service/SessionUserProvider.php, tests/AuthenticationBundle/Classes/SessionUserTest.php
=> New perms feature flag performance

src/Ilios/CliBundle/Command/AuditLogExportCommand.php, tests/AuthenticationBundle/Classes/SessionUserTest.php, tests/CliBundle/Command/AuditLogExportCommandTest.php
=> Squish deprecation warnings

src/Ilios/CoreBundle/Entity/Manager/CohortManager.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Resources/config/virtual-managers.yml, src/Ilios/CoreBundle/Service/CourseRollover.php, tests/CoreBundle/Service/CourseRolloverTest.php
Breaking up #729 into smaller pieces, this is one of them.
=>  Allow courses to be linked to new cohorts when rolling over

src/Ilios/CoreBundle/Entity/Repository/ObjectiveRepository.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php
This allows deep filtering to those objectives that are linked to
sessions within a course.
Fixes #2051
=> Filter objectives by fullCourses

src/Ilios/AuthenticationBundle/Classes/Capabilities.php, src/Ilios/AuthenticationBundle/RelationshipVoter/School.php, src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/SchoolTest.php
per an earlier conversation with the team.
=> new permissions system: only root users can delete schools.

app/config/config.yml, tests/IliosApiBundle/Endpoints/ObjectiveTest.php
=> allow for target/_blank attr/value on anchor tags.

src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php
=> corrected parameter type declaration.

app/Resources/DoctrineMigrations/Version20180309225012.php
=> migration for activating all vocabs and competencies.

src/Ilios/WebBundle/Controller/ErrorController.php
=> inject logger directly into controller action.

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Voter/CourseVoter.php, src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
fixes performance problems introduced by conversion from raw SQL to DQL.
=> fixes performance issue with "my courses"

src/Ilios/CoreBundle/Resources/views/Email/teachingreminder.text.twig, tests/CliBundle/Command/SendTeachingRemindersCommandTest.php
=> Add offering site to teaching reminder template

src/Ilios/CliBundle/Command/SyncUserCommand.php, tests/CliBundle/Command/SyncUserCommandTest.php
=> When syncing a user remove pending updates

src/Ilios/CliBundle/Command/ListConfigValuesCommand.php, src/Ilios/CliBundle/Command/ListSchoolConfigValuesCommand.php, src/Ilios/CliBundle/Command/SetConfigValueCommand.php, src/Ilios/CliBundle/Command/SetSchoolConfigValueCommand.php, src/Ilios/CoreBundle/Entity/Manager/SchoolConfigManager.php, src/Ilios/CoreBundle/Entity/Repository/SchoolConfigRepository.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Resources/config/virtual-managers.yml, tests/CliBundle/Command/ListSchoolConfigValuesCommandTest.php, tests/CliBundle/Command/SetSchoolConfigValueCommandTest.php
Allows viewing and setting school configuration values from the command line
=> Add School Config Commands

composer.lock
| Production Changes             | From    | To      | Compare                                                               |
|--------------------------------|---------|---------|-----------------------------------------------------------------------|
| composer/ca-bundle             | 1.1.0   | 1.1.1   | https://github.com/composer/ca-bundle/compare/1.1.0...1.1.1           |
| doctrine/dbal                  | v2.6.3  | v2.7.1  | https://github.com/doctrine/dbal/compare/v2.6.3...v2.7.1              |
| doctrine/doctrine-cache-bundle | 1.3.2   | 1.3.3   | https://github.com/doctrine/DoctrineCacheBundle/compare/1.3.2...1.3.3 |
| guzzlehttp/guzzle              | 6.3.1   | 6.3.2   | https://github.com/guzzle/guzzle/compare/6.3.1...6.3.2                |
| paragonie/random_compat        | …
=> Dependency Update

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> corrected botched attempt at flattening an assoc array.

src/Ilios/AuthenticationBundle/RelationshipVoter/ElevatedPermissionsViewDTOVoter.php, src/Ilios/AuthenticationBundle/RelationshipVoter/GreenlightViewDTOVoter.php, src/Ilios/AuthenticationBundle/RelationshipVoter/UserDTOVoter.php, tests/AuthenticationBundle/RelationshipVoter/AbstractBase.php, tests/AuthenticationBundle/RelationshipVoter/ElevatedPermissionsViewDTOVoterTest.php, tests/AuthenticationBundle/RelationshipVoter/UserDTOVoter.php
=> update user dto voter to allow users to see themselves

src/Ilios/AuthenticationBundle/RelationshipVoter/ReportDTOVoter.php, tests/AuthenticationBundle/RelationshipVoter/ReportDTOVoterTest.php, tests/AuthenticationBundle/RelationshipVoter/ReportTest.php
=> separated entity voter from dto voter for reports.

src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php, tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
=> rm caps to update/delete all sessions for course admin/director.

src/Ilios/AuthenticationBundle/RelationshipVoter/SchoolConfig.php, src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php, tests/AuthenticationBundle/RelationshipVoter/SchoolConfigTest.php, tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
=> consolidated capability checks for school configs.

src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php, tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
=> rm capabilities for program directors to update/delete ALL program years.

app/config/config.yml
We only want to serve a frontend that can handle the new permissions
system.
=> Bump the API versions

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/Service/PermissionCheckerTest.php
A root users token should include these privileges in addition to being root.
=> Give root more default stuff

.travis.yml
Ensures that any changes we make to docker can, at least, build and run.
=> Test our container build

app/Resources/DoctrineMigrations/Version20180313211111.php
fixes #1952 (see bottom comment there)
=> tweaks to perms migration

src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php, tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
=> grants update permissions on instructor groups to school- and program-directors

src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php
=> build permission matrices on demand.

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Classes/SessionUserInterface.php
=> consider program directors when checking for roles in school.

docs/install.md
=> updated Ilios version in install docs to match most up-to-date ilios version

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/AuthenticationBundle/Classes/SessionUserInterface.php, src/Ilios/AuthenticationBundle/RelationshipVoter/LearnerGroup.php, src/Ilios/AuthenticationBundle/RelationshipVoter/LearnerGroupDTOVoter.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Report.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, src/Ilios/CliBundle/Command/SyncUserCommand.php, src/Ilios/CliBundle/Command/UpdateFrontendCommand.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/AuthenticationBundle/Classes/SessionUserTest.php, tests/AuthenticationBundle/RelationshipVoter/ElevatedPermissionsViewDTOVoterTest.php, tests/AuthenticationBundle/RelationshipVoter/LearnerGroupDTOVoterTest.php, tests/AuthenticationBundle/RelationshipVoter/LearnerGroupTest.php, tests/AuthenticationBundle/Service/PermissionCheckerTest.php, tests/CliBundle/Command/SetSchoolConfigValueCommandTest.php
=> allow users to view the learner groups that they're a member of.

src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
=> broke up query into two, to get rid of non-standard UNION construct.

src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
=> add vocabulary terms linked to sessions as keywords to CI report.

src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
=> check instructor group membership when determining non-learner function status

src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseInterface.php, src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php, tests/CoreBundle/Entity/CourseTest.php
fixes #2152 
can be tested _best_ by pulling the same CI report using the code in this branch and using `master`. then comparing the output.
=> replaces raw SQL with DQL equivalents

app/Resources/DoctrineMigrations/Version20180514214501.php, src/Ilios/AuthenticationBundle/Classes/SessionUser.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php, src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlockInterface.php, src/Ilios/CoreBundle/Entity/DTO/CurriculumInventorySequenceBlockDTO.php, src/Ilios/CoreBundle/Entity/Repository/CurriculumInventorySequenceBlockRepository.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php, tests/CoreBundle/DataLoader/CurriculumInventorySequenceBlockData.php, tests/CoreBundle/Entity/CurriculumInventorySequenceBlockTest.php, tests/CoreBundle/Entity/SessionTest.php, tests/CoreBundle/Fixture/LoadCurriculumInventorySequenceBlockData.php, tests/IliosApiBundle/Endpoints/CurriculumInventorySequenceBlockTest.php
schema/model changes for #1989
=> link excluded sessions to CI sequence blocks.

src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php
=> corrected schema mapping annotation.

src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
=> correct reporting on events based on ilm sessions with offerings

src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php, src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
fixes #1989 
should also fix #1940
=> ignore excluded sessions in report

app/config/config.yml
Adds excludedSessions to CI sequence blocks from #2161
=> Bump the API version to 1.31

.travis.yml, src/Ilios/CoreBundle/Service/CurriculumInventory/Export/XmlPrinter.php
phpcs was not failing even when there are errors.
Fixes #2101
=> Split up lines in tests

src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php, src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Export/Aggregator.php, tests/CoreBundle/Entity/Manager/CurriculumInventoryReportManagerTest.php, tests/CoreBundle/Service/CurriculumInventory/Export/AggregatorTest.php
=> consolidate program objectives in CI report output

src/Ilios/CoreBundle/Service/CourseRollover.php, tests/CoreBundle/Service/CourseRolloverTest.php
=> clone position attribute with objectives and LMs on course rollover.

src/Ilios/CoreBundle/Service/CurriculumInventory/Export/XmlPrinter.php
=> corrected printing of resource types.

src/Ilios/WebBundle/Controller/IcsController.php, tests/WebBundle/Controller/IcsControllerTest.php
Instead of providing instructors, objectives, and learning materials we
can just provide a link to the session itself. This saves a lot of data
and processing and makes it possible to load more events.
Fixes #2169
=> Add a link to the event to the ICS feed

app/Resources/DoctrineMigrations/Version20180823181914.php, src/Ilios/ApiBundle/Resources/swagger/definitions/Session.yml, src/Ilios/CoreBundle/Entity/DTO/SessionDTO.php, src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Entity/SessionInterface.php, tests/CoreBundle/DataLoader/SessionData.php, tests/CoreBundle/Entity/SessionTest.php, tests/CoreBundle/Fixture/LoadSessionData.php, tests/IliosApiBundle/Endpoints/SessionTest.php
This allows sessions to be linked to other sessions for the purposes of
identifying items that should be completed before a session.
Refs #822
=> Add prerequisites to session

app/config/config.yml
This should have been done with the addition of postrequisite to Session in #2211
=> Bump the API to v1.34

tests/AppBundle/AbstractEndpointTest.php, tests/AppBundle/DataFixtures/ORM/AbstractDataFixtureTest.php, tests/AppBundle/Endpoints/AcademicYearTest.php, tests/AppBundle/Endpoints/AuthenticationTest.php, tests/AppBundle/Endpoints/CohortTest.php, tests/AppBundle/Endpoints/CourseTest.php, tests/AppBundle/Endpoints/CurrentSessionTest.php, tests/AppBundle/Endpoints/CurriculumInventoryInstitutionTest.php, tests/AppBundle/Endpoints/CurriculumInventorySequenceTest.php, tests/AppBundle/Endpoints/IlmSessionTest.php, tests/AppBundle/Endpoints/ObjectiveTest.php, tests/AppBundle/Endpoints/OfferingTest.php, tests/AppBundle/Endpoints/ProgramYearStewardTest.php, tests/AppBundle/Endpoints/ProgramYearTest.php, tests/AppBundle/Endpoints/SchooleventsTest.php, tests/AppBundle/Endpoints/SessionDescriptionTest.php, tests/AppBundle/Endpoints/SessionTest.php, tests/AppBundle/Endpoints/SessionTypeTest.php, tests/AppBundle/Endpoints/UsereventTest.php
The LiipFunctionalTestBundle provides these interfaces and our container
property actually overrides a static container in the base class which
probably shouldn't be allowed.
=> Use the container and client from our test bundle

app/AppKernel.php, composer.json, composer.lock
Remove twig/extensions and sensio/generator-bundle as we don't require them anymore.
Remove direct dependency on ocramius/proxy-manager as we don't need that workaround anymore since we support PHP 7.2
=> Remove unused dependencies

docker-compose.yml
This can work with the Dockerfile locally by using the build directive.
The ENV variables was wrong, fixed that as well.
=> Fix local development container

src/Entity/CurriculumInventorySequenceBlock.php, src/Entity/CurriculumInventorySequenceBlockInterface.php, tests/Endpoints/CurriculumInventorySequenceBlockTest.php
=> allow null value for parent setter arg.

tests/Service/ConfigTest.php
All of these pass, but they're important edge cases to think about.
=> Add some tests for different config scenarios

src/Command/SendTestEmailCommand.php, tests/Command/SendTestEmailCommandTest.php
Useful for testing if messages are working
=> Add a command to send a sample email

src/Entity/Term.php, src/Entity/TermInterface.php, tests/Endpoints/TermTest.php
=> Allow top level terms 

config/bundles.php
=> make fixtures bundle available in all environments.

tests/Endpoints/CourseTest.php
=> adjusted rollover test to new year.

src/Entity/Repository/UserRepository.php, tests/Endpoints/UsereventTest.php
Shared PR to work on fixes and add / fix tests.
=> Fix issues with pre/post requisites

composer.json, tests/Service/CurriculumInventory/Export/AggregatorTest.php
just a few minor things that popped up whilst reviewing this code today.
=> a hodgepodge of curriculum inventory export-related tweaks

src/Controller/UsersController.php, src/Entity/Manager/UserManager.php, src/Entity/Repository/UserRepository.php
These are way faster to create and much less memory intensive, especially
in a search which could return many results this is a big improvement which takes a simple search down from eight seconds to two.
=> When searching for users use DTOs

src/Entity/Repository/UserRepository.php
refs ilios/common#433
refs ilios/frontend#4240
=> consider administered courses when pulling user events.

.env.dist, docker-compose.yml
Shouldn't be on in development.
=> Turn off error capture by default

src/Controller/SchooleventController.php, src/Entity/Manager/SchoolManager.php, src/Entity/Repository/SchoolRepository.php, tests/Endpoints/SchooleventsTest.php
=> bolted pre/post-requisites onto school events.

src/Service/CourseRollover.php, tests/Service/CourseRolloverTest.php
If the postrequisite session is within the same course then roll over
that relationship as well.
Refs #822
=> Rollover postrequisites with course

src/Entity/Repository/UserRepository.php
=> retrieve user events based on session administrator relationships.

composer.json, composer.lock, config/services.yaml, docker-compose.yml, src/Classes/ElasticSearchBase.php, src/Command/PopulateIndexCommand.php, src/Entity/DTO/CourseDTO.php, src/Entity/DTO/UserDTO.php, src/Entity/Manager/CourseManager.php, src/Entity/Manager/UserManager.php, src/Entity/Repository/CourseRepository.php, src/Entity/Repository/UserRepository.php, src/EventListener/IndexEntityChanges.php, src/Service/Index.php, src/Service/Search.php, symfony.lock, tests/Command/PopulateIndexCommandTest.php, tests/Service/IndexTest.php, tests/Service/SearchTest.php
First draft of indexing and searching for users in ElasticSearch. I've also enable indexing for courses to give some contrast and also to work out the details of having a public and a private index. 
Wip:
=> Enable ElasticSearch for users

config/swagger/definitions/Schoolevent.yml, config/swagger/definitions/Userevent.yml
=> added missing post/pre-requisite properties to user/school-event definitions.

src/Command/ChangePasswordCommand.php, src/Command/ChangeUsernameCommand.php, src/Entity/Manager/AuthenticationManager.php, src/Entity/Repository/AuthenticationRepository.php, tests/Command/ChangePasswordCommandTest.php, tests/Command/ChangeUsernameCommandTest.php
Add commands to allow the username and password to be changed.
=> User management commands

.travis.yml, bin/phpunit
=> Default our tests to PHPUnit 7.5

.azure/api-test-job-template.yaml, .azure/install-steps-template.yaml, .azure/phpunit-job-template.yaml, azure-pipelines.yml, tests/Command/AddUserCommandTest.php, tests/Command/ChangePasswordCommandTest.php, tests/Helper/TestQuestionHelper.php
=> Add Azure Pipelines for CI/CD

azure-pipelines.yml
Pushing another branch will not trigger a build, opening a pull request
will.
=> Only build against the master branch

docker-compose.yml, src/Classes/ElasticSearchBase.php, src/Command/ImportMeshUniverseCommand.php, src/Command/PopulateIndexCommand.php, src/Entity/Manager/MeshDescriptorManager.php, src/Entity/Repository/MeshDescriptorRepository.php, src/Service/Index.php, src/Service/Search.php, tests/Command/ImportMeshUniverseCommandTest.php, tests/Command/PopulateIndexCommandTest.php, tests/Service/IndexTest.php, tests/Service/SearchTest.php
This creates a new index for mesh terms and populates it on demand and when the mesh universe is updated. When the index is enables all searches for MeSH terms will go through it.
=> Index and Search for MeSH using elasticsearch

config/swagger/definitions/Program.yml, config/swagger/definitions/Programyear.yml, src/Entity/DTO/ProgramDTO.php, src/Entity/DTO/ProgramYearDTO.php, src/Entity/Program.php, src/Entity/ProgramYear.php
refs #2379
refs ilios/frontend#3675
refs ilios/frontend#4416
=> flags publishing attributes for programs/program-years as deprecated.

src/Entity/Manager/UserManager.php, src/Service/Search.php
Without this the default for elasticsearch is 10 results.
Fixes #2383
=> Pass user search limit to search

src/Command/SendTeachingRemindersCommand.php, tests/Command/SendTeachingRemindersCommandTest.php
=> Use preferred email in teaching reminders, if available

src/Entity/LearningMaterialInterface.php
=> corrects arg name in docblock

src/Controller/ConfigController.php, src/Entity/Manager/UserManager.php, src/Service/Search.php, tests/Controller/ConfigControllerTest.php
=> Improve elastic search results order

src/Entity/Manager/UserManager.php
=> corrects type hints in argument list.

config/services.yaml, config/services_test.yaml, src/Command/ListConfigValuesCommand.php, src/Service/JsonWebTokenManager.php, tests/Command/ListConfigValuesCommandTest.php
This makes it easier to see what the final computed values are for
these.
=> Add ENV values to list config command

docs/authentication.md, docs/authentication_and_users.md, docs/shibboleth_authentication.md
Due to recent clarification requests for configuring shibboleth, this is the first new set up doc I'm pushing up... Still overhauling the parent ENV and config doc greatly, but hopefully will have the updates to that one up shortly...
=> Shibboleth docs

src/Classes/IndexableCourse.php, src/Classes/IndexableSession.php, src/Entity/Repository/CourseRepository.php, src/Service/Index.php, tests/Service/IndexTest.php
Improved this a bit by introducing a new IndexableSession object and
delegating more responsibility to the Indexable classes.
Fixes #2461
=> Refactor indexing

src/EventListener/IndexEntityChanges.php
The API for this changed in #2475 and this listener wasn't updated.
=> Correctly re-index course on change

src/Service/Index.php, src/Service/Search.php
Improves the way users are indexed so they respond to partial name
searches and matches as well as queries with a space in them.
=> Improve user search

config/dataimport/aamc_method.csv, config/services.yaml, config/swagger/definitions/Aamcmethod.yml, src/DataFixtures/ORM/LoadAamcMethodData.php, src/Entity/AamcMethod.php, src/Entity/AamcMethodInterface.php, src/Entity/DTO/AamcMethodDTO.php, src/Entity/Repository/AamcMethodRepository.php, src/Migrations/Version20190612212532.php, tests/DataLoader/AamcMethodData.php, tests/Endpoints/AamcMethodTest.php, tests/Entity/AamcMethodTest.php, tests/Fixture/LoadAamcMethodData.php
=> Adds active flag to AAMC Method and re-maps deprecated method

composer.lock, symfony.lock
| Production Changes                 | From    | To      | Compare                                                                       |
|------------------------------------|---------|---------|-------------------------------------------------------------------------------|
| aws/aws-sdk-php                    | 3.100.7 | 3.101.1 | https://github.com/aws/aws-sdk-php/compare/3.100.7...3.101.1                  |
| egulias/email-validator            | 2.1.8   | 2.1.9   | https://github.com/egulias/EmailValidator/compare/2.1.8...2.1.9               |
| symfony/asset                      | v4.3.1  | v4.3.2  | https://github.com/symfony/asset/compare/v4.3.1...v4.3.2                      |
| symfony/cache                      | v4.3.1  | v4.3.2  | …
=> Update Symfony to 4.3.2

config/packages/security.yaml, config/routes.yaml
Remove the experimental prefix and make search available for general
use.
=> Open search endpoint

composer.lock
| Production Changes | From   | To     | Compare                                                 |
|--------------------|--------|--------|---------------------------------------------------------|
| symfony/flex       | v1.3.0 | v1.4.1 | https://github.com/symfony/flex/compare/v1.3.0...v1.4.1 |
=> Update Symfony Flex

config/services.yaml, src/EventListener/TimestampEntityChanges.php, src/Service/Timestamper.php, src/Traits/TimestampableEntity.php, src/Traits/TimestampableEntityInterface.php, tests/Entity/MeshConceptTest.php, tests/Entity/MeshDescriptorTest.php, tests/Entity/MeshQualifierTest.php, tests/Entity/MeshTermTest.php, tests/Entity/SessionTest.php
fixes #2547 
third attempt at nailing this issue.
see https://github.com/ilios/ilios/pull/2548#issuecomment-504727553 and commit notes for the taken approach this time.
=> re-work of entity timestamping mechanism

src/Command/AddUserCommand.php, src/Entity/User.php, src/Migrations/Version20190711180817.php
=> increase length of user first/last-name.

src/Service/Index.php, src/Service/Search.php
By indexing curriculum as ngram we can get partial word matches we then
boost the score by looking for other complete word matches. Refactored
things into new methods to add a little bit of clarity.
Fixes #2565
=> Improve index and searching

src/Entity/Course.php, src/Entity/ProgramYear.php, src/Entity/Session.php
fixes #2571 
i'm taking the easy route here.
=> sort objectives by position, then id, by default.

src/Entity/CurriculumInventoryInstitution.php
=> aligns property length assertion with column length.

src/Service/CurriculumInventory/ReportRollover.php, tests/Endpoints/CurriculumInventoryReportTest.php, tests/Service/ReportRolloverTest.php
fixes #2586 
provided test coverage for the rollover service while at it.
=> calculate start/end date based on given year and hardwired month/day range.

config/services.yaml, src/Service/Search.php
We need this to filter and identify results in the search.
Refs ilios/frontend#4754
Includes an API bump so we can know this data is present in search results.
=> Add school to search output

src/Service/Index.php, src/Service/Search.php
This ensures that the full address and the domain end up in the index
as well as partial matches on smaller parts.
Refs #2639
=> Improve indexing of email address

src/EventListener/IndexEntityChanges.php, src/Service/Index.php, src/Service/Search.php
Re-index users when their authentication is updated and modify the index
to be partial match searchable to better match what users expect.
Fixes #2639
=> Improve user indexing

src/Service/CurriculumInventory/VerificationPreviewBuilder.php, tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php
just a follow up, so we won't have to deal with sorting objectives in the frontend.
=> sort data by markup-free objective title.

src/Controller/IcsController.php, tests/Controller/IcsControllerTest.php
=> indicate existence of lm's and pre-requisites in event description as applicable.

src/Entity/ProgramYearSteward.php, tests/Endpoints/ProgramYearStewardTest.php, tests/Entity/ProgramYearStewardTest.php
=> departments are optional for program year stewards.

config/packages/messenger.yaml, config/services.yaml, src/EventListener/IndexEntityChanges.php
Dispatch messages on this bus, but set them up to be received by the
default bus.
=> Use special bus to dispatch messages

src/Service/CourseRollover.php, tests/Service/CourseRolloverTest.php
=> rollover course admins.

tests/Classes/SessionUserTest.php
Fleshes out the test coverage on various roles-related methods in the session user class.
=> implements skipped tests.

config/services.yaml
=> increments API version number.

config/swagger/definitions/CalendarEvent.yml, config/swagger/definitions/Schoolevent.yml, src/Classes/CalendarEvent.php, src/Classes/SchoolEvent.php, src/Classes/SessionUser.php, src/Classes/SessionUserInterface.php, src/Controller/SchooleventController.php, src/Controller/UsereventController.php, src/Entity/Manager/UserManager.php, src/Entity/Repository/SchoolRepository.php, src/Entity/Repository/UserRepository.php, src/RelationshipVoter/AbstractCalendarEvent.php, src/RelationshipVoter/SchoolEvent.php, src/RelationshipVoter/UserEvent.php, src/Traits/CalendarEventRepository.php, tests/Classes/SchoolEventTest.php, tests/Classes/SessionUserTest.php, tests/Endpoints/UsereventTest.php, tests/RelationshipVoter/SchoolEventTest.php, tests/RelationshipVoter/UserEventTest.php
=> More accurate read-access checks to calendar events

tests/Service/CourseRolloverTest.php
Offering test starts failing at the end of the year because something is fishy about calculating the weeks. This fix from the course section above fixes that issue.
=> Copy start of year date time test from course setStartDate

azure-pipelines.yml
Found out about this in the Symfony release notes https://symfony.com/blog/new-in-symfony-4-4-misc-improvements-part-2#improved-the-lint-twig-command
=> Add template linting to our tests

config/routes.yaml
This is a new feature in symfony 4.4, didn't see a reason not to take
advantage.
=> Use simplified redirect

src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php
=> update mesh importer for 2020

src/Command/ChangePasswordCommand.php, tests/Command/ChangePasswordCommandTest.php
=> fixes password changer command for legacy accounts

.github/workflows/coverage.yml
Removing a testing group here that I left in by mistake. Now coverage will run on everything.
=> Run coverage on all tests

src/Monitor/NoDefaultSecret.php, src/Monitor/PhpConfiguration.php
Everything else appears to be working as intended so this fixes #2727
=> Fixup some health checks

tests/AbstractEndpointTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/MeshConceptTest.php, tests/Endpoints/MeshDescriptorTest.php, tests/Endpoints/MeshQualifierTest.php, tests/Endpoints/MeshTermTest.php, tests/Endpoints/OfferingTest.php, tests/Endpoints/ReportTest.php, tests/Endpoints/SessionTest.php
=> fixes intermittent test failures related to time freezing.

.github/workflows/future-php.yml
Keep track of any issues in this version before we move to it.
=> Start testing against PHP 7.4

src/Controller/LearningMaterialController.php
=> guard against empty filehash uploads.

.github/workflows/ci.yml
=> explicitly start up mysql server.

src/Command/AddDirectoryUserCommand.php, src/Command/AddNewStudentsToSchoolCommand.php, src/Command/FindUserCommand.php, src/Command/SyncFormerStudentsCommand.php
fixes all of the ones that were still missing.
fixes #2838
fixes #2840
=> Adds return codes where missing.

composer.lock
| Production Changes                   | From     | To      | Compare                                                                              |
|--------------------------------------|----------|---------|--------------------------------------------------------------------------------------|
| aws/aws-sdk-php                      | 3.133.46 | 3.134.3 | [...](https://github.com/aws/aws-sdk-php/compare/3.133.46...3.134.3)                 |
| doctrine/annotations                 | v1.8.0   | 1.10.1  | [...](https://github.com/doctrine/annotations/compare/v1.8.0...1.10.1)               |
| laminas/laminas-zendframework-bridge | 1.0.2    | 1.0.3   | [...](https://github.com/laminas/laminas-zendframework-bridge/compare/1.0.2...1.0.3) |
=> Update Transitive Dependencies

src/Entity/Report.php, src/Entity/ReportInterface.php, tests/Entity/ReportTest.php
=> school in report is optional, treat it as such.

README.md, docker-compose.yml
This is a better tool than our own local development server as it
doesn't require maintaining a development only copy of our application,
is controlled by the local .env files, and is faster.
=> Prefer symfony server for developing ilios

src/Command/AddNewStudentsToSchoolCommand.php
=> always return a code.

.gitignore, Dockerfile, config/routes.yaml, public/.htaccess, src/Command/UpdateFrontendCommand.php, src/Controller/IcsController.php, src/Controller/IndexController.php, src/Service/CasAuthentication.php, src/Service/Filesystem.php, src/Service/SwaggerDocBuilder.php, tests/Command/UpdateFrontendCommandTest.php, tests/Controller/IndexControllerTest.php
Refs ilios/frontend#5299 where new statically compressed assets are now deployed. These can be served as is with the correct headers to improve performance and lower the resource cost on the server.
=> Improved Static Asset Loading

templates/index/webindex.html.twig
Tells the frontend to use the current version of the API.
=> Use v2 of the API

composer.json, composer.lock, config/bootstrap.php, config/services.yaml, src/Classes/Inflector.php, src/Command/GenerateEndpointTestCommand.php, src/Command/GenerateSwaggerApiPathYamlCommand.php, src/Service/EndpointResponseNamer.php, src/Service/InflectorFactory.php, tests/AbstractEndpointTest.php, tests/Classes/InflectorTest.php, tests/Endpoints/AamcPcrsTest.php
The new inflector API isn't static, but we still want to only define our
custom rules in one place so I've wrapped it in a static class of our
own.
=> Use new Doctrine Inflector

src/Controller/API/AcademicYears.php, src/Entity/DTO/CurriculumInventoryReportDTO.php, src/Entity/DTO/MeshConceptDTO.php, src/Entity/DTO/MeshQualifierDTO.php, src/Entity/DTO/MeshTermDTO.php, src/Entity/DTO/MeshTreeDTO.php, src/Entity/DTO/SessionV1DTO.php, src/Service/ApiResponseBuilder.php, tests/Endpoints/AcademicYearTest.php
I connected to all the endpoints with ember-data and pulled all of the data to confirm each was working as expected. Couple of small tweaks.
=> Some JSON API Fixes

src/Controller/API/Authentications.php, src/Controller/API/CurriculumInventoryExports.php, src/Controller/API/CurriculumInventoryReports.php, src/Controller/API/CurriculumInventorySequenceBlocks.php, src/Controller/API/LearningMaterials.php, src/Controller/API/Offerings.php, src/Controller/API/ProgramYears.php, src/Controller/API/ReadWriteController.php, src/Controller/API/Users.php
Adding this causes a redirect when the route is accessed without the /.
Since we don't use a slash in our API calls that's an extra step we
don't need.
=> Remove unneeded / in routes

.github/workflows/update-dependenies.yaml
Handle line breaks correctly in commit message and PR title and have the
commit be authored by the github bot.
=> Improve update action

src/Command/CheckS3PermissionsCommand.php
This try block needed a return value, used the new aliases from symonfy
to make it a bit more readable what is good and bad.
=> Return from command

docker-compose.yml, docker/elasticsearch-dev/Dockerfile, src/Classes/ElasticSearchBase.php, src/Service/Index/Curriculum.php, src/Service/Index/LearningMaterials.php, src/Service/Index/Mesh.php, src/Service/Index/Users.php, tests/Service/Index/CurriculumTest.php, tests/Service/Index/UsersTest.php
Updated our containers and configuration and then removed the `_doc` type from all indexes as type is no longer supported by deffault in 7.x.
=> Update to ElasticSearch 7.x

composer.json, composer.lock
PHPStorm is nagging, and righteously so.
=> explicitly state dependency on PDO extension.

src/Controller/API/Offerings.php, tests/Endpoints/OfferingTest.php
When an offering is saved or modified a change alert should be created, these were being built, but since the manager wasn't being flushed they were not persisted to the database. The testing infrastructure for this was mostly neutered when the API endpoint for alerts was removed in #1968, but by querying the database directly we can once again test to ensure these alerts are working.
For PATH JSON:API requests a new method was added to the Offerings Controller to handle saving these alerts.
Fixes #2949
=> Create Change Alerts When Offerings Are Modified

docs/ilios_quick_setup_for_admins.md
quickstart file to explain setting up a dev instance
=> created quickstart file for admins/devs

src/Classes/CalendarEvent.php, src/Entity/Repository/SchoolRepository.php, src/Entity/Repository/UserRepository.php, src/Traits/CalendarEventRepository.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php
Not much good adding this to offerings if it isn't exposed to users on the dashboard.
Refs #2953
=> Add URL to events

src/Service/CurriculumInventory/Export/XmlPrinter.php, tests/Service/CurriculumInventory/Export/XmlPrinterTest.php
=> Adjustments to CI XML Printer for PHP strict mode

composer.json, composer.lock
this resolves the world's most pressing issue.
=> lists simplexml php extension as dev requirement.

tests/Command/Index/CreateCommandTest.php, tests/Command/Index/DropCommandTest.php, tests/Controller/SearchControllerTest.php, tests/Service/Index/CurriculumTest.php, tests/Service/Index/MeshTest.php, tests/Service/Index/UsersTest.php
=> invokes phpunit assertion methods non-statically.

config/swagger/definitions/Programyear.yml, config/swagger/definitions/School.yml, src/Controller/API/Schools.php, src/Entity/DTO/SchoolDTO.php, src/Entity/DTO/SchoolV1DTO.php, src/Entity/Manager/SchoolManager.php, src/Entity/Repository/SchoolRepository.php, src/Entity/School.php, src/RelationshipVoter/GreenlightViewDTOVoter.php, tests/Endpoints/CurriculumInventoryInstitutionTest.php, tests/Endpoints/SchoolTest.php, tests/Endpoints/SchoolV1Test.php, tests/RelationshipVoter/GreenlightViewDtoVoterTest.php
follow-up item to #2980
we must also prevent exposing stewards from schools endpoint in API v3.
=> Do no expose stewards from school

config/swagger/definitions/Program.yml, config/swagger/definitions/Programyear.yml, src/Controller/API/Programs.php, src/Entity/DTO/ProgramDTO.php, src/Entity/DTO/ProgramV1DTO.php, src/Entity/DTO/ProgramYearDTO.php, src/Entity/Manager/ProgramManager.php, src/Entity/Program.php, src/Entity/Repository/ProgramRepository.php, src/RelationshipVoter/GreenlightViewDTOVoter.php, tests/Endpoints/CohortTest.php, tests/Endpoints/ProgramTest.php, tests/Endpoints/ProgramV1Test.php, tests/Endpoints/ProgramYearTest.php, tests/Endpoints/ProgramYearV1Test.php, tests/RelationshipVoter/GreenlightViewDtoVoterTest.php
=> removes deprecated publication-workflow related properties from programs and program-years

src/Denormalizer/EntityDenormalizer.php, tests/Endpoints/CourseLearningMaterialTest.php, tests/Endpoints/SessionLearningMaterialTest.php, tests/Endpoints/SessionTest.php
=> do not purify null input.

templates/index/webindex.html.twig
Tells the frontend what the base URL is to connect to for the API.
=> Use v3 of the API

src/Command/CleanupStringsCommand.php, tests/Command/CleanupStringsCommandTest.php
=> zero-index offset.

src/Service/CurriculumInventory/Export/XmlPrinter.php, tests/Service/CurriculumInventory/Export/XmlPrinterTest.php
absolutely dreadful, but at least this covers the happy path now.
=> Improves test coverage for Curriculum Inventory Report XML printer.

src/Command/CleanupStringsCommand.php, src/Entity/Manager/LearningMaterialManager.php, tests/Command/CleanupStringsCommandTest.php
=> Adds command for cleanup up learning material links

config/swagger/definitions/Userevent.yml
=> corrects property declarations for user event.

Dockerfile
Remove opcache production instructions from the correct PHP ini file.
=> Fix fpm-dev container

.github/workflows/deploy-latest.yml
I'm more comfortable with the security implications of doing this deploy
using a verified action from docker.
=> Use the verified docker action to deploy

src/Entity/Repository/UserRepository.php
refs https://github.com/ilios/common/issues/1553
=> set user id when creating post-requisite user event from ilm.

.github/workflows/deploy-tag.yml
When we release this will send 3 tags each to github and docker for our
containers. For example for tag v3.15.2 -  v3 v3.15 and v3.15.2 will all get sent to the registry.
=> Build and deploy tagged containers

.github/workflows/deploy-tag.yml
runs-on is required, also added a name for clarity in the output.
=> Add missing attrs to deploy tags action

src/Entity/CourseObjective.php, src/Entity/SessionObjective.php, src/Migrations/Version20200814223927.php
=> Adds deleting cascades to x-objective join tables.

config/swagger/definitions/Authentication.yml, config/swagger/definitions/Curriculuminventoryreport.yml, config/swagger/definitions/Curriculuminventorysequenceblock.yml, config/swagger/definitions/Learnergroup.yml, config/swagger/definitions/Learningmaterial.yml, config/swagger/definitions/School.yml
=> realigned API docs with code

tests/Service/CourseRolloverTest.php
this replaces the hokey week-of-the-year calculations that never really worked around the year edges.
=> uses date interval functions to calculate expected future end/start week

src/Controller/API/AcademicYears.php, src/Controller/DirectoryController.php, src/Controller/ErrorController.php, src/Service/ApiRequestParser.php, src/Service/ApiResponseBuilder.php, src/Service/CasAuthentication.php, tests/DataLoader/PendingUserUpdateData.php
=> fixes deprecation warnings by using all() over get().

config/swagger/definitions/Learnergroup.yml, src/Entity/DTO/LearnerGroupDTO.php, src/Entity/LearnerGroup.php, src/Entity/LearnerGroupInterface.php, src/Entity/Repository/LearnerGroupRepository.php, src/Migrations/Version20200902230650.php, tests/DataLoader/LearnerGroupData.php, tests/Endpoints/LearnerGroupTest.php, tests/Entity/LearnerGroupTest.php, tests/Fixture/LoadLearnerGroupData.php
Adds `url` and `needsAccommodation` attributes to learner group entity.
fixes https://github.com/ilios/ilios/issues/3083
fixes https://github.com/ilios/ilios/issues/3082
will need API bump.
=> New learnergroup fields

config/services.yaml
=> bumps API version to 3.1

src/Controller/API/CurriculumInventoryExports.php, src/Entity/DTO/CurriculumInventoryExportDTO.php, src/Entity/Repository/CurriculumInventoryExportRepository.php, tests/DataLoader/CurriculumInventoryExportData.php, tests/Endpoints/CurriculumInventoryExportTest.php
this allows us to correctly serialize the response payload when
finalizing CI reports.
fixes #3121
=> DTOifies CI report export.

src/Service/CurriculumInventory/Export/XmlPrinter.php
"fixes" #3125 
the report will still be invalid but at least it won't break on creation.
=> forces type-coersion to string on NULL value method ids.

migrations/Version20201001230658.php, src/Entity/CourseObjective.php, src/Entity/Objective.php, src/Entity/ProgramYearObjective.php, src/Entity/SessionObjective.php
fixes https://github.com/ilios/ilios/issues/3142
=> adds ability to delete objectives without having to delete links to mesh terms first

src/Command/CheckS3PermissionsCommand.php, src/Command/CreateUserTokenCommand.php, src/Command/CrossingGuardCommand.php, src/Command/FixLearningMaterialMimeTypesCommand.php, src/Command/Index/UpdateCommand.php, src/Command/InvalidateUserTokenCommand.php, src/Command/MigrateIlios2LearningMaterialsCommand.php, src/Command/SyncUserCommand.php, src/Command/ValidateLearningMaterialPathsCommand.php, src/Controller/AuthController.php, src/Entity/DTO/CurriculumInventoryAcademicLevelDTO.php, src/Entity/DTO/IlmSessionDTO.php, src/Entity/Repository/InstructorGroupRepository.php, src/EventListener/LogEntityChanges.php, src/Service/AuthenticationFactory.php, src/Service/JsonWebTokenManager.php, src/Service/LdapManager.php, src/Service/LoggerQueue.php, src/Service/TemporaryFileSystem.php, src/Traits/AuthenticationService.php, tests/Controller/SwaggerYamlDocsControllerTest.php, tests/Controller/UploadControllerTest.php, tests/DataLoader/ReportData.php, tests/Fixture/LoadAlertChangeTypeData.php, tests/Fixture/LoadCurriculumInventoryInstitutionData.php, tests/Fixture/LoadProgramYearStewardData.php, tests/Service/IliosFileSystemTest.php, tests/Service/TemporaryFileSystemTest.php
New version of PHPCS is more strict about these empty lines.
=> Fix some whitespace code style issues

src/Entity/Repository/SessionLearningMaterialRepository.php, src/Entity/Repository/SessionObjectiveRepository.php, tests/Endpoints/SessionLearningMaterialTest.php, tests/Endpoints/SessionObjectiveTest.php
Filtering by school was requested for both `sessionlearningmaterials` and `sessionobjectives`, added here.
=> Added needed school filters

migrations/Version20201117221343.php, src/Entity/Offering.php, src/Entity/OfferingInterface.php, tests/Endpoints/OfferingTest.php, tests/Entity/OfferingTest.php
=> makes offering room attribute nullable.

composer.json, composer.lock, symfony.lock
=> replaces dependency on abandoned faker lib with its maintained fork

composer.json, composer.lock, symfony.lock
This package has been abandoned and we weren't actually using it
anymore. Either of these seems like reasonable reasons to remove it :)
=> Remove Easy Log Handler

Dockerfile, src/Controller/IndexController.php
The default custom.css file in this directory is required to be present
so it can be served without checking to see if it exists. I also cleaned
up IndexController a bit while troubleshooting this issue.
Fixes #3200
=> Copy theme-overrides into docker container

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/update-dependencies.yaml
Updating to the latest actions for better performance and various
improvements.
=> Update action versions

src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php
fixes #3205 
_do not merge until the 2021 dataset has been published_
=> adds support for 2021 MeSH dataset to importer.

phpstan.neon.dist, src/Classes/UserMaterial.php, src/Command/SendChangeAlertsCommand.php, src/Command/UpdateFrontendCommand.php, src/Controller/IcsController.php, src/Entity/CourseObjectiveInterface.php, src/Entity/SessionObjectiveInterface.php, src/Repository/CourseRepository.php, src/Service/ChangeAlertHandler.php, src/Service/CourseRollover.php, tests/AbstractEndpointTest.php, tests/Classes/UserMaterialTest.php, tests/Command/AddDirectoryUserCommandTest.php, tests/Command/AddNewStudentsToSchoolCommandTest.php, tests/Command/AddRootUserCommandTest.php, tests/Command/AddUserCommandTest.php, tests/Command/CreateUserTokenCommandTest.php, tests/Command/InstallFirstUserCommandTest.php, tests/Command/InvalidateUserTokenCommandTest.php, tests/Command/MigrateIlios2LearningMaterialsCommandTest.php, tests/Command/RemoveRootUserCommandTest.php, tests/Command/RolloverCourseCommandTest.php, tests/Command/RolloverCurriculumInventoryReportCommandTest.php, tests/Command/SendTeachingRemindersCommandTest.php, tests/Command/SyncUserCommandTest.php, tests/Service/ChangeAlertHandlerTest.php, tests/Service/CourseRolloverTest.php, tests/Traits/JsonControllerTest.php, tests/phpstan.neon.dist
Bumped from 0 to 1 and then cleaned up all the issues, many of which were very real and needed to be addressed.
=> Level Up PHPStan to 1

migrations/Version20210126001058.php, src/Entity/Session.php
=> set prerequisite to NULL on delete.

.github/workflows/ci.yml, composer.json, composer.lock, config/packages/monitor.yaml, config/packages/security_checker.yaml, symfony.lock
see https://twitter.com/fabpot/status/1349980977397964800
=> Replace security checker

src/Repository/SchoolRepository.php, src/Repository/UserRepository.php, src/Traits/CalendarEventRepository.php
There is no userId property on a calendar event, this only exists on the
UserEvent class.
=> Don't overload CalendarEvent with user data

src/Repository/AuditLogRepository.php
fixes https://github.com/ilios/ilios/issues/3256
=> rm obsolete method.

src/Service/LdapManager.php
fixes https://github.com/ilios/ilios/issues/3302
=> lazy load LDAP connection.

config/services.yaml, migrations/Version20210204234902.php, src/Classes/AcademicYear.php, src/Controller/API/AcademicYears.php, src/Service/AcademicYearFactory.php, src/Service/Config.php, tests/Classes/AcademicYearTest.php, tests/Service/AcademicYearFactoryTest.php
=> appplication configuration for academic year boundaries

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/future-php.yml, .github/workflows/update-dependencies.yaml
As we prepare to make PHP8 our minimum supported version we need to
start testing it in CI.
=> Start officially testing PHP 8

.env, .env.dev, .github/workflows/ci.yml, Dockerfile, docker-compose.yml, docker/docker-compose-everything.yml, docs/env_vars_and_config.md, docs/install.md, docs/update.md
As AWS Aurora now supports this version we can bump our defaults as
well.
=> Bump our default MySQL version to 5.7

composer.json, composer.lock, src/Controller/IcsController.php, tests/Controller/IcsControllerTest.php
=> downgrade ics libary to last known good version.

config/packages/dev/monolog.yaml, config/packages/prod/deprecations.yaml, config/packages/prod/monolog.yaml, docker/monolog.yaml, symfony.lock
see https://symfony.com/blog/logging-in-symfony-and-the-cloud
=> updates symfony recipe for monolog bundle.

tests/DataFixtures/ORM/LoadCompetencyAamcPcrsDataTest.php
=> Fix class name

src/Controller/API/Authentications.php, src/Controller/API/LearningMaterials.php, src/DataFixtures/ORM/AbstractFixture.php, src/EventListener/LogEntityChanges.php, src/Normalizer/FactoryNormalizer.php, src/Security/JsonWebTokenAuthenticator.php, src/Service/ApiRequestParser.php, src/Service/EntityMetadata.php, src/Service/Index/Curriculum.php, src/Service/Index/LearningMaterials.php, src/Service/Index/Mesh.php, src/Service/Index/Users.php, src/Service/LearningMaterialDecoratorFactory.php, src/Service/SessionUserProvider.php, src/Traits/ManagerRepository.php, tests/Endpoints/AuthenticationTest.php, tests/Endpoints/OfferingTest.php, tests/Entity/EntityBase.php, tests/PutEndpointTestable.php, tests/ReadWriteEndpointTest.php
This is faster and more idiomatic in recent PHP versions.
=> Replace get_class with ::class

config/services.yaml, src/EventListener/SentryCaptureListener.php
Adds more data to our sentry events so we can spot performance issues.
=> Add sentry performance monitoring

.github/workflows/deploy-latest.yml
This is causing some issues, while working them out I'm going to disable
this for now.
=> Temporarily stop publishing to Github Registry

config/services.yaml, src/Command/RolloverCurriculumInventoryReportCommand.php, src/Controller/API/CurriculumInventoryReports.php, src/Service/CurriculumInventory/ReportRollover.php, tests/Command/RolloverCurriculumInventoryReportCommandTest.php, tests/Endpoints/CurriculumInventoryReportTest.php, tests/Service/ReportRolloverTest.php
refs https://github.com/ilios/frontend/issues/6157
=> opens up ci report rollover api endpoint to accept program year as input.

symfony.lock
no further changes except for the referenced hash.
=> updates recipe for symfony/validator.

symfony.lock, templates/base.html.twig
of note is the replacement of the base twig template. i don't think it is of any consequence for us, so i went with the new one that the recipe is pushing.
=> updates twig recipe.

symfony.lock
nothing here for us but to update the symfony lock file.
=> updates recipe for symfony/routing bundle.

symfony.lock
no changes other than reference hash bump required.
=> updates recipe for symfony/monolog bundle.

symfony.lock
no further changes required for this.
=> updates recipe for symfony/lock bundle.

symfony.lock
=> updates mailer recipe.

symfony.lock
=> updates recipe for symfony/apache-pack bundle.

symfony.lock
no other changes were required.
=> updates recipe for symfony/framework-bundle bundle.

symfony.lock
no other changes were required here.
=> updates recipe for htmlpurifier bundle.

symfony.lock
refs https://github.com/ilios/ilios/pull/3605.
=> updates recipe for phpunit/phpunit bundle.

symfony.lock
=> updates recipe for doctrine/doctrine-bundle bundle.

symfony.lock
no further changes required here.
=> updates recipe for liip/monitor-bundle bundle.

config/packages/security.yaml, src/Security/JsonWebTokenAuthenticator.php
=> Replace guard authenticator

.env, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/future-php.yml, Dockerfile, config/packages/messenger.yaml, symfony.lock
this moves the transports config value into an ENV variable,
which realigns Ilios with the recipe defaults.
=> updates messenger recipe.

.github/workflows/ci.yml
This isn't required anymore (probably, but have to try it in a possibly embarrassing PR to find out)
=> Remove unneeded passed env

src/Controller/AuthController.php, tests/Controller/AuthControllerTest.php
The symfony firewall has changed slightly and we need to be careful now
that we may have received a null token if a user is not authenticated.
Fixes #3651
=> Handle unauthenticated token correctly

src/Controller/AuthController.php, src/Service/AuthenticationInterface.php, src/Service/CasAuthentication.php, src/Service/FormAuthentication.php, src/Service/LdapAuthentication.php, src/Service/ShibbolethAuthentication.php
I changed the controller without updating each Auth provider, this
aligns them again.
=> Align return types for authentication

.github/workflows/create_release.yaml, .github/workflows/tag_version.yaml
Will allow our bot to do tagging and if manually tagged will create the
release notes and publish them.
=> Add Release Automation

.github/workflows/deploy-latest.yml
This alows us to build the arm platform on Github actions.
=> Add an emulator to build with

.github/workflows/deploy-latest.yml
This doesn't work now and it's difficult to debug without a system to
try it on. Will wait for a new MBP and try this again.
=> Revert multi-platform builds

.github/workflows/ci.yml
This command changed at some point, this is how github now recommends we
start this service.
=> Start MySQL in CI correctly

tests/AbstractEndpointTest.php
Otherwise it's hard from the CI output to know what to check.
=> When test fails show more details

composer.json, composer.lock, config/services.yaml, src/Kernel.php, symfony.lock
Last attempt at this was botched a bit, this is the real deal.
| Production Changes           | From     | To       | Compare                                                                         |
|------------------------------|----------|----------|---------------------------------------------------------------------------------|
| aws/aws-sdk-php              | 3.208.1  | 3.208.3  | [...](https://github.com/aws/aws-sdk-php/compare/3.208.1...3.208.3)             |
| composer/xdebug-handler      | 2.0.2    | 2.0.3    | [...](https://github.com/composer/xdebug-handler/compare/2.0.2...2.0.3)         |
| guzzlehttp/guzzle            | 7.4.0    | 7.4.1    | [...](https://github.com/guzzle/guzzle/compare/7.4.0...7.4.1)                   |
| jaybizzle/crawler-detect     | v1.2.109 | …
=> Update to Symfony 5.4 (for real)

src/Entity/Authentication.php, src/Entity/AuthenticationInterface.php, tests/Entity/AuthenticationTest.php
=> Fix return type on Authentication:passwordHash

src/Entity/Authentication.php, src/Entity/AuthenticationInterface.php, tests/Entity/AuthenticationTest.php
Some more nullables here which needed fixing.
Fixes #3803
=> Fix authentication return types

src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php
=> updates mesh importer to support and default to 2022 data.

docs/ilios_quick_setup_for_admins.md
composer vs docker compose.... the final showdown!
=> Fix documentation typo

src/Entity/User.php, src/Entity/UserInterface.php
=> allow phone getter to return null.

src/Entity/User.php, src/Entity/UserInterface.php
=> allow campus id getter to return null.

symfony.lock
turn out there was no code/config changes for us to apply.
=> updates recipe for symfony framework bundle.

src/Command/UpdateFrontendCommand.php
Since our preview deploys aren't commit based we have to do a bit of
extra work to ensure we're using the most recent version.
=> Update existing frontend versions when reloading

.github/workflows/ci.yml
This is a newer and more performant docker build environment.
=> Use buildkit with CI

.env, .env.dev, .github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml, Dockerfile, docker-compose.demo.yml, docker-compose.override.yml, docs/env_vars_and_config.md, docs/install.md, docs/update.md
This will add support for the new Apple Silicon CPUs
=> Build multiplatform images

Dockerfile
This is recommended by docker to make errors clearer and to ensure a
good exit code if one of the steps fails.
=> Use set in multi-step RUN jobs

.github/workflows/ci.yml
This should allow us to diagnose issues running a specific container.
=> Output Docker Logs When a Test Fails

.github/workflows/deploy-latest.yml, Dockerfile
Our version library doesn't like dev, it needs some digits first.
=> Change deploy latest tagged version

composer.json, composer.lock, config/routes.yaml, config/routes/annotations.yaml, src/Classes/SessionUser.php, src/Controller/AuthController.php, src/Controller/ErrorController.php, src/Entity/AamcMethod.php, src/EventSubscriber/RedirectInsecureConnections.php, src/Security/JsonWebTokenAuthenticator.php, src/Service/CasAuthentication.php, src/Service/SessionUserProvider.php, src/Service/ShibbolethAuthentication.php, symfony.lock
Fixes #4000 
| Production Changes                 | From   | To      | Compare                                                                              |
|------------------------------------|--------|---------|--------------------------------------------------------------------------------------|
| psr/cache                          | 1.0.1  | 3.0.0   | [...](https://github.com/php-fig/cache/compare/1.0.1...3.0.0)                        |
| psr/container                      | 1.1.2  | 2.0.2   | [...](https://github.com/php-fig/container/compare/1.1.2...2.0.2)                    |
| psr/link                           | 1.1.1  | 2.0.1   | [...](https://github.com/php-fig/link/compare/1.1.1...2.0.1)                         |
| symfony/amazon-mailer              | v5.4.7 | v6.0.7  | …
=> Upgrade to Symfony 6.0

src/Normalizer/FactoryNormalizer.php, src/RelationshipVoter/Authentication.php, src/RelationshipVoter/Cohort.php, src/RelationshipVoter/Competency.php, src/RelationshipVoter/Course.php, src/RelationshipVoter/CourseLearningMaterial.php, src/RelationshipVoter/CurriculumInventoryInstitution.php, src/RelationshipVoter/CurriculumInventoryReport.php, src/RelationshipVoter/IlmSession.php, src/RelationshipVoter/IngestionException.php, src/RelationshipVoter/InstructorGroup.php, src/RelationshipVoter/LearnerGroup.php, src/RelationshipVoter/LearningMaterial.php, src/RelationshipVoter/Offering.php, src/RelationshipVoter/PendingUserUpdate.php, src/RelationshipVoter/Program.php, src/RelationshipVoter/ProgramYear.php, src/RelationshipVoter/Report.php, src/RelationshipVoter/School.php, src/RelationshipVoter/SchoolConfig.php, src/RelationshipVoter/Session.php, src/RelationshipVoter/SessionLearningMaterial.php, src/RelationshipVoter/SessionType.php, src/RelationshipVoter/Term.php, src/RelationshipVoter/User.php, src/RelationshipVoter/Vocabulary.php, src/Service/AuthenticationFactory.php, src/Service/CasManager.php, src/Service/CurriculumInventory/Export/XmlPrinter.php, tests/Entity/EntityBase.php
This new control flow in PHP 8 is better in comparing values and,
especially when returning the value, way easier to read. I codemoded
these using rector and it seems to have done a nice job.
=> Convert switch to match

phpstan.neon.dist, src/Entity/DTO/LearningMaterialDTO.php, src/Entity/IlmSession.php, src/Entity/LearningMaterial.php, src/Entity/LearningMaterialInterface.php, src/Entity/MeshQualifier.php, src/Entity/Offering.php, src/Entity/School.php, src/Entity/Session.php, src/Service/GraphQL/DateTimeType.php
Couple of things to cleanup which probably weren't bugs this time, but would become bugs once we switched from annotating types to enforcing them.
=> Up Phpstan to level 3

.github/workflows/deploy-tag.yml
While it may be worth re-adding this in the future it has proven to be
difficult to maintain with no real gain. Removing it.
=> Stop building github containers

src/Service/CasManager.php, src/Service/Config.php, tests/Service/ConfigTest.php
When we get this value we expect it to be an int, so just like booleans
I've added a cast here to ensure that.
=> Cast CAS version to int in Config

src/Command/CreateUserTokenCommand.php, src/Controller/AuthController.php, src/Security/JsonWebTokenAuthenticator.php, src/Service/JsonWebTokenManager.php, tests/Command/CreateUserTokenCommandTest.php, tests/Controller/AuthControllerTest.php, tests/Traits/JsonControllerTest.php
We're going to want to shut this option down and adding these details to
the token is the start of that process.
=> Augment JWT with refresh details

src/Traits/ManagerRepository.php
By dropping back to SQL here we can query the join table directly for
manyToMany relationships on DTOs where we only want to get
the ID and don't need anything else. This is a significant performance
boost especially in cases where the DTO has a lot of related things
(like terms which can be connected to courses, sessions, objectives,
etc).
When loading a single course and includes such as ABC at UCSF we get a [23% performance gain](https://blackfire.io/profiles/compare/6bd82901-927d-4939-925d-6811158f3ba0/graph) which is great on it's own, but loading all the terms for a school results in a fairly amazing [97% improvement](https://blackfire.io/profiles/compare/cfca8234-7bf6-48cb-9e62-f3f9fe026a4d/graph) in loading time reducing the time from 48 down to 1.5 seconds!
All this together …
=> Improve Performance of DTO Relationship Loading

.github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml
Lots of releases to cover a bump of node, I think they all need to
happen together otherwise we get some test failures.
=> Bump all docker actions

tests/Controller/AuthControllerTest.php, tests/Controller/CurriculumInventoryDownloadControllerTest.php, tests/Endpoints/CurrentSessionTest.php
=> rm unsetting of non-existing class member.

tests/Controller/UploadControllerTest.php
this one was failing when run in isolation, b/c the user fixture wasn't loaded.
=> load user fixture before running tests.

tests/Command/ImportDefaultDataCommandTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/ProgramYearTest.php, tests/Entity/CourseTest.php, tests/Entity/ProgramYearObjectiveTest.php, tests/RelationshipVoter/UserDTOVoterTest.php, tests/Service/DefaultDataImporterTest.php, tests/Service/DefaultDataLoaderTest.php
=> corrects coverage annotations.

.gitpod.Dockerfile, .gitpod.yml
This *almost* works. Well, it works if you do one more manual step. But I want to get it working without that. Might be a race condition on the whole `bin/console cache:warmup` thing?
=> feat: add Gitpod files

config/dataimport/application_config.csv, migrations/Version20220610080000.php, src/Controller/ConfigController.php, src/Service/Config.php, tests/Controller/ConfigControllerTest.php
This was deprecated and scheduled to be removed in v3.100.0
=> Drop Google Analytics Support

src/Command/CleanupStringsCommand.php
saw that by looking for something else. 
fly-by fix.
=> fixes typo in function name.

src/Traits/ManagerRepository.php
=> unbreak get-all API requests with sort order

src/EventListener/ClearCachedDto.php, src/EventListener/LogEntityChanges.php, src/Repository/MeshDescriptorRepository.php
fixes #4251 
found a fixed a DBAL deprecation while at it.
=> Resolve doctrine orm deprecations

templates/email/teachingreminder.text.twig, tests/Command/SendTeachingRemindersCommandTest.php
=> adds virtual learning link to teaching reminders.

tests/Classes/UserMaterialTest.php
saw this while working on https://github.com/ilios/ilios/pull/4281
=> fixes copy/paste error in unit test.

src/Classes/UserMaterial.php, src/Service/UserMaterialFactory.php, src/Traits/CalendarEventRepository.php, tests/Classes/UserMaterialTest.php, tests/Endpoints/UsereventTest.php, tests/Endpoints/UsermaterialsTest.php
companion ticket to https://github.com/ilios/common/pull/3026
refs https://github.com/ilios/common/issues/3025
=> add course year and course external id to user material output.

symfony.lock
it's just the symfony lock file update this time.
=> updates doctrine-bundle recipe.

tests/Endpoints/CourseTest.php
Ensuring that included data is returned when authorized and not when requested by users without sufficient access.
=> Add sideload checks for graphql

.github/workflows/deploy-nightly.yml
The [build and tag](https://github.com/ilios/ilios/actions/workflows/deploy-nightly.yml) action has been failing for a bit due to a whitespace error in the config. I've fixed that issue and also added a slack notification for failures.
=> Fix Nightly Container Re-build Job

.github/workflows/infection.yml
infection tests are gluttonous in their memory consumption. galactus hungers, let's feed him.
=> double allocated memory once again.

.env, config/packages/doctrine.yaml, config/packages/sentry.yaml, public/.htaccess, symfony.lock
it's been a bit.
Please see commit messages for details.
=> Symfony recipes update

src/Entity/DTO/SessionDTO.php, src/Repository/SessionRepository.php, tests/AbstractEndpointTest.php, tests/Endpoints/SessionTest.php, tests/Traits/JsonControllerTest.php
We need this for reporting, we've been doing some magic to make it take a single session type, but let's just accept the pluralized form.
=> Filter Sessions by Session Type

src/Entity/DTO/LearningMaterialDTO.php, src/Repository/LearningMaterialRepository.php, tests/Endpoints/LearningMaterialTest.php
This is useful in reporting (and maybe other stuff, I dunno).
=> Add schools filter to learning materials endpoint

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/update-dependencies.yaml, docs/ilios_php_version_policy.md
We're already testing in 8.2, a few places we're still using 8.1 and I've changed those as well as indicating our compatibility with both 8.1 and 8.2.
=> Align with latest PHP 8.2

src/Controller/API/GraphQL.php, src/Entity/DTO/MeshDescriptorDTO.php, src/Repository/MeshDescriptorRepository.php, tests/Endpoints/MeshDescriptorTest.php
I had to re-structure the way we do joins in the repository so they would be shared amongst filters otherwise we hit a mysql limit. This filter set is SLOW, but that's a pre-existing problem with mesh and adding the schools filter doesn't seem to make it better or worse.
=> Filter Mesh Descriptor by School

.github/workflows/ci.yml, composer.json, composer.lock, config/packages/doctrine.yaml, config/packages/framework.yaml, config/routes.yaml, config/services.yaml, symfony.lock, tests/bootstrap.php
| Production Changes           | From    | To      | Compare                                                                            |
|------------------------------|---------|---------|------------------------------------------------------------------------------------|
| aws/aws-sdk-php              | 3.257.1 | 3.257.4 | [...](https://github.com/aws/aws-sdk-php/compare/3.257.1...3.257.4)                |
| doctrine/event-manager       | 1.2.0   | 2.0.0   | [...](https://github.com/doctrine/event-manager/compare/1.2.0...2.0.0)             |
| doctrine/migrations          | 3.5.3   | 3.5.5   | [...](https://github.com/doctrine/migrations/compare/3.5.3...3.5.5)                |
| doctrine/persistence         | 3.1.2   | 3.1.3   | …
=> Upgrade to Symfony 6.2

.github/workflows/deploy-pr.yml
When a pull request is labeled as 'safe to deploy' we will create a special tag with the pr number and send it to the docker hub. This will allow us to deploy those containers into a test environment.
=> Deploy PR Previews to Docker Hub

.github/workflows/deploy-pr.yml
Makes it easier to track down the tag and see that the process happened.
=> Comment on PR when image is deployed

src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php
drop support for 2021 universe while at it.
=> Update MeSH importer to ingest 2023 universe by default.

src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php
the MeSH files got shuffled around once more. rewired.
=> replaces URL to MeSH 2022 XML file.

composer.json, composer.lock, migrations/Version20230626000000.php
Production Changes           | From    | To      | Compare                                                                         |
|------------------------------|---------|---------|---------------------------------------------------------------------------------|
| async-aws/core               | 1.18.1  | 1.19.0  | [...](https://github.com/async-aws/core/compare/1.18.1...1.19.0)                |
| aws/aws-sdk-php              | 3.271.7 | 3.273.7 | [...](https://github.com/aws/aws-sdk-php/compare/3.271.7...3.273.7)             |
| monolog/monolog              | 3.3.1   | 3.4.0   | [...](https://github.com/Seldaek/monolog/compare/3.3.1...3.4.0)                 |
| sentry/sentry                | 3.19.1  | 3.20.0  | [...](https://github.com/getsentry/sentry-php/compare/3.19.1...3.20.0) …
=> Update to Symfony 6.3

src/Entity/DTO/OfferingDTO.php, src/Repository/OfferingRepository.php, tests/Endpoints/OfferingTest.php
fixes https://github.com/ilios/ilios/issues/4839
=> adds filtering by schools to offerings endpoint.

Dockerfile
Bump our PHP version to 8.2 in our containers, we've been running tests against this for a while.
=> Update to PHP 8.2

config/services.yaml, src/Controller/API/Courses.php, src/Controller/API/Sessions.php, src/Repository/CourseRepository.php, src/Repository/SessionRepository.php, tests/Endpoints/AbstractEndpoint.php, tests/Endpoints/CourseTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/MeshDescriptorTest.php, tests/Endpoints/SessionTest.php, tests/Endpoints/UserTest.php, tests/QEndpointTrait.php
This will be needed for #4358. ~There is no compatible frontend yet to test this with.~
=> Add some 'q' query options to course and sessions endpoints

Dockerfile
add ILIOS_SEARCH_HOSTS env placeholder for consume-messages and consume-messages-dev
=> add ILIOS_SEARCH_HOSTS env placeholder for consume-messages and consume-messages-dev

Dockerfile
=> Revert "add ILIOS_SEARCH_HOSTS env placeholder for consume-messages and consume-messages-dev"

src/Command/AuditLogExportCommand.php, src/Command/SendTestEmailCommand.php, tests/Command/AuditLogExportCommandTest.php, tests/Command/SendTestEmailCommandTest.php, tests/Service/IliosFileSystemTest.php, tests/Service/TemporaryFileSystemTest.php
fixes https://github.com/ilios/ilios/issues/5039
=> eliminates "risky" test warnings

config/services.yaml, src/Encoder/JsonApiEncoder.php, src/EventListener/LogEntityChanges.php
prep-work for Symfony v7 upgrade.
refs #5141
=> rm deprecated ContainerAwareTrait

tests/Service/EntityMetadataTest.php
=> provides test coverage for EntityMetadata service.

tests/Service/EntityRepositoryLookupTest.php
fixes https://github.com/ilios/ilios/issues/5180
=> adds test coverage for the EntityRepositoryLookup service.

.github/workflows/ci.yml
see https://symfony.com/blog/new-in-symfony-5-1-misc-improvements-part-2#yaml-linter-command
```bash
stefan@nichtsnutz: ~/dev/projects/ilios on lint_yaml
$ find . -name "*.yaml" | egrep -v "(\.git/|var/|vendor/)"
./config/services.yaml
./config/services_test.yaml
./config/routes/framework.yaml
./config/routes/nelmio_api_doc.yaml
./config/routes/web_profiler.yaml
./config/routes/dev/twig.yaml
./config/packages/test/liip_test_fixtures.yaml
./config/packages/test/routing.yaml
./config/packages/exercise_html_purifier.yaml
./config/packages/monitor.yaml
./config/packages/framework.yaml
./config/packages/prod/framework.yaml
./config/packages/twig.yaml
./config/packages/nelmio_api_doc.yaml
./config/packages/doctrine.yaml
./config/packages/validator.yaml
./config/packages/monolog.yaml …
```
=> adds YAML linting to CI.

Dockerfile
This one is much nicer, and moar awesomer too.
=> Replace the demo DB download URL

config/services.yaml, src/Entity/DTO/CompetencyDTO.php, src/Entity/DTO/CourseDTO.php, src/Entity/DTO/InstructorGroupDTO.php, src/Entity/DTO/SessionDTO.php, src/Entity/DTO/SessionTypeDTO.php, src/Entity/DTO/TermDTO.php, src/Entity/DTO/UserDTO.php, src/Repository/CompetencyRepository.php, src/Repository/CourseRepository.php, src/Repository/InstructorGroupRepository.php, src/Repository/SessionRepository.php, src/Repository/SessionTypeRepository.php, src/Repository/TermRepository.php, src/Repository/UserRepository.php, tests/Endpoints/CompetencyTest.php, tests/Endpoints/CourseTest.php, tests/Endpoints/InstructorGroupTest.php, tests/Endpoints/SessionTest.php, tests/Endpoints/SessionTypeTest.php, tests/Endpoints/TermTest.php, tests/Endpoints/UserTest.php
These are used by reporting for these endpoints and filter the output by the academic year a course belongs to.
=> Add Academic Year Filters

src/DependencyInjection/PrefixSeedCompilerPass.php, tests/DependencyInjection/PrefixSeedCompilerPassTest.php
drop-in replacement for the removed, VERSION-file based process.
refs https://github.com/ilios/ilios/pull/5282#pullrequestreview-1910371330
=> adds ilios release version to cache prefix seed.

tests/DependencyInjection/PrefixSeedCompilerPassTest.php
the world's most impactful code change.
=> re-use local variable.

compose.yaml
see https://docs.docker.com/compose/compose-file/04-version-and-name/
=> removed version from compose.yaml, as it is now deprecated

.github/workflows/scan-repo.yml
Adding UCSF's code quality sonarqube tool to scan Ilios code. It will scan each pull request and compare it to merges in master (as configured in the project UI).
=> Add UCSF SonarQube scanner

src/Service/Directory.php, tests/Service/DirectoryTest.php
When performing a directory search look for the display name, configured first and last name, and preferred first and last name to ensure we find matches for these terms.
Refs #5453
=> Search directory for more values

src/Service/CasAuthentication.php
An old cookie in the old format, or something hokey may slip in here. We should not only validate the hash, but ensure the URL is valid at all. I've re-written the logic a bit to initially create the success response and then replace it if we have a valid redirect.
Fixes #5481
=> Ensure our cookie is valid

.github/workflows/ci.yml
15 minutes was too short, sometimes the composer install takes a while.
=> Slightly extend timeout

composer.json, composer.lock
| Production Changes              | From   | To     | Compare                                                                           |
|---------------------------------|--------|--------|-----------------------------------------------------------------------------------|
| symfony/amazon-mailer           | v7.0.7 | v7.1.0 | [...](https://github.com/symfony/amazon-mailer/compare/v7.0.7...v7.1.0)           |
| symfony/asset                   | v7.0.7 | v7.1.0 | [...](https://github.com/symfony/asset/compare/v7.0.7...v7.1.0)                   |
| symfony/cache                   | v7.0.7 | v7.1.0 | [...](https://github.com/symfony/cache/compare/v7.0.7...v7.1.0)                   |
| symfony/clock                   | v7.0.7 | v7.1.0 | …
=> Update Symfony to v7.1

.github/workflows/ci.yml, .markdownlint-cli2.jsonc, docs/ilios_quick_setup_for_admins.md
refs https://github.com/ilios/ilios/issues/5557
=> lint markdown files.

Dockerfile
Getting some warnings from github about this syntax, fixing it up.
=> Fix Syntax in Dockerfile

src/EventListener/IndexEntityChanges.php, tests/EventListener/IndexEntityChangesTest.php
=> adds some test coverage to the entity change listener.

src/Command/UpdateFrontendCommand.php, src/Security/JsonWebTokenAuthenticator.php, src/Service/Directory.php, src/Traits/ManagerRepository.php, tests/Endpoints/AbstractEndpoint.php
Using arrow functions is fun! In one case it allowed the removal of an interim variable which is also nice.
=> Apply ClosureToArrowFunctionRector

symfony.lock
no config changes necessary  here.
=> Updates recipe for doctrine/doctrine-bundle dependency to v2.13.

src/Command/SyncAllUsersCommand.php, src/Controller/API/UsereventController.php, src/Controller/AuthController.php, src/Repository/CourseRepository.php, src/Repository/SchoolRepository.php, src/Repository/SessionRepository.php, src/Repository/TermRepository.php, src/Repository/UserRepository.php, tests/Entity/EntityBase.php
I'm not sure I even knew PHP had this, but I like the syntax, it's nice.
=> Run TernaryToElvisRector

.github/workflows/ci.yml
Load and then delete each image as part of the test step, hopefully this
will save some needed space.
=> Better Image Loading Hygiene in Container Tests

symfony.lock
no changes, our config is already aligned with the recipe.
=> updates symfony/mailer recipe.

tests/Classes/IndexableCourseTest.php, tests/Classes/IndexableSessionTest.php
=> Adds test coverage for indexable classes

.github/workflows/ci.yml, .github/workflows/infection.yml, .github/workflows/update-dependencies.yaml
I think we're much better off using the minimum supported, and not the maximum available, php version for these tests. Changing the name of this variable makes that clearer.
=> Better Test Semantics

.env, .env.dev, composer.json, composer.lock, config/packages/framework.yaml, symfony.lock
Updated Symfony as well as the framework bundle's recipe:
The framework is now generating an APP_SECRET. We've overridden this
with ILIOS_SECRET so I kept that. Probably worth looking at to go back
to the default if the bundle is going to be messign with this.
Many options in our framework.yaml file are now the defaults in symfony
7 and were still in our config, I removed those.
The session handling config has been drastically simplified in the
recipe as well, we don't use the local session anyway, but now it aligns
with the provided recipe.
| Production Changes              | From   | To     | Compare                                                                           |
|---------------------------------|--------|--------|------------------------------------------------------------- …
=> Update to Symfony 7.2.0

.github/workflows/ci.yml
Also added a clarifying comment for the source of this info
=> Update SQ Token

src/Controller/ExceptionController.php, src/Service/UserMaterialFactory.php
=> Apply TernaryToNullCoalescingRector

src/Traits/ManagerRepository.php
=> corrects relationship mappings by using Doctrine 3.0 methods and objects instead of array attributes.

composer.json, composer.lock, config/services.yaml, migrations/Version20241214013522.php, src/Command/ImportMeshUniverseCommand.php, src/Entity/DTO/MeshConceptDTO.php, src/Entity/MeshConcept.php, src/Entity/MeshConceptInterface.php, src/Repository/MeshConceptRepository.php, src/Repository/MeshDescriptorRepository.php, symfony.lock, tests/Command/ImportMeshUniverseCommandTest.php, tests/DataLoader/MeshConceptData.php, tests/Endpoints/MeshConceptTest.php, tests/Entity/MeshConceptTest.php, tests/Fixture/LoadMeshConceptData.php
fixes #5890 
- drop support for 2023 MeSH
- add support for 2025 MeSH 
- drop MeshConcept::registryNumber data point
=> Add support for MeSH Universe 2025

.github/workflows/deploy-latest.yml, .github/workflows/deploy-nightly.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-tag.yml
This tag is once again tracking the latest release. Let's use it, if possible.
=> Switch back to Latest Tag

src/Repository/MeshDescriptorRepository.php
fixes #5985 
to test this, run `php bin/console ilios:import-mesh-universe`.
=> replace PDO parameter types with DBAL equivalents.

Dockerfile
Well tested and supported by Ilios, let's upgrade!
=> Update Containers to PHP 8.4

src/Repository/UserRepository.php
Joining the same tables twice makes this query super slow and very memory intensive. This breaks students viewing all events for a school as the permissions path goes through here and they have many links to offerings.
Splitting this into two parts makes it 98% faster and uses 99% less memory.
Fixes #6023
Profile: https://blackfire.io/profiles/compare/437b2919-e99c-43ce-9238-b07e759e5bdb/graph
=> Split Slow Query

tests/Service/Index/CurriculumTest.php
refs https://github.com/ilios/ilios/pull/6019#discussion_r2025723478
=> rm duplicate line.

config/services.yaml, config/services_test.yaml, src/Entity/MeshConcept.php, tests/Command/ImportMeshUniverseCommandAcceptanceTest.php, tests/Command/TestFiles/desc.xml, tests/Entity/MeshConceptTest.php
fixes https://github.com/ilios/ilios/issues/6084
fixes https://github.com/ilios/ilios/issues/5995
=> adds acceptance test for MeSH importer command, and resolves minor bug in MeSH concept entity

src/Command/Index/MaterialCommand.php, src/Command/Index/UpdateCommand.php, src/EventListener/IndexEntityChanges.php, src/Message/LearningMaterialIndexRequest.php, src/MessageHandler/LearningMaterialIndexHandler.php, src/MessageHandler/LearningMaterialTextExtractionHandler.php, src/Service/Index/LearningMaterials.php, src/Service/Index/Manager.php, tests/Command/Index/MaterialCommandTest.php, tests/EventListener/IndexEntityChangesTest.php, tests/Message/LearningMaterialIndexRequestTest.php, tests/MessageHandler/LearningMaterialIndexHandlerTest.php, tests/MessageHandler/LearningMaterialTextExtractionHandlerTest.php, tests/Service/Index/LearningMaterialsTest.php
Now that we're extracting learning materials we can use that extracted
text in the index without needing to process it as an attachment.
Materials with extracted text are now queued and indexed.
=> Index Learning Material Extractions

src/Classes/OpenSearchBase.php, src/Service/LearningMaterialTextExtractor.php
When we convert to text sometimes we get what looks like binary data in
the mix. Looking at the top ten largest materials in our extraction I've
tried to step through and remove as much of this as it seems safe to do.
=> Remove Junk from Learning Material Text

phpunit.dist.xml, symfony.lock
please see [ignoreSuppressionOfDeprecations](https://docs.phpunit.de/en/12.1/configuration.html#the-ignoresuppressionofdeprecations-attribute) for details on this mouthful of an attribute name.
=> updates recipe for phpunit/phpunit bundle to version 12.1.

config/packages/sentry.yaml, symfony.lock
a bit of churn along the comments in the yaml file that i'm accepting here at face value.
but nothing that changes active configuration.
=> updates recipe for sentry/sentry-symfony bundle to v5.2

src/Controller/API/ProgramYears.php, tests/Endpoints/ProgramYearTest.php
=> improves column headers in competency map spreadsheet.

composer.json, composer.lock
| Production Changes              | From    | To      | Compare                                                                           |
|---------------------------------|---------|---------|-----------------------------------------------------------------------------------|
| aws/aws-sdk-php                 | 3.344.0 | 3.344.3 | [...](https://github.com/aws/aws-sdk-php/compare/3.344.0...3.344.3)               |
| sentry/sentry                   | 4.11.1  | 4.13.0  | [...](https://github.com/getsentry/sentry-php/compare/4.11.1...4.13.0)            |
| symfony/amazon-mailer           | v7.2.0  | v7.3.0  | [...](https://github.com/symfony/amazon-mailer/compare/v7.2.0...v7.3.0)           |
| symfony/asset                   | v7.2.0  | v7.3.0  | …
=> Update to Symfony 7.3

src/Controller/API/Courses.php
=> handle course locking, unlocking, and archiving for PATCH requests

src/Classes/ServiceTokenUser.php, src/Classes/SessionUser.php, tests/Classes/SessionUserTest.php
=> resolves ::eraseCredentials-related deprecations.

.editorconfig, config/routes/framework.yaml, symfony.lock
this adds a .editorconfig file, and updates the routing config. 
for details, please see https://github.com/symfony/recipes/commits/main/symfony/framework-bundle/7.3
=> updates recipe from symfony/framework-bundle to v7.3.

config/packages/property_info.yaml, symfony.lock
this is a new recipe.
for details, please see https://github.com/symfony/recipes/commits/main/symfony/property-info/7.3
=> installs recipe for symfony/property_info bundle.

.github/workflows/ci.yml
=> rotates SQ token.

Dockerfile, docker/admin-entrypoint.sh
=> removed non-root users, enabled root ssh login
