sfi/src/Ilios/CoreBundle/Controller/UserController.php, sfi/src/Ilios/CoreBundle/Entity/Manager/UserManager.php, sfi/src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, sfi/src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, sfi/src/Ilios/CoreBundle/Entity/User.php
searchTerm is a space separated list of terms which will match
firstName, lastName, middleName, and email.  Each additional term will further constrain the results.
Are there any other fields we should be matching?
Fixes #738
=> Add the ability to find users by searchTerm

.gitignore
prevents accidental check-ins of customized phpunit configuration.
[skip-ci]
=> gitignore phpunit.xml

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
Offering entity updatedAt replaced lastUpdatedOn in
[546f3d5925532c4d620158ad09b57c05d710575b]
This fixes the issue with getting user events we had when deploying the new API code.
=> Fix user event query to match offering entity

tests/phpunit/Ilios/UserSync/Process/_datasets/student_process/post/user.xml, web/application/third_party/Ilios/UserSync/Process/StudentProcess.php
For some reason new student accounts are being deactivated on creation.  This is not correct. (read bone headed bug I created).
=> Stop deactivating new student accounts

provision/puppet/modules/profile/manifests/common/php.pp
PHPUnit gobbles up more than 1G now when running the full test suite.
[ci skip]
=> vagrant: increase PHP memory limit for CLI

app/AppKernel.php, composer.json, composer.lock
Only require the things we are using and use a stable build of all libraries.  This should improve production performance and deployability.
=> Clean up dependencies

src/Ilios/CoreBundle/Controller/LearningMaterialController.php, src/Ilios/CoreBundle/Controller/OfferingController.php, src/Ilios/CoreBundle/Controller/ReportController.php, src/Ilios/CoreBundle/Controller/SessionController.php, src/Ilios/CoreBundle/Controller/UserMadeReminderController.php, src/Ilios/CoreBundle/Entity/Offering.php
These aren’t super likely to be used, but if someone wants to send an
exact dateTime then we should handle it as opposed to sending a 500
error when it breaks.
Fixes #806
=> Handle dates correctly in the filters

app/Resources/DoctrineMigrations/Version20150826215733.php, src/Ilios/AuthenticationBundle/Voter/IlmSessionVoter.php, src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/Session.php, src/Ilios/CoreBundle/Form/Type/IlmSessionType.php, src/Ilios/CoreBundle/Tests/Controller/SessionControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/IlmSessionData.php, src/Ilios/CoreBundle/Tests/Entity/IlmSessionTest.php, src/Ilios/CoreBundle/Tests/Fixture/LoadIlmSessionData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadSessionData.php
Now the IlmSession owns the foreign key and is responsible for deleting
itself when the session is deleted.  Since session_id is required on
ILMSession it shouldn’t be possible to have an IlmSession without a
corresponding session relationship.
Fixes #925
Fixes #850
=> Improved schema for ILMSession

app/config/config.yml, app/config/security.yml, src/Ilios/AuthenticationBundle/Jwt/Listener.php, src/Ilios/AuthenticationBundle/Tests/Controller/AuthenticationControllerTest.php
I split the /auth sections into two separate firewalls so the JWT
firewall can deny any request that doesn’t work.  This allows us to
give much nicer error messages.
Also mapped the two common authentication exceptions into HTTP 401
error codes which seems like the best fit for this condition.
Fixes #904
=> Better authentication error handling

Vagrantfile, provision/puppet/modules/profile/manifests/common/php.pp
new values:
- 3GB max memory for VM
- 2GB max memory for PHP/CLI
- 1GB max memory for PHP/Apache
requires [reprovisioning](https://docs.vagrantup.com/v2/provisioning/index.html) of existing VMs.
```
vagrant up
vagrant provision
```
[ci skip]
=> upped VM and PHP memory limits

src/Ilios/AuthenticationBundle/Voter/UserVoter.php, src/Ilios/CoreBundle/Entity/Cohort.php, src/Ilios/CoreBundle/Entity/Manager/PermissionManager.php, src/Ilios/CoreBundle/Entity/Manager/PermissionManagerInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserInterface.php
This should make it possible for faculty in a school to view all
students with a secondary affiliation to that school.
I’m not sure about this solution, but it is the only one I could come up with.  I think the performance is made tenable by doctrine caching the repeated requests for the same cohort/program/school relationships.
I still need to handle the case of a secondary user school + a secondary learner cohort, but wanted to get some feedback on this path first.
Fixes #1004
=> Ensure read access to learners with a secondary school

.travis.yml, composer.json, composer.lock, src/Ilios/CoreBundle/Entity/Alert.php, src/Ilios/CoreBundle/Entity/Manager/MeshTermManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/MeshTreeManagerInterface.php, src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Form/DataTransformer/ManyRelatedTransformer.php, src/Ilios/CoreBundle/Form/DataTransformer/SingleRelatedTransformer.php, src/Ilios/CoreBundle/Tests/DataLoader/DataLoaderInterface.php
doctrine-fixtures-bundle was incorrectly in the require-dev section of our composer file.  This prevents it from being installed in a production environment and causes any production install to fail.   I fixed this issue and also modified our travis build to prevent it happening again.
=> Fix issue with production install

app/config/routing.yml, src/Ilios/CliBundle/Command/MigrateIlios2LearningMaterialsCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/MigrateIlios2LearningMaterialsCommandTest.php, src/Ilios/CoreBundle/Classes/IliosFileSystem.php, src/Ilios/CoreBundle/Controller/DownloadController.php, src/Ilios/CoreBundle/Controller/LearningMaterialController.php, src/Ilios/CoreBundle/Entity/LearningMaterial.php, src/Ilios/CoreBundle/Entity/LearningMaterialInterface.php, src/Ilios/CoreBundle/Entity/Manager/AbstractManager.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManagerInterface.php, src/Ilios/CoreBundle/Entity/Manager/ManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/AuthenticationRepository.php, src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Tests/Classes/IliosFileSystemTest.php, src/Ilios/CoreBundle/Tests/Controller/DownloadControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/LearningMaterialControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/LearningMaterialData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadLearningMaterialData.php
Tokens for learning materials are created automatically when new materials are created.  They are pretty random so we can rely on them to access files without any further authentication.
Old Ilios2 learning materials can be moved into v3 compatible locations using the ilios:setup:migrate-learning-materials command.  It takes the Ilios2 Source Root which is is where the relateive_file_path in the database expects to search for learning materials.
Materials can be downloaded at 
/lm/TOKEN.  Maybe this should be /download/lm/TOKEN, but the token is already 64 characters long so it might run into URL length  issues already.
Fixes #1019
=> Learning Material Downloads

app/config/config.yml, src/Ilios/CoreBundle/Controller/SchooleventsController.php, src/Ilios/CoreBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/IlmSessionInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Exception/InvalidInputWithSafeUserMessageException.php, src/Ilios/CoreBundle/Tests/Entity/UserTest.php
The main fix is that user instructedOfferings and instructedIlmSessions no longer return deleted offerings or sessions.  
I also added `InvalidInputWithSafeUserMessageException` which when thrown results in a 400 error and the display of the exception message to the API user.
=> Handle deleted offerings in the user API

.travis.yml, app/config/config.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis, src/Ilios/CliBundle/Tests/Command/SendTeachingRemindersCommandTest.php
As a result of #1035 and some mysterious internal symphony and doctrine voodoo all of our commands will fail when a database is not present including the command to create a database.  This happens when the UserEntityProvider we use for authentication attempts to detect the version of mysql we are running.  The best (only) way I could find to combat this is to explicit declare a mysql version in our configuration.
=> Fix commands and broken build

src/Ilios/CliBundle/Command/SendChangeAlertsCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/SendChangeAlertsCommandTest.php, src/Ilios/CoreBundle/Resources/views/Email/offeringchangealert.text.twig
```
vagrant@ilios:/vagrant$ bin/console ilios:messaging:send-change-alerts --help
Usage:
ilios:messaging:send-change-alerts [options]
Options:
--dry-run            Print out alerts instead of emailing them. Useful for testing/debugging purposes.
-h, --help               Display this help message
-q, --quiet              Do not output any message
-V, --version            Display this application version
--ansi               Force ANSI output
--no-ansi            Disable ANSI output
-n, --no-interaction     Do not ask any interactive question
-s, --shell              Launch the shell.
--process-isolation  Launch commands from shell as a separate process.
-e, --env=ENV            The Environment name. [default: "dev"]
--no-debug           Switches off debug mode.
-v|vv|vvv, --verbose …
```
=> change alerts command.

app/config/config.yml
This is an incorrect configuration value, it should be left off to
allow any host.
[ci skip]
=> Remove the hosts matcher from CORS options

src/Ilios/CoreBundle/Entity/Cohort.php, src/Ilios/CoreBundle/Entity/CohortInterface.php, src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/IlmSessionInterface.php, src/Ilios/CoreBundle/Entity/LearnerGroup.php, src/Ilios/CoreBundle/Entity/LearnerGroupInterface.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/CourseData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadCourseData.php
Expanded the list of schools related to a user so that the record of a course director for example is available to other directors not in the same primary school.
I added a single test which cover course director, we probably need more tests.
@stopfstedt this needs a security audit.  Am I punching too many holes?  Would it make more sense to just allow privileged users access to the whole user set?
=> More schools for a user

src/Ilios/CoreBundle/Entity/IlmSession.php, src/Ilios/CoreBundle/Entity/IlmSessionInterface.php, src/Ilios/CoreBundle/Tests/Entity/EntityBase.php, src/Ilios/CoreBundle/Tests/Entity/IlmSessionTest.php
Validate and display using floats instead of integers.
Fixes #1066
=> Allow fractional ILM hours

app/config/config.yml, src/Ilios/CoreBundle/Tests/Controller/ObjectiveControllerTest.php
=> Whitelisted <u> element in input sanitation rules.

src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php
This vastly simplifies the frontend response since we can just look at
the status and ignore the response code.  Plus I’m not sure that OK
isn’t actually the right response, the request was fulfilled after all.
Fixes ilios/frontend#1054
=> Return 200 when user does not have an account

src/Ilios/CoreBundle/Entity/School.php, src/Ilios/CoreBundle/Entity/SessionType.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Entity/UserRole.php, src/Ilios/CoreBundle/Form/Type/SchoolType.php, src/Ilios/CoreBundle/Form/Type/UserRoleType.php, src/Ilios/CoreBundle/Form/Type/UserType.php, src/Ilios/CoreBundle/Tests/Controller/SchoolControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/SessionTypeControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserRoleControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/SchoolData.php, src/Ilios/CoreBundle/Tests/DataLoader/SessionTypeData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserRoleData.php
This should speed up load speed on several pages.
Fixes #1100, #1101, #1102
=> Remove unnecessary API fields from highly trafficked endpoints

app/config/security.yml, src/Ilios/AuthenticationBundle/Controller/AuthenticationController.php, src/Ilios/AuthenticationBundle/Resources/config/routing.yml, src/Ilios/AuthenticationBundle/Service/AuthenticationInterface.php, src/Ilios/AuthenticationBundle/Service/FormAuthentication.php, src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php, src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php
This allows for special cases like shibboleth to log people out
correctly.
=> Add /auth/logout route

src/Ilios/CoreBundle/Entity/LearningMaterial.php
Per @saschaben's [request](https://github.com/ilios/frontend/issues/1013#issuecomment-153589485).
Refs ilios/frontend#1013.
=> lm::link needs to be a string, but not necessarily an URL.

app/config/security.yml, src/Ilios/WebBundle/Controller/ErrorController.php, src/Ilios/WebBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Tests/Controller/ErrorControllerTest.php
Authenticated users can post data here so we can keep track of any
errors encountered in the app.
Fixes #1063
=> Add /errors endpoint for capturing errors from frontend

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
Filter params which have always existed on course like id, year, etc…
can be passed as an array and should be handled in that way.
Fixes #1112
=> Handle course filter params as an array

src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
This allows us to quickly retrieve a set of all the courses that belong
to a user which should be faster than building it backwards on the fronted.
Fixes #1125
=> Add users as a filter on courses endpoint

app/Resources/DoctrineMigrations/Version20151118233516.php, src/Ilios/CoreBundle/Entity/Cohort.php
Cascade program year / cohort deletes.  This allows empty program years connected to empty cohorts to be deleted.
Fixes #1117
=> Allow program years to be removed

.travis.yml, app/Resources/DoctrineMigrations/Version20151125055054.php, composer.lock, src/Ilios/AuthenticationBundle/Voter/LearningMaterialVoter.php, src/Ilios/AuthenticationBundle/Voter/SchoolVoter.php
This should detect some security issues with our install to help us stay ahead of problems.  I put it in the same build as code style.  Does it belong somewhere else?
One vulnerability was detected so I updated libraries as well:
- symfony/symfony v2.7.6 to v2.7.7
- doctrine/orm v2.5.1 to v2.5.2
- symfony/monolog-bundle 2.8.1 to v2.8.2
- squizlabs/php_codesniffer 2.3.4 to 2.4.0
=> Add symphony security checker to travis build

src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/Tests/Controller/IndexControllerTest.php
This file which is always available at index.html is actually
dynamically tied to the latest fronted version tag.  This change
ensures that the browser will attempt to reload it at least once a
minute.
Fixes #1156
=> Cache index.html for 60 seconds only

src/Ilios/CoreBundle/Entity/LearnerGroup.php
Users, children, and instructor groups relationships needed the
protection we use on all many to many relationships.
Fixes #1167
=> Protect learner group related entities from double add

src/Ilios/CliBundle/Command/MigrateIlios2LearningMaterialsCommand.php, src/Ilios/CliBundle/Command/ValidateLearningMaterialPathsCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CliBundle/Tests/Command/MigrateIlios2LearningMaterialsCommandTest.php, src/Ilios/CliBundle/Tests/Command/ValidateLearningMaterialPathsCommandTest.php, src/Ilios/CoreBundle/Classes/IliosFileSystem.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManager.php, src/Ilios/CoreBundle/Entity/Manager/LearningMaterialManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/LearningMaterialRepository.php, src/Ilios/CoreBundle/Tests/Classes/IliosFileSystemTest.php
Migrate files in blocks and don’t die if they are missing.  This should let the command run many times to move a whole tree.
Also Added a command to validate learning materials in the DB
This is mainly useful after migrating to ensure that everything works, but I guess would be equally useful after any large file operation on the learning materials.
Refs #1168
=> Improved Learning Material Migration

src/Ilios/CoreBundle/Entity/Topic.php, src/Ilios/CoreBundle/Form/Type/TopicType.php, src/Ilios/CoreBundle/Tests/Controller/TopicControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php
The data isn’t needed in this direction and it makes loading topic very slow.
Fixes #1203
=> Remove courses, sessions, and programYears from topic endpoint

src/Ilios/CoreBundle/Controller/CurrentsessionController.php, src/Ilios/CoreBundle/Controller/PublishEventController.php
see http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements
=> get current user from token storage instead of from security context service

src/Ilios/AuthenticationBundle/Voter/UserVoter.php
new, looser rules for granting views permissions on users:
at least one of these must be true.
1. the requested user is the current user
2. the current user has faculty/course director/developer role
fixes ilios/frontend#1272
=> loosen up restrictions for viewing users.

src/Ilios/WebBundle/Controller/IcsController.php
6 months forwards and backwards was resulting in ICS files too large
for google calendar to handle.  Scaling the time range back should help with this.
=> Limit ICS feed events to 1 month back and 2 months forward

src/Ilios/WebBundle/Controller/IcsController.php
Don’t show anything that isn’t published and display only title and
date for scheduled stuff.
Fixes #1235
=> Hide unpublished info from the ICS feed

provision/puppet/environments/dev/files/testshib-config/shibboleth2.xml
This makes the vagrant shibboleth config work with no extra configuration.
=> Update shibboleth config to not require https

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
1. scheduled events do not possess information about their source type (offering vs. ILM), so they must be ignored when attempting to add instructors.
2. filtering a numeric array with `array_filter()` throws off the index and leaves us with a sparse array. when the `$events` array gets passed to `addInstructorToEvent()`, it may be sparse. deal with it by grabbing the array's items into a new, correctly indexed array via `array_values()`.
=> various bug fixes in method that adds instructors to events

app/Resources/DoctrineMigrations/Version20160111222451.php
I forgot to do this despite @stopfstedt reminding me three times.  This should fix it and since we didn’t release with the bad migration name I think this is OK to do.
Refs #1212
=> Move publishing migration to the right place in time

src/Ilios/CoreBundle/Controller/LearningMaterialController.php, src/Ilios/CoreBundle/Form/Type/LearningMaterialType.php
This isn’t needed in the API and wasn’t being sent from the fronted
anyway.
Fixes #1253
=> Don't set relativePath for learning materials

app/config/config_dev.yml
This is in line with what symphony standard edition is now doing.
=> Stop logging events in dev logs

src/Ilios/CliBundle/Command/SendTeachingRemindersCommand.php, src/Ilios/CliBundle/Tests/Command/SendTeachingRemindersCommandTest.php
fixes #1214.
the command option is `--sender_name`. if not specified, then only the provided email address will be used as the email's "from" value.
```
$ bin/console ilios:messaging:send-teaching-reminders --help
Usage:
ilios:messaging:send-teaching-reminders [options] [--] <sender> <base_url>
Arguments:
sender                           Email address to send reminders from.
base_url                         The base URL of your Ilios instance.
Options:
--days[=DAYS]                How many days in advance of teaching events reminders should be sent. [default: 7]
--subject[=SUBJECT]          The subject line of reminder emails. [default: "Upcoming Teaching Session"]
--sender_name[=SENDER_NAME]  The name of the reminder's sender.
--dry-run                    Prints out notification instead …
```
=> added 'sender_name' option to "send teaching reminders" command

app/config/parameters.yml.dist, app/config/parameters.yml.travis, app/config/routing.yml
If forceProtocol is set to https all requests will be redirected, this
is the default, but it can be overridden in parameters.yml.
Fixes #1261
=> Configurable forcing of https

app/config/config_test.yml, src/Ilios/WebBundle/Controller/ConfigController.php, src/Ilios/WebBundle/Tests/Controller/ConfigControllerTest.php
This will allow the fronted to choose the correct workflow for adding
new users to Ilios.
Fixes #1291
=> Add a userSearchType value to config

app/AppKernel.php, app/config/security.yml, composer.json, composer.lock, src/Ilios/CoreBundle/Service/Directory.php, src/Ilios/CoreBundle/Tests/Service/DirectoryTest.php, src/Ilios/WebBundle/Controller/DirectoryController.php, src/Ilios/WebBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Tests/Controller/DirectoryControllerTest.php
Allows us to search for users with the API that passes through to LDAP or another directory store.
Fixes #1290
=> Add /application/directory/search endpoint

app/AppKernel.php
see https://github.com/symfony/http-kernel/blob/master/CHANGELOG.md#230
and https://github.com/symfony/http-kernel/blob/2.8/Kernel.php#L99
=> replaced deprecated init() method with constructor.

src/Ilios/CoreBundle/EventListener/UpdateOfferingTimestamp.php, src/Ilios/CoreBundle/Tests/Controller/OfferingControllerTest.php
This code doesn’t make any sense.  Offering stamps should be updated
from the offering side any time an association changes.
=> Updating a user should not update all of their offerings

.travis.yml, INSTALL.md, composer.json, composer.lock, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
5.6 is the only supported version in the 5.x series, but 5,5 is still
the default on OS X.  While 5.5 is supported and tested 5.6 is the
preferred version.
Also updated all of our composer dependancies to their most recent minor version.
Fixes #1302
=> Remove support for PHP 5.4

composer.lock
paragonie/random_compat (1.1.6 - v1.2.0)
doctrine/doctrine-bundle (1.6.1 - 1.6.2)
phpunit/phpunit (4.8.21 - 4.8.22)
liip/functional-test-bundle (1.3.4 - 1.4.1)
=> Minor version bumps for third part libs

src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/AuthenticationVoter.php, src/Ilios/CoreBundle/Controller/AuthenticationController.php, src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/User.php, src/Ilios/CoreBundle/Form/Type/AuthenticationType.php, src/Ilios/CoreBundle/Handler/AuthenticationHandler.php, src/Ilios/CoreBundle/Resources/config/handlers.yml, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Tests/Controller/AuthenticationControllerTest.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/AuthenticationData.php
- Auto generate an icsFeedKey when a new user is created
- Add controller for creating Authentication instances
These are necessary changes for ilios/frontend#1402
=> Make it easier to add a new user

app/config/config.yml, app/config/config_test.yml
i yanked the Liip profiler and query counter in all environments, and only enabled the profiler in test env.
based on this recommendation: http://symfony.com/doc/current/cookbook/testing/profiling.html#speeding-up-tests-by-not-collecting-profiler-data
we were getting warnings in travis:
see: https://github.com/liip/LiipFunctionalTestBundle#query-counter
=> disable profiler in test env.

src/Ilios/AuthenticationBundle/Service/FormAuthentication.php, src/Ilios/AuthenticationBundle/Service/JsonWebTokenAuthenticator.php, src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php, src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, src/Ilios/AuthenticationBundle/Tests/Service/FormAuthenticationTest.php, src/Ilios/AuthenticationBundle/Tests/Service/LdapAuthenticationTest.php, src/Ilios/AuthenticationBundle/Tests/Service/ShibbolethAuthenticationTest.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/Traits/JsonControllerTest.php
Modified the three supported authentication methods as a failsafe I
also modified the JWT token authenticator to ensure that even if a
disabled user gets a token it cannot be used to access the API.
Fixes #1332
=> Prevent disabled users from logging in

src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManagerInterface.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/WebBundle/Controller/DirectoryController.php, src/Ilios/WebBundle/Tests/Controller/DirectoryControllerTest.php
/application/directory/search no allows a limit and offset query param and returns results with a possible ‘user’ field indicating that the user has an account already.
=> Improve directory

src/Ilios/CoreBundle/Controller/AuthenticationController.php, src/Ilios/CoreBundle/Tests/Controller/AuthenticationControllerTest.php
If we sent password=null to authentication it would blow up, even
though this is a valid thing to do when creating accounts that will
work on shibboleth and ldap providers.
=> Allow an empty password to be passed to authentication POST

src/Ilios/WebBundle/Controller/IcsController.php
Google can only process a file that is less than 1mb in size.  In order
to expand the feed to our desired -4 months +2 months course objectives
have been removed.
Fixes #1230
=> Increase the ICS feed window by removing course objectives

web/app_dev.php
This is needed for development with ember-cli and since we indicate in
our instructions that app_dev.php should be removed in production and
running proxies on localhost isn’t really something anyone does anymore
I think it is safe to remove this protection.
=> Allow access to app_dev.php by proxies

src/Ilios/CoreBundle/Form/Type/TermType.php, src/Ilios/CoreBundle/Tests/Controller/TermControllerTest.php
We don’t allow saving of the many side in a one to many relationship
anywhere, and ember doesn’t send this data by default.
=> Term children should not be saved with the term

src/Ilios/CoreBundle/Controller/UserController.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Tests/Controller/UserControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/UserData.php, src/Ilios/CoreBundle/Tests/DataLoader/UserRoleData.php
User can be filtered by the cohorts they are in or if null is passed
then users with no cohorts will be returned.
=> Filter users by role and cohort

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php
This was turned off when tests were failing because no frontend had been activated.
=> Require a frontend when starting up

src/Ilios/CoreBundle/Entity/SessionDescription.php
Badly formatted annotation was missing a leading astrix
=> Fix annotation for SessionDescription

src/Ilios/AuthenticationBundle/Tests/Voter/AbstractVoterTestCase.php, src/Ilios/AuthenticationBundle/Tests/Voter/UsereventVoterTest.php, src/Ilios/AuthenticationBundle/Voter/UsereventVoter.php
=> grant view privileges to developers on all published user events

app/config/routing.yml, composer.json, composer.lock, src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Resources/config/routing.yml
Replaced patters with path in routes.
Unquotes variables are deprecated and being removed in 3.0.
Fixes #1401
Updating composer libs fixes #1400
=> Clear YAML deprecations

.travis.yml
We now have nothing blocking us from 3.0 so stop ignoring anything new
that pops up and consider it a failure.
=> Stop allowing deprecations in travis builds

app/Resources/updateSchemaFromIlios2toIlios3.sql
This item is re-created later in the script, so it throws an error unless it is removed.
=> added call to remove 'fkey_user_primary_school' index

src/Ilios/CoreBundle/Controller/CurriculumInventoryAcademicLevelController.php, src/Ilios/CoreBundle/Controller/CurriculumInventoryReportController.php, src/Ilios/CoreBundle/Controller/CurriculumInventorySequenceBlockController.php, src/Ilios/CoreBundle/Tests/Controller/CurriculumInventoryReportControllerTest.php, src/Ilios/CoreBundle/Tests/DataLoader/CurriculumInventoryReportData.php
when a ci report gets created, it needs to spawn off academic levels and a sequence in the same go. 
so i augmented the post action on the ci report controller accordingly.
while at it, i flagged certain CRUD actions on the academic lvl and sequence controllers as deprecated as applicable.
=> "atomic" ci report creation

app/Resources/DoctrineMigrations/Version20160608010345.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryReport.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
as discussed with @saschaben, there is no real need to enforce report uniqueness across academic year and associated programs. as long as the report id in the export itself is unique. 
so i ditched the unique constraint from the db schema and made the appropriate changes to the report exporter.
=> rm unique constraint from ci reports.

src/Ilios/CoreBundle/Controller/CurriculumInventoryExportController.php, src/Ilios/CoreBundle/Entity/CurriculumInventoryExport.php, src/Ilios/CoreBundle/Tests/Controller/CurriculumInventoryExportControllerTest.php
finalizing a report resulted in an export record without document, amongst other minor bugs.
this has been hereby fixed.
=> exclude document in payload of curriculum inventory export

src/Ilios/CoreBundle/Controller/LearningMaterialController.php, src/Ilios/CoreBundle/Entity/LearningMaterial.php, src/Ilios/CoreBundle/Tests/Fixture/LoadLearningMaterialData.php
fixes a minor bug, where the token is generated prematurely (the LM's id is not present on record creation).
=> generate LM d/l token explicitly.

src/Ilios/CoreBundle/Classes/CourseRollover.php, src/Ilios/CoreBundle/Tests/Classes/CourseRolloverTest.php
If a session objective is linked to an objective which is no longer
linked to a course we should allow this to be rolled over as it is a
common case left over from Ilios2.
Fixes #1476
=> Allow rollover for sessions with orphaned parent objectives

UPGRADE.md
added missing `--append` option to migration instructions. this will prevent the db from being purged.
=> fixed update instructions.

src/Ilios/CoreBundle/Controller/CourseController.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
Courses can be rolled over with a new title.
Fixes #1487
=> Add newCourseTitle parameter to rollover

src/Ilios/CoreBundle/Controller/CourseController.php, src/Ilios/CoreBundle/Tests/Classes/CourseRolloverTest.php, src/Ilios/CoreBundle/Tests/Controller/CourseControllerTest.php
Added tests for courses with specific start dates and start dates in the future.  Many of these tests are skipped now while @thecoolestguy makes some changes to the service.  
Fixes #1483
Fixes #1485
=> More rollover tests

.travis.yml, app/config/config_prod.yml, bin/symfony_requirements, composer.json, composer.lock, src/Ilios/CoreBundle/Tests/Controller/AbstractControllerTest.php
Running against PHP7 required a few changes:
- use apcu as the cache engine - this is to avoid needing to install a backwards compatibility extension for the old APC API which is unreliable on windows.
- Replace tdn/String type with Stringify which is PHP7 compatible with no conflicts.
Keeping 5.6 support required locking the version of ocramius/proxy-manager at 1.0.
This should be merged **after** the v3.14 release.
Fixes #1480
=> Add PHP7 support, remove 5.6

src/Ilios/CliBundle/Command/CreateUserTokenCommand.php, src/Ilios/CliBundle/Tests/Command/CreateUserTokenCommandTest.php
This isn't necessary and makes it harder to copy/paste the token into a
header.
Fixes #1506
=> Remove superfluous colon from token output

app/Resources/DoctrineMigrations/Version20160715212648.php, src/Ilios/CoreBundle/Entity/Competency.php, src/Ilios/CoreBundle/Entity/CompetencyInterface.php, src/Ilios/CoreBundle/Entity/DTO/TermDTO.php, src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, src/Ilios/CoreBundle/Entity/Term.php, src/Ilios/CoreBundle/Entity/TermInterface.php, src/Ilios/CoreBundle/Entity/Vocabulary.php, src/Ilios/CoreBundle/Entity/VocabularyInterface.php, src/Ilios/CoreBundle/Form/Type/CompetencyType.php, src/Ilios/CoreBundle/Form/Type/TermType.php, src/Ilios/CoreBundle/Form/Type/VocabularyType.php, src/Ilios/CoreBundle/Tests/DataLoader/CompetencyData.php, src/Ilios/CoreBundle/Tests/DataLoader/TermData.php, src/Ilios/CoreBundle/Tests/DataLoader/VocabularyData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadCompetencyData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadTermData.php, src/Ilios/CoreBundle/Tests/Fixture/LoadVocabularyData.php, src/Ilios/CoreBundle/Traits/ActivatableEntity.php, src/Ilios/CoreBundle/Traits/ActivatableEntityInterface.php
This will allow some of these to be de-activated so they can be excluded
from selection while still remaining connected to existing collections
for archive purposes.
Fixes #1519
=> Add active to competency, term, and vocabulary

src/Ilios/CoreBundle/EventListener/LogEntityChanges.php, src/Ilios/CoreBundle/EventListener/TimestampListener.php, src/Ilios/CoreBundle/EventListener/UpdateOfferingTimestamp.php, src/Ilios/CoreBundle/EventListener/UpdateSessionTimestamp.php, src/Ilios/CoreBundle/Tests/EventListener/ContainerInjectorTest.php
Fixed a few minor things.
Most notably, I dropped everything event-subscriber related, since we are using event listeners exclusively.
=> Doctrine event listener cleanup

app/Resources/DoctrineMigrations/Version20150916173024.php, composer.json, composer.lock
Symfony has deprecated the SecureRandom class in favor of the built in
php function.  In order to maintain compatibility with PHP < 7 we need
the compat library as well.
Fixes #1530
=> Replace SecureRandom with random_bytes

app/config/config.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis, src/Ilios/AuthenticationBundle/DependencyInjection/Configuration.php, src/Ilios/AuthenticationBundle/DependencyInjection/IliosAuthenticationExtension.php, src/Ilios/AuthenticationBundle/Resources/config/services.yml, src/Ilios/AuthenticationBundle/Service/CasAuthentication.php, src/Ilios/AuthenticationBundle/Service/CasManager.php, src/Ilios/AuthenticationBundle/Tests/DependencyInjection/ConfigurationTest.php, src/Ilios/AuthenticationBundle/Tests/DependencyInjection/IliosAuthenticationExtensionTest.php, src/Ilios/WebBundle/Controller/ConfigController.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php
This is a pretty simplistic implementation of CAS which basically just
validates a ticket that the frontend has provided.  All of the
redirecting will need to happen there.
todo:
Fixes #1522
=> Add CAS as an auth provider

src/Ilios/CoreBundle/Controller/CurriculumInventorySequenceBlockController.php
when switching the sort order of a block from parallel/unordered to ordered, we must re-sort nested blocks within.
this fix applies the correct strategy for sorting.
=> apply correct strategy when changing sequence sort order

app/config/parameters.yml.travis, composer.lock
`composer update`
- symfony/symfony v2.8.8 to v2.8.9
- doctrine/doctrine-bundle 1.6.3 to 1.6.4
- symfony/phpunit-bridge v2.8.8 to v2.8.9
- webmozart/assert 1.0.2 to 1.1.0
- phpunit/phpunit 4.8.26 to 4.8.27
- ezyang/htmlpurifier v4.7.0 to v4.8.0
- phpcollection/phpcollection 0.4.0 to 0.5.0
- ms/serializer 1.1.0 to 1.2.0
- monolog/monolog 1.20.0 to 1.21.0
- ms/cg 1.1.0 to 1.2.0
=> Update dependencies to latest versions

src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Voter/Entity/AuthenticationEntityVoter.php, src/Ilios/CoreBundle/Tests/Controller/AuthenticationControllerTest.php
We were not injecting the permissionsManager so it wasn't possible to
add authentication records for users in a different primary school than
the requester.
Fixes #1546
=> Add authentication for users with different schools

INSTALL.md, UPGRADE.md
Adding the `SYMFONY_ENV` ensures that symfony’s cache clear command (which
runs at the end of composer install) gets the correct environment and
doesn't blow up on missing packages.
The `—optimize-autoloader` flag is recommended by symfony for production
installs.
Fixes #1549
=> Improved composer install instructions

src/Ilios/WebBundle/Controller/ConfigController.php
The request service no longer exists in symfony3 so it needs to be
passed to the controller as a parameter.
Fixes #1557
=> User Request param instead of a service

tests/CoreBundle/Classes/CourseRolloverTest.php
When the end week cross into the new year we have to prevent it from
going to week 53 and reset it to week 1.
Fixes #1568
=> Adjust expected end week

src/Ilios/CliBundle/Command/AuditLogExportCommand.php, src/Ilios/CoreBundle/Entity/Repository/AuditLogRepository.php
The log was only including fields directly on the log table, we also
need the related userId.
Fixes #1570
=> Add userId to exported audit log

src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php
This prevents cluttering up the logs with invalid attempts.
Fixes #1563
=> Detect if a session exists before attempting to destroy it

src/Ilios/CoreBundle/Entity/Session.php
When ILM is removed from a session we send NULL to this method.  We
should not then turn around and attempt to set the session on that NULL
values.
Fixes #1564
=> Don't set the session if we are unsetting the ILM session

app/config/security.yml, src/Ilios/AuthenticationBundle/Service/JsonWebTokenManager.php, src/Ilios/CoreBundle/Controller/CourseController.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/ProgramControllerTest.php, tests/CoreBundle/Controller/ProgramYearControllerTest.php, tests/CoreBundle/Traits/JsonControllerTest.php
We were using a 'modify' keyword as well as doing voter lookup by
allowing a single yes voter to grant permissions.  Instead we need to
check with all voters and ensure we are looking for both 'delete' and
'modify' permissions.
Fixes #1576
=> Enforce permission for archivable and lockable entities

src/Ilios/CoreBundle/Entity/Cohort.php, src/Ilios/CoreBundle/Entity/LearnerGroup.php
These aren't really useful in our case and may have something to do with
deadlock issues we have experienced.
=> Remove EXTRA_LAZY annotations

tests/CoreBundle/Classes/CourseRolloverTest.php
Some tests were getting messed up as they rolled within 16 weeks of the
end of the year.
=> Fix flakey end of the year tests

src/Ilios/CoreBundle/Entity/CurriculumInventoryAcademicLevelInterface.php, src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
We pre-create a bunch of academic levels for a report, but we should
only include those levels which have a sequence block associated with
them in the final report.
Fixes #1584
=> Only include used levels in CI export

src/Ilios/CoreBundle/Form/Type/AuthenticationType.php, tests/CoreBundle/Controller/AuthenticationControllerTest.php
Empty values were getting converted into blank strings which then caused
duplicate key errors in the DB.  Instead they need to be stored as NULL.
Fixes #1590
=> When and empty username is sent store it as null

app/Resources/DoctrineMigrations/Version20160915043119.php, src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseInterface.php, src/Ilios/CoreBundle/Entity/DTO/CourseDTO.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/ObjectiveInterface.php, src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php, src/Ilios/CoreBundle/Form/Type/CourseType.php, src/Ilios/CoreBundle/Form/Type/ObjectiveType.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/DataLoader/CourseData.php, tests/CoreBundle/DataLoader/ObjectiveData.php, tests/CoreBundle/Entity/CourseTest.php, tests/CoreBundle/Entity/ObjectiveTest.php, tests/CoreBundle/Fixture/LoadCourseData.php, tests/CoreBundle/Fixture/LoadObjectiveData.php
We will use the ancestor to track where courses and objectives come from
during rollovers and reporting.
Refs #729
=> Add ancestry to courses and objectives

src/Ilios/CoreBundle/Resources/views/Email/teachingreminder.text.twig
=> removed the line referencing 'UCSF' from the email template

src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, tests/AuthenticationBundle/Service/ShibbolethAuthenticationTest.php
We were logging out the entire $_SERVER stack, but that is much more
information than we need to handle authentication issues.
Fixes #1471
=> Log less information when there is a missing ship parameter

src/Ilios/CliBundle/Command/RolloverCurriculumInventoryReportCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Controller/CurriculumInventoryReportController.php, src/Ilios/CoreBundle/Resources/config/routing.yml, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/CurriculumInventory/ReportRollover.php, tests/CliBundle/Command/RolloverCurriculumInventoryReportCommandTest.php, tests/CoreBundle/Controller/CurriculumInventoryDownloadControllerTest.php, tests/CoreBundle/Controller/CurriculumInventoryReportControllerTest.php, tests/CoreBundle/DataLoader/CurriculumInventoryAcademicLevelData.php, tests/CoreBundle/DataLoader/CurriculumInventoryReportData.php, tests/CoreBundle/DataLoader/CurriculumInventorySequenceBlockData.php
=> curriculum inventory report rollover.

src/Ilios/CoreBundle/Entity/Course.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/SessionControllerTest.php, tests/CoreBundle/Controller/SessionTypeControllerTest.php, tests/CoreBundle/DataLoader/ObjectiveData.php, tests/CoreBundle/Entity/CourseTest.php
The link between course objectives and session objectives is not
something the DB can remove on its own, we have to look for an remove
this ourselves.
Fixes #1597
=> When a course objective is removed unlink session objectives

src/Ilios/AuthenticationBundle/Service/JsonWebTokenAuthenticator.php
There is already an AuthenticationInterface in this directory and PHP
did not handle the conflict well.
Fixes #1645
=> Use AuthenticationInterface as a different name to avoid conflicts

src/Ilios/CoreBundle/Controller/UploadController.php, tests/CoreBundle/Controller/UploadControllerTest.php
There doesn't seem to be a better way to trap the error when a posted
file exceeds the PHP post_max_size limit. So I added some text to the
error to indicate that this is probable the case.
Fixes #1196
=> Clarify error message for large file uploads

src/Ilios/CoreBundle/Resources/config/routing.yml
=> fixed route to ci rollover report endpoint.

src/Ilios/CoreBundle/Controller/UploadController.php, src/Ilios/WebBundle/Controller/ConfigController.php
Instead of calculating this on our own just use the static method built
into the Symfony UploadFile class.
=> Use Symfony builtin to detect maximum file upload size

src/Ilios/WebBundle/Controller/ConfigController.php, tests/WebBundle/Controller/ConfigControllerTest.php
This makes it possible to detect issues on the frontend where a mismatch
might occur.
Fixes #1655
=> Add API version to configuration

src/Ilios/WebBundle/Controller/IcsController.php, tests/CoreBundle/DataLoader/LearningMaterialData.php, tests/CoreBundle/DataLoader/LearningMaterialStatusData.php, tests/WebBundle/Controller/IcsControllerTest.php
We were not correctly filtering out those learning materials which are
in draft status and should not be shown.
Fixes #1659
=> Exclude draft LMs from ICS Feed

src/Ilios/AuthenticationBundle/Resources/config/dto_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/entity_voters.yml, src/Ilios/AuthenticationBundle/Resources/config/voters.yml, src/Ilios/AuthenticationBundle/Voter/DTO/ObjectiveDTOVoter.php, src/Ilios/AuthenticationBundle/Voter/Entity/ObjectiveEntityVoter.php, src/Ilios/CoreBundle/Controller/ObjectiveController.php, src/Ilios/CoreBundle/Entity/DTO/ObjectiveDTO.php, src/Ilios/CoreBundle/Entity/Manager/BaseManager.php, src/Ilios/CoreBundle/Entity/Manager/ManagerInterface.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/Repository/ObjectiveRepository.php, tests/CoreBundle/Controller/ObjectiveControllerTest.php
Speeds up access to Objectives and adds filters for courses, sessions,
and programYears.
Fixes #1666
=> Make objective a DTO

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/CoreBundle/Controller/UsermaterialsControllerTest.php, tests/CoreBundle/DataLoader/CourseData.php
Sending this information about the course will prevent extra lookups to
get LM metadata.
Fixes #1672
=> Add courseId and title to session usermaterials

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/CoreBundle/Controller/UsermaterialsControllerTest.php
Uses to course date to present a first offering date for user materials.
Fixes #1676
=> Add firstOfferingDate to course learning materials

app/AppKernel.php, app/config/config.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis, composer.json, composer.lock, src/Ilios/CoreBundle/DependencyInjection/Configuration.php, src/Ilios/CoreBundle/DependencyInjection/IliosCoreExtension.php, src/Ilios/CoreBundle/EventListener/TrackApiUsageListener.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/WebBundle/Controller/ConfigController.php, tests/CoreBundle/DependencyInjection/IliosCoreExtensionTest.php, tests/CoreBundle/EventListener/TrackApiUsageListenerTest.php, tests/WebBundle/Controller/ConfigControllerTest.php
fixes #1148 
the "tracking enabled" flag and the tracking code itself are exposed via the config endpoint in the API (the latter only if the tracking has been enabled.)
google will receive the following three data attributes for each API controller hit
- the API server's host name
- the API endpoint URI ("path")
- the fully qualified name of the controller class that was called.
=> track API usage

src/Ilios/CoreBundle/Entity/Manager/BaseManager.php, src/Ilios/CoreBundle/EventListener/TimestampEntityChanges.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/Timestamper.php, src/Ilios/CoreBundle/Traits/TimestampableEntity.php, src/Ilios/CoreBundle/Traits/TimestampableEntityInterface.php, tests/CoreBundle/Controller/SessionControllerTest.php, tests/CoreBundle/Entity/Manager/OfferingManagerTest.php
By moving the timestamping of entities changed and their related changed
sessions and offerings into its own post flush process we will hopefully
avoid deadlocks which have frequently occurred here. I had to use the
query builder instead of just calling stampUpdate on the entities
because when a relationship is deleted in the flush (like
sessionDescription) it still attempts to save it in our postFlush event.
This causes issues so instead I'm only working with the IDs and not the
entities.
Fixes #1683
=> Timestamp updated entities outside of the normal flow

src/Ilios/AuthenticationBundle/Service/JsonWebTokenManager.php, tests/AuthenticationBundle/Service/JsonWebTokenManagerTest.php
It is not possible to compare DateInterval objects.  We first need to
apply them to a DateTime and then calculate that difference.
Fixes #1709
=> Correctly apply maximum TTL for tokens

src/Ilios/CoreBundle/Classes/CourseRollover.php, tests/CoreBundle/Classes/CourseRolloverTest.php
This allows for rolling over a spring course in the 2016 - 2017 academic
year in January 2017.
Fixes #1711
=> Allow courses to be rolled over in the previous year

src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, tests/CoreBundle/Controller/AbstractControllerTest.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Controller/SchooleventsControllerTest.php, tests/CoreBundle/Controller/UsereventControllerTest.php, tests/CoreBundle/Controller/UsermaterialsControllerTest.php, tests/CoreBundle/DataLoader/OfferingData.php
One of the offerings now uses a variable date in order to stay current.
Instead of looking for a static date we need to grab the correct entity
and check that date.
Fixes #1716
=> Use variable date from offering fixture in tests

src/Ilios/AuthenticationBundle/Voter/DepartmentVoter.php
This is essentially directory information and this allows program year
stewards to be viewed when the stewarding department is not in the
primary school.
Fixes #1722
=> Grant VIEW permissions for all departments

src/Ilios/CoreBundle/Entity/Repository/SessionTypeRepository.php, tests/CoreBundle/Controller/SessionTypeControllerTest.php
refs #1725.
the SQL equivalent of this filter is
```sql
SELECT DISTINCT st.* 
FROM session_type st
JOIN session s ON s.session_type_id = st.session_type_id
LEFT JOIN session_x_term sxt ON sxt.session_id = s.session_id
LEFT JOIN term t ON t.term_id = sxt.term_id
LEFT JOIN course c ON c.course_id = s.course_id
LEFT JOIN course_x_term cxt ON cxt.course_id = c.course_id
LEFT JOIN term t2 ON t2.term_id = cxt.term_id
WHERE (
t2.term_id IN (?) 
OR t.term_id IN (?)
);
```
=> filter session types by terms

INSTALL.md, app/config/config_dev.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis
debug_toolbar and debug_redirects are never used in anything but the dev
environment and there they can just be set in config_dev.yml and they
are usually true and false respectively anyway.  Lets remove them and
remove some complication from configuration.
=> Remove debug parameters which are only used in dev

src/Ilios/WebBundle/Resources/views/WebIndex/webindex.html.twig, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/WebBundle/Service/WebIndexFromJsonTest.php
Our frontend JSON now includes script tags with no src attribute but
with actual JS inside the content property.
Fixes #1692
=> Read content from scripts when pulling frontend JSON

src/Ilios/CoreBundle/Classes/CourseRollover.php, src/Ilios/CoreBundle/Entity/Course.php, src/Ilios/CoreBundle/Entity/CourseInterface.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/ObjectiveInterface.php, tests/CoreBundle/Classes/CourseRolloverTest.php, tests/CoreBundle/Controller/CourseControllerTest.php, tests/CoreBundle/Entity/CourseTest.php, tests/CoreBundle/Entity/ObjectiveTest.php
Courses and Objectives both track their ancestors so when they are
rolled over they should either inherit the ancestor of the previous
entity or else set the previous entity to be their ancestor.
Refs #729
=> Create ancestor relationship when rolling over courses

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/Resources/views/Index/error.html.twig, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/CliBundle/Command/UpdateFrontendCommandTest.php, tests/WebBundle/Controller/IndexControllerTest.php
Instead of just dying we can be much better with this.  By messaging the
user during cache:clear and then presenting an error page we can ensure
that tests will run even if there is an API mismatch between Ilios and
the fronted and no comparable fronted is yet available.
Fixes #1626 
The user will see this screen if they attempt to load ilios while there is no frontend:
=> Fail gracefully on missing frontend

src/Ilios/AuthenticationBundle/Voter/Entity/UserEntityVoter.php, tests/CoreBundle/Controller/UserControllerTest.php
Without this check it is possible for a user to add roles to their own
account.  This happens because doctrine keeps the User object in sync
between our authentication token and the user we modify in the
controller.  Since our process is to modify users and then check
authentication anyone can send a set of roles they want and the roles
will be applied before the authorization is checked.
Fixes #1762
=> Prevent users from editing their own account

app/config/config.yml, app/config/config_prod.yml, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/CacheFactory.php, tests/CoreBundle/Service/CacheFactoryTest.php
This will allow us to use other configuration parameters to choose the
cache we want in a specific environment.  For now we’re just duplicating our existing APCu cache in production.
=> Create a customizable cache for Ilios

Dockerfile.dev, README.md, docker/apache.conf, docker/ilios.ini
This is useful for broader testing - especially frontened integration
testing where the PHP server's single threaded nature makes requests way
too slow.
=> Add a development docker container

composer.json
We need the cache to be warmed to our index.html file will get built.
Even if we instruct users to run a cache clear they may not, so lets
just make it part of the install.
=> Warmup the cache when composer installs or updates

.travis.yml
We no longer need to install apcu ourselves in PHP 7+, we just need to let travis
know it should be activated.
Fixes #1777
=> Enable already installed apcu extension

.travis.yml
This test was put in to prevent issues where the AppKernel.php file and
the composer dependencies were out of sync with a dev composer
dependency in the production kernel tree.  Unfortunately it prevents
testing when a suitable release of the frontend cannot be found to match
the API version.  Since the version mismatch happens every couple of
weeks and then AppKernel issue has only happened once in 2 years we
should err on the side of useful and likely here.
=> Remove production composer install test

Dockerfile.dev
Dockerfile.dev is specifically for use while developing and should use
the 'dev' environment.
=> Use the dev environment in development container

app/config/config.yml, src/Ilios/ApiBundle/Controller/ApiController.php, src/Ilios/ApiBundle/Controller/CurrentSessionController.php, src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/ApiBundle/Controller/UsermaterialController.php, src/Ilios/ApiBundle/Resources/config/services.yml, src/Ilios/ApiBundle/Service/SerializerFactory.php, src/Ilios/CoreBundle/Classes/CurrentSession.php, src/Ilios/CoreBundle/Service/EntityMetadata.php, tests/CoreBundle/Traits/JsonControllerTest.php
Don't trust Cache:contains completely: This method sometimes returns true when the actual Cache::fetch() returns false instead of what the cache should have.  This seems to have to do with APCu's memory or other settings.
The default Symfony serializer falls back all the way to an
ObjectNormalizer that will serialize ANY object it is given.  We don't
want to serialize any random object - just those Entities and DTOs that
we have crafted.  By creating our own serializer we can control exactly
what is serializable.
Fixes #1798
=> Improve Serialization

src/Ilios/CoreBundle/Service/CacheFactory.php, src/Ilios/CoreBundle/Service/EntityMetadata.php, tests/CoreBundle/Service/CacheFactoryTest.php
This SNAFU was causing non-dto entities to be un-usable.  I also
switched our testing to use APCu for caching just like production does
which will help catch this kind of failure in the future.
=> Fix incorrect caching or DTOs as entities

src/Ilios/ApiBundle/Normalizer/Entity.php, tests/IliosApiBundle/Endpoints/IlmSessionTest.php, tests/IliosApiBundle/Endpoints/OfferingTest.php
Datetimes are sent with their own timezon, but mysql doesn't respect
this so we need to convert each one to server time before it is stored
in the database.
Fixes #1808
=> Convert dateTimes to the server timezone when they are sent

src/Ilios/CliBundle/Command/CrossingGuardCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Classes/IliosFileSystem.php, src/Ilios/CoreBundle/Classes/TemporaryFileSystem.php, src/Ilios/CoreBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/CrossingGuard.php, tests/CliBundle/Command/CrossingGuardCommandTest.php, tests/CoreBundle/Classes/IliosFileSystemTest.php, tests/CoreBundle/Service/CrossingGuardTest.php
When the crossing guard is down requests will be queued and held until
it is up again. This is useful for putting the API into a very temporary
maintenance mode while running any necessary migrations during
deployment. Instead of blocking and erroring we can simply hold off on
responding to requests until the DB is ready.
I implemented this using a lock file as it was the only repeatable strategy I could come up with.  Attempting to store the value in an ENV didn't work since those don't carry over to other running scripts and putting it in the cache failed as well.
=> Intercept requests with a crossing guard

src/Ilios/AuthenticationBundle/Voter/Entity/UserEntityVoter.php, tests/IliosApiBundle/Endpoints/UserTest.php
This is now unnecessary since users permissions are now stored
immutably in the SessionUser.
=> Remove temporary user modification workaround

src/Ilios/AuthenticationBundle/Voter/Entity/ApplicationConfigEntityVoter.php, tests/AuthenticationBundle/Voter/AbstractVoterTestCase.php, tests/AuthenticationBundle/Voter/DTO/ApplicationConfigDTOVoterTest.php, tests/AuthenticationBundle/Voter/DTO/SchoolDTOVoterTest.php, tests/AuthenticationBundle/Voter/Entity/ApplicationConfigEntityVoterTest.php
This configuration is for the system and should only be readable /
writable by developers as it may contain sensitive information like the
LDAP credentials and the JWT signing key.
Fixes #1819
=> Restrict access to applicationConfig to developers

src/Ilios/AuthenticationBundle/Voter/Entity/UserEntityVoter.php, tests/IliosApiBundle/Endpoints/UserTest.php
We were passing a doctrine collection to the
SessionUser::hasWritePermissionToSchools method and it requires an
array.
Fixes #1829
=> Fix for users not able to create users in non-primary school

src/Ilios/ApiBundle/Resources/swagger/definitions/CalendarEvent.yml, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/IliosApiBundle/Endpoints/SchooleventsTest.php, tests/IliosApiBundle/Endpoints/UsereventTest.php
For both user and school events having access to these attributes will
prevent needing to traverse the API to get to this data and speed up the
user experience.
=> Add session attributes to events APIs

src/Ilios/CoreBundle/Entity/Repository/TermRepository.php, tests/IliosApiBundle/Endpoints/TermTest.php
=> filter terms by school via owning vocabulary, not by linked sessions/courses.

app/config/config_prod.yml
Missing an `%` in this config file blows up the production environment.
=> Fix error in prod config

src/Ilios/ApiBundle/Resources/swagger/definitions/Sessiontype.yml
These were updated in the endpoint, but not the docs
Fixes #1850
=> Add missing properties for session type endpoint

.travis.yml, tests/IliosApiBundle/Endpoints/AamcPcrsTest.php, tests/IliosApiBundle/Endpoints/AcademicYearTest.php, tests/IliosApiBundle/Endpoints/AlertTest.php, tests/IliosApiBundle/Endpoints/AuthenticationTest.php, tests/IliosApiBundle/Endpoints/CompetencyTest.php, tests/IliosApiBundle/Endpoints/CurriculumInventoryReportTest.php, tests/IliosApiBundle/Endpoints/MeshConceptTest.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php, tests/IliosApiBundle/Endpoints/SchoolConfigTest.php, tests/IliosApiBundle/Endpoints/SchoolTest.php, tests/IliosApiBundle/Endpoints/SessionDescriptionTest.php
Consolidating several smaller test runs in CI allows us to expand the
number of API groups and hopefully make each tests a bit quicker.
=> Re-balance test groups

src/Ilios/CliBundle/Command/AddNewStudentsToSchoolCommand.php, src/Ilios/CliBundle/Command/InstallFirstUserCommand.php, src/Ilios/CliBundle/Command/SendChangeAlertsCommand.php, src/Ilios/CliBundle/Command/SendTeachingRemindersCommand.php, src/Ilios/CliBundle/Command/SyncFormerStudentsCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Entity/Manager/AlertManager.php, src/Ilios/CoreBundle/Entity/Manager/UserRoleManager.php, src/Ilios/CoreBundle/Resources/config/dto-managers.yml, src/Ilios/CoreBundle/Resources/config/services.yml, tests/CliBundle/Command/AddNewStudentsToSchoolCommandTest.php, tests/CliBundle/Command/InstallFirstUserCommandTest.php, tests/CliBundle/Command/SendChangeAlertsCommandTest.php, tests/CliBundle/Command/SyncFormerStudentsCommandTest.php
Removes the services.yml boilerplate for setting up and registering the
commands. Followed the guide at https://symfony.com/doc/current/service_container/3.3-di-changes.html
=> Autowire and Autoconfigure the CLI bundle

.travis.yml
Single lines wasn't always failing when it should have.
=> Split up the code style check into two lines

src/Ilios/CoreBundle/Entity/Session.php, tests/IliosApiBundle/Endpoints/SessionTest.php
Session Description isn't required so it should be possible to set it to
null.
=> Allow SessionDescription to be set to null

.travis.yml
we're getting build errors, could be related to the travis' recent switch from ubuntu precise to trusty.
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
refs #1882.
forcing precise until we can figure out what's up, hopefully that works.
=> force ubuntu precise.

src/Ilios/CoreBundle/Service/Directory.php, tests/CoreBundle/Service/DirectoryTest.php
=> escape search terms when dynamically building LDAP filter.

src/Ilios/CoreBundle/EventListener/LogEntityChanges.php, src/Ilios/WebBundle/Controller/ConfigController.php, tests/CoreBundle/Traits/JsonControllerTest.php, tests/IliosApiBundle/Endpoints/AcademicYearTest.php, tests/IliosApiBundle/Endpoints/AuthenticationTest.php, tests/IliosApiBundle/Endpoints/CohortTest.php, tests/IliosApiBundle/Endpoints/CourseTest.php, tests/IliosApiBundle/Endpoints/CurriculumInventoryInstitutionTest.php, tests/IliosApiBundle/Endpoints/CurriculumInventorySequenceTest.php, tests/IliosApiBundle/Endpoints/IlmSessionTest.php, tests/IliosApiBundle/Endpoints/MeshPreviousIndexingTest.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php, tests/IliosApiBundle/Endpoints/OfferingTest.php, tests/IliosApiBundle/Endpoints/PermissionTest.php, tests/IliosApiBundle/Endpoints/ProgramYearStewardTest.php, tests/IliosApiBundle/Endpoints/SchooleventsTest.php, tests/IliosApiBundle/Endpoints/SessionDescriptionTest.php, tests/IliosApiBundle/Endpoints/SessionTest.php, tests/IliosApiBundle/Endpoints/SessionTypeTest.php, tests/IliosApiBundle/Endpoints/UserTest.php, tests/IliosApiBundle/Endpoints/UsereventTest.php
This removes any possibility of confusion over what service is being
loaded and makes refactoring much simpler since bad definitions will be
called out in static import analysis and not just when running the code.
=> Call services using their class name

src/Ilios/ApiBundle/Controller/SwaggerDocsController.php, src/Ilios/ApiBundle/Resources/views/swagger/index.html.twig
Not sending text/css causes some browsers not to interpret the CSS and
leaves us with an ugly page.
=> Send content type with swagger files

src/Ilios/CoreBundle/Resources/views/apiinfo.html.twig
We're no longer using the bundle for this, just our own route will do.
=> Fix link to API docs

src/Ilios/CliBundle/Command/UpdateServiceWorkerCommand.php, src/Ilios/CliBundle/Resources/config/services.yml, src/Ilios/CoreBundle/Service/Fetch.php, src/Ilios/WebBundle/Controller/ServiceWorkerController.php, src/Ilios/WebBundle/Resources/config/routing.yml, src/Ilios/WebBundle/Resources/config/services.yml, src/Ilios/WebBundle/Service/WebIndexFromJson.php, tests/CliBundle/Command/UpdateServiceWorkerCommandTest.php, tests/WebBundle/Controller/ServiceWorkerControllerTest.php, tests/WebBundle/DependencyInjection/IliosWebExtensionTest.php, tests/WebBundle/Service/WebIndexFromJsonTest.php
Service worker JS files MUST come from the same domain as the index.html
file so we have to pull them directly and serve them from the API just
like our index file.
=> Get Service Worker files from our CDN and serve them up

composer.lock
Ran `composer update` and updated:
| Production Changes             | From   | To      |
|--------------------------------|--------|---------|
| cache/adapter-common           | 0.3.3  | 1.0.0   |
| cache/hierarchical-cache       | 0.3.0  | 1.0.0   |
| cache/taggable-cache           | 0.4.3  | REMOVED |
| cache/void-adapter             | 0.3.1  | 1.0.0   |
| doctrine/orm                   | v2.5.6 | v2.5.8  |
| happyr/google-analytics-bundle | 4.0.1  | 4.0.2   |
| php-http/discovery             | 1.2.1  | 1.3.0   |
| php-http/httplug-bundle        | v1.7.0 | v1.7.1  |
| sensiolabs/security-checker    | v4.1.1 | v4.1.3  |
| swagger-api/swagger-ui         | v3.1.1 | v3.1.5  |
| symfony/symfony                | v3.3.5 | v3.3.6  |
| cache/tag-interop              | NEW    | 1.0.0   |
| Dev …
=> Updated Dependencies

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php
We're hiding useful exception information here.
=> Add more details to error when updating frontend

src/Ilios/CliBundle/Command/FixLearningMaterialMimeTypesCommand.php, src/Ilios/CliBundle/Command/MigrateIlios2LearningMaterialsCommand.php, tests/CliBundle/Command/FixLearningMaterialMimeTypesCommandTest.php
We were incorrectly storing some learning materials mimetypes to
link or citation, but that can be fixed.
This command looks through all learning materials to find
ones with a problem and fixes them. First we try and detect the type
from the file itself then we fallback to using the extension on the
filename.
Fixes #1897
=> Fix bad mimetypes in learning materials

app/config/config.yml
Not sure why this was at 2 seconds, that isn't a lot of time. This gives
us 10 instead for things like updating the frontend.
=> Longer timeout for network requests

src/Ilios/WebBundle/Service/WebIndexFromJson.php
Ensures that Version20170818144244 migration is run before the frontend
starts looking for the `active` flag on session types.
=> Bump the API to v1.23

src/Ilios/CoreBundle/Entity/LearnerGroup.php, src/Ilios/CoreBundle/Entity/LearnerGroupInterface.php, tests/IliosApiBundle/Endpoints/LearnerGroupTest.php
This is already working through a workaround we have in the serializer,
this just removes the error from the logs.
Refs #1878
=> Allow group parents to be removed

src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, tests/AuthenticationBundle/Service/ShibbolethAuthenticationTest.php
Sometimes shibboleth gives us a valid session with not user data
attached to it. We shouldn't punish our users for this - instead we can
just tell the frontend to bounce them into the Login again to get better
data.
Fixes #1925
=> Redirect users instead of sending a 500 error when shib is dumb

src/Ilios/CliBundle/Command/SyncAllUsersCommand.php, src/Ilios/CoreBundle/Service/Directory.php, tests/CliBundle/Command/SyncAllUsersCommandTest.php, tests/CoreBundle/Service/DirectoryTest.php
Fix for two LDAP Directory issues:
1) When finding a group of users by campusId we were querying for too many records at the same time. LDAP servers are much happier returning lots of little data sets instead of one big one.
2) If a user who is ignored in the sync is a duplicate of one who isn't and the ignored user already has an authentication record then a collision will occur when trying to update the second user. We now log this for further investigation instead of dying tragically.
=> Directory fixes

app/Resources/DoctrineMigrations/Version20170906230101.php
this corrects an incorrectly re-attached foreign key constraint in a migration that was part of the MeSH-importer change-set.
=> corrected sql in migration.

src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/ApiBundle/Controller/UsermaterialController.php, src/Ilios/ApiBundle/Resources/swagger/definitions/CalendarEvent.yml, src/Ilios/AuthenticationBundle/Voter/UsermaterialVoter.php, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Classes/UserEvent.php, src/Ilios/CoreBundle/Classes/UserMaterial.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Service/UserMaterialFactory.php, tests/CoreBundle/Classes/UserEventTest.php, tests/IliosApiBundle/Endpoints/SchooleventsTest.php, tests/IliosApiBundle/Endpoints/UsereventTest.php, tests/IliosApiBundle/Endpoints/UsermaterialsTest.php
fixes #1946.
also refs ilios/frontend#3273
btw, i threw a voter on user materials in the api endpoint to strip out any in-draft materials if the requesting user has no privileges above student. 
not sure if the lack of this voter was by design or an oversight. i'm inclined to think that it's the latter. @saschaben thoughts on that?
=> include learning materials in school event.

src/Ilios/CoreBundle/Controller/ExceptionController.php
We were checking for 'production' here which isn't a valid environment
(it is called 'prod'). This caused us to send full error messages (but
not stack traces) when we should have sent a much more limited response.
Fix this issue and also invert the condition to make it harder to make
this mistake again.
=> Limit error messages in production environment

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
In both `getInstructorsForOfferings` and `getInstructorsForIlmSessions` we run a
query to attach instructor names to a specific offering / ilm either
through direct connection or through group membership.
Running this as an IN or IN query is about 20 times slower in MySQL than
running it in two parts.
=> Split up slow queries

src/Ilios/WebBundle/Controller/IndexController.php, src/Ilios/WebBundle/Resources/config/routing.yml, tests/WebBundle/Controller/IndexControllerTest.php
Three different caching strategies are needed:
1) The index.html file should be cached by browsers, but it must be
checked on every request to ensure it is fresh. If it is then return a
304 No Change header
2) sw.js and sw-registration.js are handed like index.html to ensure all
updated get noticed immediately.
3) The rest of our files are fingerprinted and they can be cached
forever (I set it to one year) browsers never need to check back as they
will get a new fingerprint if they are ever updated.
=> Improve caching of frontend assets

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php, src/Ilios/CoreBundle/Service/Fetch.php, tests/CliBundle/Command/UpdateFrontendCommandTest.php
By keeping the frontend in a version and environment specific cache we
can sent the right headers to CloudFront so we get a 304 Not Modified
response back when the frontend has not been updated. That way we don't
need to download it again.
=> Save bandwidth by using a cached version of the frontend

src/Ilios/WebBundle/Controller/IndexController.php, tests/WebBundle/Controller/IndexControllerTest.php, web/.htaccess
Apache munges the etag header when it deflates static files. This causes
us to send the full file instead of a 304 and slows down user requests.
If we handle the compression step ourselves we can work around this and
not need to worry about individual web server configurations.
Fixes #1967
=> Handle compression for file requests ourselves

src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/ApiBundle/Controller/UsermaterialController.php, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Classes/UserEvent.php, tests/IliosApiBundle/Endpoints/UsereventTest.php, tests/IliosApiBundle/Endpoints/UsermaterialsTest.php
No matter what the privileges are for a user or for the user events they
are viewing they should only see published events.
This has mostly no effect as the permission system was filtering out most of these events anyway. The system was *not* filtering out draft materials, so that is a change.
=> Don't show draft events when viewing another users events

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php, src/Ilios/CoreBundle/Service/FinderFactory.php, src/Ilios/WebBundle/Controller/IndexController.php, tests/CliBundle/Command/UpdateFrontendCommandTest.php, tests/WebBundle/Controller/IndexControllerTest.php
Since virtually every client will requests compressed assets we should
do that work up front when the files are downloaded so save resources
when they are requested.
=> Compress Assets Once

src/Ilios/CoreBundle/Service/Config.php, src/Ilios/CoreBundle/Service/Fetch.php, tests/CoreBundle/Service/ConfigTest.php
When we have an ENV variables set to a string true, false, null we need
to return the actual value and not just the string.
=> Handle String ENV variables better

app/Resources/DoctrineMigrations/Version20160105002207.php
`date_default_timezone_get` returns a string and we need a DateTimeZone
object instead.
Thanks to John Ansorge at OHSU for reporting the issue and including a fix!
=> Fix timezone migration

.travis.yml, composer.json, composer.lock
Drop support for PHP 7.0 and begin testing in PHP 7.2.
Update all dependencies that can now work with the newer PHP version
constraint.
Refs #1985
=> Raise our minimum PHP version to 7.1+

app/config/config.yml
We are now providing new filters for learning materials and a new set of
administrator relationships for Curriculum Inventory.
=> Bump API version to 1.27

src/Ilios/AuthenticationBundle/RelationshipVoter/GreenlightViewDTOVoter.php, src/Ilios/AuthenticationBundle/RelationshipVoter/LearnerGroup.php, src/Ilios/AuthenticationBundle/RelationshipVoter/LearningMaterialStatus.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Objective.php, src/Ilios/AuthenticationBundle/RelationshipVoter/ProgramYear.php, src/Ilios/AuthenticationBundle/RelationshipVoter/Report.php, src/Ilios/AuthenticationBundle/Service/PermissionChecker.php, tests/AuthenticationBundle/RelationshipVoter/GreenlightViewDtoVoterTest.php, tests/AuthenticationBundle/RelationshipVoter/LearnerGroupTest.php, tests/AuthenticationBundle/RelationshipVoter/LearningMaterialStatusTest.php, tests/AuthenticationBundle/RelationshipVoter/ObjectiveTest.php, tests/AuthenticationBundle/RelationshipVoter/OfferingTest.php, tests/AuthenticationBundle/RelationshipVoter/ReportTest.php, tests/IliosApiBundle/Endpoints/CurriculumInventorySequenceBlockTest.php
refs #1950
some notes:
- learner groups: need elevated privileges to view.
- learning material status: can be read by everyone, but only modified by root.
- reports: CRUD privileges only to report owner, and root.
- objectives: readable by all, create/update/delete checks are performed against program-year/course/session context as applicable.
=> new perms and voters

app/Resources/DoctrineMigrations/Version20180102185950.php, src/Ilios/CoreBundle/Entity/Authentication.php
fixes #2023 
that column already has an primary index on it, which enforces uniqueness. so no need to have an additional unique index on it.
=> drop unnecessary index from schema.

src/Ilios/CoreBundle/Service/Config.php, tests/CoreBundle/Service/ConfigTest.php
Reading only from $_SERVER doesn't work for variables which are part of the execution context on the machine. We need to check in $_ENV as well.  $_ENV is not always filled however, depending on the way the script was called so we also need to check in $_SERVER.
Fixes #2056
=> Read ENV variables from $_ENV as well as $_SERVER

Dockerfile
We don't need to install the frontend, it is done during cache warming
Fixes #2079
=> Clear and warmup the cache in our docker build

.travis.yml, composer.json, composer.lock, docs/ilios_php_version_policy.md, docs/install.md
As indicated in the Ilios version policy we may drop support for a minor
version of PHP 90 days after the new version is released. PHP 7.2 was
released on November 30th 2017 and PHP 7.2 is now available in the IUS
repository.
Composer update after changing our minimum version also updates:
| Production Changes     | From  | To    | Compare                                                        |
|------------------------|-------|-------|----------------------------------------------------------------|
| ocramius/proxy-manager | 2.1.1 | 2.2.0 | Ocramius/ProxyManager@2.1.1...2.2.0 |
=> Drop support for PHP 7.1

app/Resources/DoctrineMigrations/Version20180326223500.php, src/Ilios/CoreBundle/Entity/AuditLog.php, src/Ilios/CoreBundle/Entity/AuditLogInterface.php, tests/CoreBundle/Entity/AuditLogTest.php
This allows entities with a string ID like AAMC Resource Type to be
logged.
Fixes #2095
=> Convert audit_log objectId to be a varchar instead of an integer

src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/ApiBundle/Resources/swagger/definitions/CalendarEvent.yml, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Classes/UserEvent.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Traits/CalendarEventRepository.php, tests/CoreBundle/Entity/Manager/SchoolManagerTest.php
Adds the data we need to render events without making another trip to the API and without needing access to endpoints that students cannot access.
WIP:
=> Add Missing Event Details

src/Ilios/CliBundle/Command/UpdateFrontendCommand.php
When there are network issues or when we have an API that doesn't have a
corresponding frontend release we shouldn't have failing builds.
=> Print an error message instead of failing when there is no frontend

src/Ilios/AuthenticationBundle/Service/JsonWebTokenManager.php, tests/AuthenticationBundle/Service/JsonWebTokenManagerTest.php
We don't need this in the token anymore as we're not using it to build
the navigation in the frontend.
Refs ilios/frontend#3778
=> Remove createCIReportInAnySchool from JWT

app/AppKernel.php, app/config/config.yml, app/config/routing.yml, composer.json, composer.lock
Allows us to manually and programmatically check the health of a server.
Humans can check a running server by visiting http://server.com/ilios/health
Machines can get a plain HTTP response (either 200 OK, or 502 Bad Gateway) at http://server.com/ilios/health/http_status_checks
Fixes #2109
There is much room for expansion here we can create groups and check lots of other things, but for now this handles the basics.
=> Add health checks

src/Ilios/ApiBundle/Controller/SchooleventController.php, src/Ilios/ApiBundle/Controller/UsereventController.php, src/Ilios/CoreBundle/Classes/CalendarEvent.php, src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php, src/Ilios/CoreBundle/Entity/Manager/UserManager.php, src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php, src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Traits/CalendarEventRepository.php, tests/CoreBundle/DataLoader/CompetencyData.php, tests/CoreBundle/DataLoader/ObjectiveData.php, tests/CoreBundle/DataLoader/SessionData.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php, tests/IliosApiBundle/Endpoints/SchooleventsTest.php
fixes #2173 
this adds it to both school- and user-events.
each event has now three new attributes - `sessionObjectives`, `courseObjectives` and `competencies`.
- Items in the `sessionObjectives` and `courseObjectives` collections have the same structure - `id`, `title`, `position` and `competenies` (that's the competency ids as lookup-keys)
- items in the `competencies` collection have the following structure: `id`, `title`, and `parent` (parent competency id, which is `NULL` for domains). this list contains all linked competencies and their parent domains.
=> add session/course objectives and related competencies to calendar-events

app/Resources/DoctrineMigrations/Version20180617000000.php, src/Ilios/CoreBundle/Entity/Objective.php, src/Ilios/CoreBundle/Entity/ObjectiveInterface.php, src/Ilios/CoreBundle/EventListener/RemoveOrphanedObjectives.php, src/Ilios/CoreBundle/Resources/config/services.yml, tests/CoreBundle/Entity/ObjectiveTest.php, tests/IliosApiBundle/Endpoints/CourseTest.php, tests/IliosApiBundle/Endpoints/ObjectiveTest.php, tests/IliosApiBundle/Endpoints/ProgramYearTest.php, tests/IliosApiBundle/Endpoints/SessionTest.php
When a ProgramYear, Course, or Session is deleted we also need to clean
up those objective's parents and children so that we don't have a tree
with no links.
Fixes #2178
=> Cleanup orphaned objectives onFlush

src/Ilios/CoreBundle/Entity/Repository/UserRepository.php, src/Ilios/CoreBundle/Traits/CalendarEventRepository.php, tests/IliosApiBundle/Endpoints/SchooleventsTest.php, tests/IliosApiBundle/Endpoints/UsereventTest.php
Anyone with elevated privileges should have access to the materials in
draft sessions and courses. We're already controlling this in the
controllers, but we needed to return a full graph of materials.
Fixes #2186
=> Non-learners get materials from draft events

app/config/config.yml, src/Ilios/ApiBundle/Controller/ProgramYearController.php, src/Ilios/ApiBundle/Resources/config/special-routes.yml, src/Ilios/CoreBundle/Entity/Manager/ProgramYearManager.php, src/Ilios/CoreBundle/Entity/Repository/ProgramYearRepository.php, src/Ilios/CoreBundle/Resources/config/services.yml, tests/CoreBundle/DataLoader/CourseData.php, tests/IliosApiBundle/Endpoints/ProgramYearTest.php
fixes #2192 
this is the reporting query that runs for a given program year objective.
```sql
SELECT p.title AS program_title, py.start_year AS matriculation_year, pyo.title AS program_year_objective,
cmp.title AS competency, c.title AS course_title, c.external_id AS course_shortname, co.title AS mapped_course_objective
FROM program_year py
JOIN program p ON py.program_id = p.program_id
JOIN program_year_x_objective pyxo ON py.program_year_id = pyxo.program_year_id
LEFT JOIN objective pyo ON pyxo.objective_id = pyo.objective_id
LEFT JOIN competency cmp ON pyo.competency_id = cmp.competency_id
LEFT JOIN objective_x_objective oxo ON pyo.objective_id = oxo.parent_objective_id
LEFT JOIN objective co ON oxo.objective_id = co.objective_id
LEFT JOIN course_x_objective cxo ON cxo.objective_id = …
```
=> d/l action for program year objectives mapping.

src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php, tests/CoreBundle/Entity/Manager/CurriculumInventoryReportManagerTest.php
=> correctly calculate event duration if offerings are configured to be counted as one.

src/AppBundle/Controller/IndexController.php, tests/AppBundle/Controller/IndexControllerTest.php
Fixes issue where favicon icons do not load in some browsers because we were sending the wrong content type and an incorrect encoding header.
=> Send the correct headers with PNG files

src/AppBundle/Controller/IndexController.php, src/Ilios/AuthenticationBundle/Service/AuthenticationInterface.php, src/Ilios/AuthenticationBundle/Service/CasAuthentication.php, src/Ilios/AuthenticationBundle/Service/FormAuthentication.php, src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php, src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php, tests/AuthenticationBundle/Service/ShibbolethAuthenticationTest.php
Instead of waiting for the frontend to redirect users who need to be
authenticated by shibboleth we can redirect them as soon as they request
the index.html page. Doing this removes the need for the browser to
render our javascript twice.
Needs:
=> Attempt to sign in users sooner

src/AppBundle/Entity/UserRole.php, src/AppBundle/Entity/UserRoleInterface.php, tests/AppBundle/Entity/UserRoleTest.php
We're no longer using this for authorization so it can just be dropped.
=> Remove deprecated Symfony RoleInterface

.env.dist
These are the defaults we want to make it easy to use. Since we override
most of the default ENV variables and call them ILIOS_* I pulled the
sections out of their flex chunks. I also added all of the local
database overrides that I tend to use myself.
=> Re-organize the .env.dist file

Dockerfile, docker/apache.conf
In symfony4 this changed from web to public so we need to fix up our docker container to match.
=> Fix docker path to webroot

tests/Endpoints/SessionTest.php
Fixed this test to do what it says, update the ILM instead of updating
the instructors as we already have a test for that.
=> Fix Session Timestamp test

public/index.php
Symfony has updated the recipe for this front controller which is good
because the old version without $_ENV didn't work with docker containers
where $_SERVER would sometimes not be populated.
BTW I learned tonight that the weird `?? $VAR ?? $VAR2 ?? 'default'` syntax is called the NULL coalesce operator:
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op
=> Update the front controller to match the recipe

src/Service/Timestamper.php, tests/AbstractEndpointTest.php
By using the time() builtin the ClockMock in our tests can work more
effectively to change the time.
https://symfony.com/blog/new-in-symfony-2-8-clock-mocking-and-time-sensitive-tests#clock-mocking
=> Modify the way we generate update timestamp

.env.dist, .travis.yml, bin/console, public/index.php, src/Monitor/RequiredENV.php
This makes it harder to get into the 'dev' environment, but saves a lot
of potential headaches for users who shouldn't need to know the
difference.
=> Default Ilios to production

bin/setup, composer.json, docs/install.md, docs/update.md
In order to improve documentation and make the experience for users simpler I have added `bin/setup` which handles the tedium of installing and setting up ilios.
This allowed me to remove the `auto-scripts` from composer that cause issues in our docker build and it will allow us to do tests and provide links to setup documentation.
=> Add a setup script

src/Controller/IndexController.php, templates/index/webindex.html.twig
By moving style sheets and defering the loading of scripts it ensures
that our loading indicator is parsed and rendered as quickly as
possible. Otherwise the browser would block rendering while the styles
were fetched and parsed.
=> Re-organize the index.html template to load faster

Dockerfile
This allows for symfony to push assets out with the index.html page
instead of waiting for the browser to find and request them.
=> Enable the http2 module

src/Command/SetSchoolConfigValueCommand.php, tests/Command/SetSchoolConfigValueCommandTest.php
School config values, when saved, must be linked to a school. Our
command was failing to do this.
=> Link config to the correct school

.dockerignore, Dockerfile, docker/ilios-entrypoint
Instead of doing the cache warmup during the build phase this changes our setup to do it during the run phase. This ensure that we have final access to the filesystem as well as any outside services that we need.
Since #2252 removed the cache steps out of the composer scripts this makes our containers much smaller and easier to work with.
=> Warmup cache better in docker builds

config/routes.yaml
Was just missing the /api, but I cleaned up some other issues as well.
Fixes ilios/frontend#4107
=> Fix route for download of competencies

tests/AbstractEndpointTest.php
We're up to date on doctrine/annotations now and can remove this
workaround
=> Remove annotation reset from tests

config/services.yaml, src/Controller/SwaggerDocsController.php
Symfony now gives us the option to use the variable name in services as
a constant injector and bind it in our services definition.
=> Bind common parameters

config/routes.yaml
We were intercepting too many requests which caused the URL /doc to not
redirect to /doc/ as it should have. I also added a redirect to send
users of /docs to /doc/.
=> Improve redirection and slashes for API docs path

src/Controller/SchooleventController.php, src/Controller/UsereventController.php, src/Entity/Manager/SchoolManager.php, src/Entity/Manager/UserManager.php, src/Entity/Repository/SchoolRepository.php, src/Entity/Repository/UserRepository.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php
For both schools and users when we have a session id (as we do in pre / post requisites) this filter allows us to find the right events without needing access to the sessions endpoint to discover the offerings first.
=> Find events by session Id

src/Command/LockingMigrationCommand.php, src/Service/IliosFileSystem.php, tests/Service/IliosFileSystemTest.php
This will allow migrations to be run on multiple instances at once
without actually having any conflicts. The first to run will keep the
lock and any others will wait for it to be released before checking and
finding no new migrations.
=> Create blocking migration command

src/Controller/IndexController.php, src/Service/Config.php, templates/index/webindex.html.twig, tests/Controller/IndexControllerTest.php, tests/Service/ConfigTest.php
Allows applications to be configured to send errors to the centralized
logging service.
=> Add error capture configuration

src/Command/ImportMeshUniverseCommand.php
fixes #2300 
```
$ bin/console ilios:import-mesh-universe --help
Description:
Imports the MeSH universe into Ilios.
Usage:
ilios:import-mesh-universe [options]
ilios:maintenance:import-mesh-universe
Options:
-u, --url=URL         The MeSH descriptors URL.
-p, --path=PATH       The MeSH descriptors file path.
-y, --year=YEAR       The MeSH descriptors publication year. Acceptable values are 2017, 2018.
-h, --help            Display this help message
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi            Force ANSI output
--no-ansi         Disable ANSI output
-n, --no-interaction  Do not ask any interactive question
-e, --env=ENV         The Environment name. [default: "prod"]
--no-debug        Switches off debug mode. …
```
=> show years, not urls in --year option description for ilios:import-mesh-universe command.

config/services.yaml
We added postrequisites and prerequisites in #2292 to the user and school events
and didn't bump the API.
=> Changes to events necessitate an API bump

src/Entity/Term.php, src/Entity/Vocabulary.php, src/Migrations/Version20190201190000.php, tests/AbstractEndpointTest.php, tests/Endpoints/TermTest.php, tests/Endpoints/VocabularyTest.php
Changes the validations and the DB structure to disallow this.
Fixes #2329
=> Don't allow empty term or vocabulary titles

.travis.yml
Start testing against this released version as we're officially
supporting it now.
=> Add PHP 7.3 tests

Dockerfile, docker/ilios-entrypoint
Environmental variables do not survive the su -c -s process and I
couldn't see a way to make that work so instead I reorganized our docker
build a bit and added sudo to use in the entrypoint to clear the cache
as the right user
=> Fixup users and environments in Docker build

azure-pipelines.yml, config/services.yaml, src/Monitor/NoDefaultSecret.php
We provide several default values for this in code and documentation, we
need to check to be sure those aren't being used.
Fixes #1734
=> Add a monitor to check ILIOS_SECRET

config/services.yaml, src/Migrations/Version20190307000000.php
This API bump is happening after a release, any changes saved by users
to objectives would have included a null active status which would put
the DB into a state that probably wasn't intended. Changing this back to
active seems less likely to cause issues as any change to inactive would
have been intentional and repeatable.
=> Correctly bump API and reset objectives

src/Service/IliosFileSystem.php, tests/Service/IliosFileSystemTest.php
The same file can be uploaded many times and it should work, using put
instead of write here allows that to happen.
Fixes ilios/frontend#4421
=> Allow learning materials to be overwritten

src/Classes/LocalCachingFilesystemDecorator.php, tests/Classes/LocalCachingFilesystemDecoratorTest.php
If the remote file system returned false we were caching that, php
turned it into a string and we stored it to return to users.
=> Prevent caching failure responses

config/services.yaml, src/Classes/CalendarEvent.php, src/Traits/CalendarEventRepository.php, tests/Classes/SessionEventTest.php, tests/Classes/UserEventTest.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php
Since students cannot access a session we need a way to get to the
course id without loading the session first.
Needed for https://github.com/ilios/common/pull/650
=> Add course id to events

docker-compose.yml, src/Classes/ElasticSearchBase.php, src/Classes/IndexableCourse.php, src/Command/PopulateIndexCommand.php, src/Entity/DTO/CourseDTO.php, src/Entity/Manager/CourseManager.php, src/Entity/Repository/CourseRepository.php, src/EventListener/IndexEntityChanges.php, src/Service/Index.php, src/Service/Search.php, tests/Command/PopulateIndexCommandTest.php, tests/Service/IndexTest.php
Elastic search has abandoned the concept of types and an index can only
contain one type now (as far as I can tell). Since we can no longer put
sessions and courses together in the same index and the other ways are
too complicated I've denormalized session data into single documents for
each session.
=> Remove types from our search index

src/Entity/Repository/UserRepository.php, src/Service/Index.php, tests/DataLoader/UserData.php, tests/Endpoints/UserTest.php
For both DB and elastic searches the display name needs to be included
for a match.
=> Include display name in user search

config/packages/security.yaml, config/routes.yaml, src/Controller/Search.php, src/Service/PermissionChecker.php, src/Service/Search.php, tests/Controller/SearchControllerTest.php
Created an api at `/experimental_search` that takes a single `q` parameter and searches the curriculum. This is a first pass, the results are poorly ranked as we're not applying as much individual weighting criteria as we should, but it does work and searches. 
The results are returned in a course object with each matching session under the respective course. The fields that were matched appear at the course and session level respectively for badging.
Search Results look like:
```
'courses' => [
[
'id' => 1,
'title' => 'This Course',
'year' => 2019,
'matchedIn' => ['title', 'objectives'],
'bestScore' => 56.777888,
'sessions' => [
[
'id' => 11,
'title' => 'This Session',
'score' => 56.777888,
'matchedIn' => ['description', 'learningMaterials']
],
[															[
'id' => 99,
'title' => …
```
=> Add a search API

src/Controller/Search.php, src/Entity/Repository/CourseRepository.php, src/Service/Index.php, src/Service/Search.php, tests/Controller/SearchControllerTest.php
Using the built in Completions suggester from Elasticsearch as it is the
simplest to implement. It will return matches when the prefix is the
same, but not mid-word matches. This is probably sufficient for our
autocomplete use case.
Incidentally fixed a bug where session title was not being set properly.
=> Add autocomplete suggestions to search

config/services.yaml, src/Classes/ElasticSearchBase.php, src/Service/ElasticSearchFactory.php, src/Service/Index.php, tests/Service/IndexTest.php, tests/Service/SearchTest.php
The new + sign for arrays apparently doesn't do what I thought it did.
Use array_merge instead, it actually works.  Refactored the way
elasticsearch gets passed in so we can actually test the Index service.
=> Index all sessions

src/Service/Index.php, src/Service/Search.php
Adding these makes it much easier to find specific things if you know
this info. Also fixed an issue with returning the course title in the
year field and lowercased the matchedIn fields because it seemed like the right thing to do.
=> Search on year and course and session id

src/Service/Index.php, tests/Service/IndexTest.php
Since we index on course and not on session we need to skip attempting
to index empty courses.
Fixes #2516
=> Fix indexing course with no sessions

azure-pipelines.yml
These clutter up test output and often cause failures that we cannot
control.
=> Silence symfony deprecations in CI

src/Service/Index.php
Elastic search doesn't automatically convert search strings into numbers
when searching fields, since we're going to be sending a query as a
string I've indexed the numerics as keywords which ensures they count as
whole strings and not partial matches.
=> Fix problem with search strings

.dependabot/config.yaml
Symfony always updates everything at the same time, but dependabot
doesn't understand that and opens a dozen individual pull requests.
Instead I'm skipping all symfony package and we'll catch them manually
when a new version is released.
=> Configure Dependabot to ignore all symfony packages

src/Service/Search.php
When array keys are numeric, but not in sequence javascript reads the
result as an object instead of an array.
Fixes #2529
=> Fix search matchedIn responses

.dependabot/config.yaml
Now that we've disabled symfony packages from getting updated on their
own we can re-enable automerging of everything else.
=> Re-enable automerge from dependabot

.dependabot/config.yaml, composer.json, composer.lock
We're not quite ready to make this jump to v7 and it's API changes.
Would like to wait until the AWS service is updated as well to ensure
we're compatible with our most likely runtime.
=> Revert Update to Elastic Search 7

.azure/phpunit-job-template.yaml, Dockerfile, azure-pipelines.yml, composer.json, composer.lock, config/packages/monitor.yaml, docs/ilios_php_version_policy.md, docs/install.md, symfony.lock
With 7.3 supported in major distros we can drop 7.2 now.
Wait to merge until we've made the announcement that the next version is the last to support 7.2
=> Drop support for PHP 7.2

config/routes.yaml, src/Controller/Search.php, src/Service/Index.php, src/Service/PermissionChecker.php, src/Service/Search.php, tests/Controller/SearchControllerTest.php, tests/Service/IndexTest.php
Just like curriculum users can be searched for. Moves everything under
a new `/experimental_search/v1` top level:
`/experimental_search/v1/curriculum`
`/experimental_search/v1/users`
Also adds autocomplete to user search to speed up that in our admin panel.
=> Add user search endpoint

composer.json, composer.lock, tests/Classes/SessionUserTest.php, tests/Controller/DirectoryControllerTest.php, tests/Controller/SearchControllerTest.php, tests/Entity/Manager/CurriculumInventoryReportManagerTest.php, tests/RelationshipVoter/AbstractBase.php, tests/Service/AuthenticationFactoryTest.php, tests/Service/ChangeAlertHandlerTest.php, tests/Service/ConfigTest.php, tests/Service/CurriculumInventory/Export/AggregatorTest.php, tests/Service/CurriculumInventory/ExporterTest.php, tests/Service/DefaultPermissionMatrixTest.php, tests/Service/DirectoryTest.php, tests/Service/FilesystemFactoryTest.php, tests/Service/FormAuthenticationTest.php, tests/Service/IliosFileSystemTest.php, tests/Service/IndexTest.php, tests/Service/JsonWebTokenManagerTest.php, tests/Service/LdapAuthenticationTest.php, tests/Service/LdapManagerTest.php, tests/Service/LoggerQueueTest.php, tests/Service/PermissionCheckerTest.php, tests/Service/SearchTest.php, tests/Service/ShibbolethAuthenticationTest.php
Unlocking this dependency to get back to regular updates.
Hoping a dependency update has fixed this issue, otherwise this PR will be a reminder to investigate.
=> Switch mockery back to stable version

src/Monitor/IliosFileSystem.php
This slipped through a few refactors of this filesystem and was no
longer working.
=> Use the IliosFileSystem when checking the filesystem

src/Monitor/PhpConfiguration.php
Gives enough time for complicated things like curriculum inventory load
to work. We're careful in our code not to run wild with execution time
for other requests so this seems like a safe default to apply.
Fixes #2259
=> Add max execution time health check

composer.json, composer.lock, src/Controller/IndexController.php, symfony.lock
If we send this early redirect to search crawlers they will index the
SSO landing page instead of the site at that address.  Even though it is
a minimal set of information at this non-authenticated point it's still
worth showing to crawlers so they can read meta tags and improve SEO.
=> Stop Redirecting Search Crawlers

templates/email/teachingreminder.text.twig, tests/Command/SendTeachingRemindersCommandTest.php
=> treat trailing S in school name correctly.

src/Command/ListConfigValuesCommand.php, tests/Command/ListConfigValuesCommandTest.php
Without this change it's impossible to see exactly why the DB isn't
working. The exception prevents the other values from being written.
This way a missing DB configuration param is visible.
=> List config values when database is not configured

src/Service/Index.php, src/Service/Search.php
Words like interprofessional were not getting returned in the search
because we have a maximum ngram size of 15. This change ensures that
exact word long matches will still work along with partial string
shorter ones.
Fixes #2591
=> Re-index search to match long words

config/services.yaml
These got pulled accidentally and without them our service won't listen
for changes and update the index.
Fixes #2594
=> Listen for events again

docker-compose.yml
This makes it easier to file up a unified environment, but still run the
local webserver so that debugging is possible without complicated
configuration.
=> Expose mysql when running in docker

docker-compose.yml
We need to discover if we're going over this hard limit in development
instead of waiting for production.
Fixes #2604
=> Set elasticsearch option to match AWS

src/Classes/IndexableCourse.php, src/Classes/IndexableSession.php, src/Entity/Repository/CourseRepository.php, src/Service/Index.php, src/Service/Search.php
Instead of just the first ID this indexes all IDs, names, and
annotations attached to each course and session.
Fixes #2610
=> Index more of the mesh descriptor

src/RelationshipVoter/CourseLearningMaterial.php, src/RelationshipVoter/ElevatedPermissionsViewDTOVoter.php, src/RelationshipVoter/GreenlightViewDTOVoter.php, src/RelationshipVoter/LearningMaterial.php, src/RelationshipVoter/SessionLearningMaterial.php, tests/RelationshipVoter/AbstractBase.php, tests/RelationshipVoter/CourseLearningMaterialTest.php, tests/RelationshipVoter/ElevatedPermissionsViewDTOVoterTest.php, tests/RelationshipVoter/GreenlightViewDtoVoterTest.php, tests/RelationshipVoter/LearningMaterialTest.php, tests/RelationshipVoter/SessionLearningMaterialTest.php
refs #2599 
this is the poor man's implementation - if you're only a learner then you cannot get to this data.
not a problem for students right now, since they don't hit up these endpoints on the dashboard, they get their LMs via user/school events which use a different filtering/blanking mechanism in order to restrict access.
... _however!_ this will come back to haunt us when we ever get around to implementing a "course overview" for learners (see lti convo with stanford). at that point, we'll have to check the current user's relationship with the given user. for example: 
> is this user in a learner group that is associated with a session that belongs to a course that this learning material is attached to? if so, they can see it.
rinse/repeat for similar relationships …
=> only users who perform non-learner functions can view learning materials

src/Entity/Course.php, src/Entity/CourseInterface.php, src/Entity/LearningMaterial.php, src/Entity/LearningMaterialInterface.php, src/Entity/MeshDescriptor.php, src/Entity/MeshDescriptorInterface.php, src/Entity/Objective.php, src/Entity/ObjectiveInterface.php, src/Entity/School.php, src/Entity/SchoolInterface.php, src/Entity/Session.php, src/Entity/SessionInterface.php, src/Entity/Term.php, src/Entity/TermInterface.php, src/Entity/Vocabulary.php, src/Entity/VocabularyInterface.php, src/EventListener/IndexEntityChanges.php, src/Traits/IndexableCoursesEntityInterface.php, tests/Endpoints/VocabularyTest.php, tests/Entity/CourseTest.php, tests/Entity/LearningMaterialTest.php, tests/Entity/MeshDescriptorTest.php, tests/Entity/ObjectiveTest.php, tests/Entity/SchoolTest.php, tests/Entity/SessionTest.php, tests/Entity/TermTest.php
We were only indexing changes to the course object directly, but there
are many other places where the index needs to be modified.
Fixes #2606
=> Re-index when anything indexable is updated

src/Service/Search.php
In Elasticsearch 7 types are deprecated in favor of a single _doc type,
this transition was made for indexing mesh, but missed in the search
code.
Fixes #2608
=> Search for mesh using the correct type

src/Entity/Manager/MeshDescriptorManager.php, src/Entity/Manager/UserManager.php
These were a way to get at elastic search without using the API, but the
sorting on top of elastic doesn't work for users so we need to force all
elastic queries to go through the right endpoint so the UI can handle
them.
Fixes ilios/frontend#4788
=> Remove search passthroughs

src/Controller/IcsController.php, tests/Controller/IcsControllerTest.php, tests/DataLoader/SessionData.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php, tests/Fixture/LoadSessionData.php
Prerequisites don't need to be part of the feed as they are available
from the event details for the event.
Fixes #2635
=> Ignore Prerequisites in ICS feed

config/packages/security.yaml, config/routes.yaml
In order to prevent conflicts with the UI and as it *is* part of the API
I've moved search into the /api path.
Fixes #2648
=> Renamespace search API

src/Service/Search.php
When courses and session tags have array keys that are not consecutive
then the final JSON ends up being an object instead of an array which
can't be parsed by the frontend.
Fixes #2649
=> Fix return tags on search

src/Classes/IndexableCourse.php, src/Classes/IndexableSession.php
If these aren't consecutively zero indexed then JSON converts them into an
object which is not what search is expecting. Re-indexing the values
ensures we're getting at array.
Fixes #2655
=> Ensure arrays are indexed in order

src/Service/CurriculumInventory/VerificationPreviewBuilder.php, tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php
this came up while implementing the UI in the frontend.
without spacing:
with proper spacing, cell content wraps better:
refs https://github.com/ilios/frontend/pull/4825
=> better spacing in method names.

src/Controller/DownloadController.php, src/Service/Config.php, tests/Controller/DownloadControllerTest.php, tests/Fixture/LoadApplicationConfigData.php
When the demo site (or a staging server) is scanned all of the learning
materials links throw missing 404 errors because the files are not
synced up. Instead they can be disabled by this configuration option to
return a simple string instead.
=> Create a config option to disable learning materials

config/packages/messenger.yaml, docs/install.md, docs/update.md
Having this enabled causes conflicts when we run multiple workers to
consume the messages. Instead I've added the setup instructions to the
installation guide.
=> Disable auto_setup for messenger

src/EventListener/IndexEntityChanges.php
The message bus can only handle 50 messages at the same time so we need
to split this up here. We could also do this on the bus itself, but that
is more complicated.
Fixes #2666
=> Split up course indexing into chunks

config/packages/messenger.yaml
New features in symfony v4.3.5 make auto_setup useful and improve performance.
I've also enabled some two doctrine features which make it less likely
we'll hold onto lots of open connections.
=> Improve messenger configuration

config/packages/exercise_html_purifier.yaml, tests/Endpoints/ObjectiveTest.php
This non-semantic presentation only HTML element is an a11y
violation. Let's prevent our users from making that mistake.
This reverts #1090 as the `<u>` tag is no longer included in our WYSIWYG editor we can safely remove it here as well. The only place it can still being used is in rolled over items and stripping these out is an improvement.
=> Stop allowing <u> in input

config/packages/messenger.yaml, config/services.yaml
The performance enhancing middleware for doctrine doesn't make sense
when it is called during synchronous dispatch operations and it breaks
the app as it closes the default open connection to the database and
kills all running transactions. Instead I've applied these only to index
handling which is what gets run on read.
=> Split messages into two busses

src/Classes/LocalCachingFilesystemDecorator.php, src/Service/FilesystemFactory.php, src/Service/IliosFileSystem.php, src/Service/NonCachingIliosFileSystem.php, tests/Service/IliosFileSystemTest.php, tests/Service/NonCachingIliosFileSystemTest.php
We need this when indexing learning materials, it allows a single file
retrieval to be made without storing that file in the cache.
refs #2672
=> Option to disable caching when fetching files

src/EventListener/SentryCaptureListener.php
We get lots of these and they are all crawlers or bad actors. We should
just ignore them.
=> Stop reporting 404 errors to sentry

src/Monitor/NoDefaultSecret.php
the previous message had a typo, `do` instead of `to`. 
this new one is more to the point, imo.
=> provides a better success message.

src/Service/SwaggerDocBuilder.php
These variables are already registered for injection and is a better
path than injecting the kernel and reading properties off of it.
=> Inject properties instead of the kernel

tests/Service/CourseRolloverTest.php
Offering test starts failing at the end of the year because something is
fishy about calculating the weeks. This fix from the course section
above fixes that issue.
=> Copy end of year date time test from course setEndDate

composer.json, composer.lock, src/Controller/ExceptionController.php, symfony.lock, tests/Classes/AcademicYearTest.php, tests/Classes/LocalCachingFilesystemDecoratorTest.php, tests/Classes/PermissionMatrixTest.php, tests/Classes/SchoolEventTest.php, tests/Classes/UserEventTest.php, tests/Classes/UserMaterialTest.php, tests/Service/MeshDescriptorSetTransmogrifierTest.php, tests/TestCase.php
This is the last release of the 4.x line, after clearing deprecations we can move to v5.
I did this in two steps the first was to modify composer.json to require `@stable` versions of symfony packages. That composer update made these changes:
| Production Changes           | From    | To      | Compare                                                                |
|------------------------------|---------|---------|------------------------------------------------------------------------|
| aws/aws-sdk-php              | 3.128.0 | 3.129.0 | https://github.com/aws/aws-sdk-php/compare/3.128.0...3.129.0           |
| doctrine/persistence         | 1.2.0   | 1.3.3   | https://github.com/doctrine/persistence/compare/1.2.0...1.3.3          |
| exercise/htmlpurifier-bundle | V2.0.4  | v2.0.5  | …
=> Update Symfony to v4.4

tests/Endpoints/CourseTest.php, tests/Service/CourseRolloverTest.php
Adding 54 weeks to a week in 2020 ends up with a different week in 2021
due to the leap year or some other madness. Using ISO dates fixes this
issue.
=> Fix date calculate in tests

.gitignore, composer.json, composer.lock, config/bundles.php, symfony.lock
This is deprecated in symfony 4.4 and will be removed in 5.0.
Details at: https://symfony.com/blog/new-in-symfony-4-4-misc-improvements-part-3#deprecated-webserverbundle
=> Remove Webserver Bundle

.env, composer.json, composer.lock, config/packages/messenger.yaml, config/packages/prod/monolog.yaml, docker-compose.yml, docker/elasticsearch-dev/Dockerfile, src/Classes/ElasticSearchBase.php, src/Classes/IndexableCourse.php, src/Classes/IndexableSession.php, src/Command/PopulateIndexCommand.php, src/Entity/CourseLearningMaterial.php, src/Entity/CourseLearningMaterialInterface.php, src/Entity/DTO/LearningMaterialDTO.php, src/Entity/Manager/LearningMaterialManager.php, src/Entity/Repository/CourseRepository.php, src/Entity/Repository/LearningMaterialRepository.php, src/Entity/SessionLearningMaterial.php, src/Entity/SessionLearningMaterialInterface.php, src/EventListener/IndexEntityChanges.php, src/Message/LearningMaterialIndexRequest.php, src/MessageHandler/LearningMaterialIndexHandler.php, src/Service/IliosFileSystem.php, src/Service/Index.php, src/Service/LearningMaterialDecoratorFactory.php, src/Service/Search.php, symfony.lock, tests/Entity/DTO/LearningMaterialDTOTest.php, tests/Service/IndexTest.php
This creates a new index for learning materials and then uses the elasticsearch attachment plugin to parse binary files and insert their test into that index. We then scan this index when indexing courses and add the data to the curriculum index to make it searchable.
Wip:
Fixes #2669
=> Index the contents of learning materials

src/Entity/Alert.php, src/Entity/AuditLog.php, src/Entity/Authentication.php, src/Entity/Competency.php, src/Entity/Course.php, src/Entity/CourseLearningMaterial.php, src/Entity/CurriculumInventoryAcademicLevel.php, src/Entity/CurriculumInventoryReport.php, src/Entity/CurriculumInventorySequence.php, src/Entity/CurriculumInventorySequenceBlock.php, src/Entity/IlmSession.php, src/Entity/LearnerGroup.php, src/Entity/LearningMaterial.php, src/Entity/MeshConcept.php, src/Entity/MeshDescriptor.php, src/Entity/MeshTerm.php, src/Entity/Offering.php, src/Entity/Program.php, src/Entity/Report.php, src/Entity/School.php, src/Entity/Session.php, src/Entity/SessionDescription.php, src/Entity/SessionLearningMaterial.php, src/Entity/Term.php, src/Entity/User.php
Fixing two deprecations in our validations.
1) DateTime is going away
2) The way Length works with empty strings is changing in Symfony 5
=> Clear validation deprecations

src/Controller/CoursesController.php, src/Controller/CurriculumInventoryReportController.php
Passing an array of attributes to this method was deprecated in Symfony
4.4. We weren't actually using that feature though, just using an array
as a container for a single attribute.
=> Pass single attribute to authorization check

config/packages/security.yaml, src/Command/AddUserCommand.php, src/Command/ChangePasswordCommand.php, src/Command/InstallFirstUserCommand.php, src/Controller/AuthenticationController.php, src/Entity/Authentication.php, src/Entity/AuthenticationInterface.php, src/Form/Encoder.php, src/Migrations/Version20200115050155.php, src/Service/FormAuthentication.php, tests/Command/AddUserCommandTest.php, tests/Command/ChangePasswordCommandTest.php, tests/Command/InstallFirstUserCommandTest.php, tests/Controller/AuthControllerTest.php, tests/Fixture/LoadAuthenticationData.php, tests/Service/FormAuthenticationTest.php
In symfony 4.3 a [new auto encoder configuration](https://symfony.com/blog/new-in-symfony-4-4-password-migrations) was introduced which will
use the best hash configuration available at the time. In Symfony 4.4 it gained the
ability to migrate users into the new hash algorithm each time they
login.
As any account currently using the bcrypt hash will get updated to a brand
new configuration I've also modified the DB column from password_bcrypt
to password_hash and removed length checking to ensure there is room for
any future hash output.
=> Use symfony auto migrating password hash

config/packages/dev/monolog.yaml, config/packages/prod/monolog.yaml, config/packages/test/monolog.yaml
These log files can get huge and fill up the disk, switch off this
logging in production, but specifically pull it out in dev/test for
examination there.
=> Don't log deprecations in production

tests/Controller/UploadControllerTest.php, tests/Endpoints/LearningMaterialTest.php
Passing the filesize into a an UploadFile is deprecated and will be
removed in symfony 5.0
=> Remove deprecated filesize parameter

src/EventListener/SentryCaptureListener.php
This will break in symfony 5.0, it has an easy replacement though.
=> Remove call to deprecated method

tests/Controller/AuthControllerTest.php, tests/Controller/DownloadControllerTest.php, tests/Controller/ErrorControllerTest.php, tests/Controller/UploadControllerTest.php, tests/Endpoints/CurrentSessionTest.php
This is deprecated in SF5. For most of these we weren't calling
`WebTestCase::teardown()` which cleans up the kernel for the next test.
=> Don't load the test kernel twice

azure-pipelines.yml, src/Kernel.php, tests/Endpoints/AamcPcrsTest.php
Prevents issues where the container already exists and is not
re-created. Specifically looking at the Inflector::rules we have in
src/Kernel.php to ensure they're run every time.
=> Ensure setup is always run

src/Controller/CurriculumInventoryDownloadController.php
Setting secure to null allows symfony to detect if HTTPS is running
and set the cookie to https only. The same site policy of lax is the new
default in most browsers, it allows this cookie to be used between
origins (as is the case when the API and frontend are on different
domains.)
=> Add explicit cookie properties

src/Monitor/Composer.php, src/Monitor/Frontend.php, src/Monitor/IliosFileSystem.php, src/Monitor/NoDefaultSecret.php, src/Monitor/PhpConfiguration.php, src/Monitor/RequiredENV.php, src/Monitor/Timezone.php
Zend has transferred the framework to the linux foundation and it is
called Laminas now. Through the magic of composer and great upstream
packages this was mostly transparent to us, but we are interfacing with
this directly in our custom Monitor classes.
Refs #2727
=> Replace Zend with Laminas

tests/Endpoints/OfferingTest.php
It's sort of possible that this value isn't actually getting changed
here and maybe that's why the test fails sometimes.
=> Attempt to fix flaky test

src/Entity/Manager/ApplicationConfigManager.php, src/Entity/Repository/ApplicationConfigRepository.php
Each request loads 9-15 of these and each load was making a DB query to
get the value. Loading them all at once saves about 100ms on each
request which is a substantial speed improvement over several
requests.
=> Add some light caching of database configuration values

.github/workflows/ci.yml
Not sure if this is causing our flaky tests, but it's something to try.
It wasn't speeding us up that much as the requests to Github itself
seems to run super fast anyway.
=> Remove composer cache

.github/workflows/ci.yml
Reverts ilios/ilios#2798
Adding back in this cache as it doesn't fix flaky tests and adds about 20 seconds to each test run.
=> Revert "Remove composer cache"

src/Service/JsonWebTokenManager.php, tests/Service/JsonWebTokenManagerTest.php
createFromFormat expects only a string, we're passing in timestamps here
which may come through the token as ints so we need to cast them first
to ensure they're correct.
Fixes #2801
=> Cast token values to string before converting them

composer.json, composer.lock, phpcs.xml.dist, src/EventListener/LogEntityChanges.php, src/Migrations/Version20150826130000.php, src/Migrations/Version20150916173024.php, src/Migrations/Version20160615223611.php, src/Service/Directory.php, symfony.lock, tests/Service/IliosFileSystemTest.php, tests/Service/NonCachingIliosFileSystemTest.php
Checks for things that are deprecated or removed in a released PHP version, in this case it cause places where the arguments were provided in the wrong order for `implode`.
=> Add PHP Compatibility Code Sniffer

src/Controller/IndexController.php
This seems to only come from IE8, but sometimes we get a stray `/`
request which was falling through our current set up checks and causing
an error.
Fixes #2810 which has more debug information attached in the Sentry error. I wasn't able to reproduce this error in browserstack with Windows XP / IE8, so I'm only guessing at the solution here.
=> Handle root file requests better

src/Classes/ElasticSearchBase.php
When the search index doesn't exist, or when the data being deleted
doesn't exist then Elasticsearch is throwing an exception. We don't care
if we're deleting something that doesn't exist, it should just be
removed.
Fixes #2813
=> Delete when index is missing data

.github/workflows/coverage.yml, tests/Classes/PermissionMatrixTest.php, tests/Classes/SchoolEventTest.php, tests/Classes/SessionUserTest.php, tests/Classes/UserEventTest.php, tests/Classes/UserMaterialTest.php, tests/Command/ExportMeshUniverseCommandTest.php, tests/Command/ImportMeshUniverseCommandTest.php, tests/Entity/ApplicationConfigTest.php, tests/Entity/SchoolConfigTest.php, tests/RelationshipVoter/ElevatedPermissionsViewDTOVoterTest.php, tests/RelationshipVoter/GreenlightViewDtoVoterTest.php, tests/RelationshipVoter/LearnerGroupDTOVoterTest.php, tests/RelationshipVoter/ReportDTOVoterTest.php, tests/Service/ChangeAlertHandlerTest.php, tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php, tests/Service/DefaultPermissionMatrixTest.php, tests/Service/MeshDescriptorSetTransmogrifierTest.php, tests/Service/PermissionCheckerTest.php, tests/Service/ReportRolloverTest.php
PHPUnit doesn't accept anything but a fully qualified name here, it does
provide the @coversDefaultClass annotation which avoids repeating the
name endlessly in tests.
=> Fix @covers annotations

config/bootstrap.php, src/Kernel.php
Each time the kernel is created we were re-adding new rules to the
static inflector instance. In a test process where the kernel is created thousands of
times we're adding thousands of items which eventually overloads PHPs
regex parser and causes errors.
Instead of setting this when booting the kernel moving it to the
bootstrap file does the same work, but only once.
This is a fix for [code coverage failing](https://github.com/ilios/ilios/runs/473902951?check_suite_focus=true#step:5:118)
=> Setup the inflector in the bootstrap file

.dependabot/config.yaml
This will update the workflows we have with actions dependencies when
those dependencies are updated.
I have no idea if this is going to work, seems to be undocumented, but in the source code since December for dependabot. I think we'll just have to merge and find out.
=> Add dependency management for action versions

.dependabot/config.yaml
The bot knows where to look, just give it the root directory.
Fixes #2824
=> Fix path for dependabot

src/Controller/ProgramYearController.php
We can't strip_tags on null it causes a strict type error.
Fixes #2826 
Refs #2759
=> Protect against empty objectives

src/Command/SendTeachingRemindersCommand.php, src/Entity/Manager/OfferingManager.php, src/Entity/Manager/SchoolManager.php, src/Entity/Repository/OfferingRepository.php, src/Entity/Repository/SchoolRepository.php, tests/Command/SendTeachingRemindersCommandTest.php, tests/Entity/Manager/OfferingManagerTest.php
Added a `--schools 1,2,4` option to the command that will allow us to split up reminder jobs so that each school can use their own outgoing email address and subject for the teaching reminder emails along with a school specific template for the content.
Fixes #2168
=> Added option to specifiy schools in teaching reminders

src/Controller/LearningMaterialController.php, src/Controller/UploadController.php, src/RelationshipVoter/IliosFileSystem.php, src/Service/IliosFileSystem.php, src/Service/TemporaryFileSystem.php, tests/Service/IliosFileSystemTest.php
Learning materials are uploaded into a temporary file system on whatever
server the user happens to hit. On distributed systems this makes it a
random chance of catching the system which contains the file when you
want to save it.
This change stores these uploaded files on the official FS (S3, shared
drive) which is already setup to be shared among machines. Thus ensuring
that tmp files are available when users want to attach them to a
learning material.
=> Store uploaded files in the shared file system

src/Migrations/Version20200330062405.php
No UI exists to deactivate objectives currently, but they were
defaulting to inactive when created. This was a mistake which can best
be fixed by re-activating any objectives that are currently inactive.
=> Re-activate all objectives

src/Controller/IndexController.php, templates/index/webindex.html.twig
Split up all of the link assets so that each one gets only the
attributes it needs. For stylesheets including an empty sizes attributes
causes safari to fail to load CSS at all. Preloads for fonts were not
working because they were missing the as and crossorigin attributes
which are required.
=> Improve asset loading

.gitignore
Some cruft has built up here, many of these things are now ignored and
managed by symfony flex recipes, the rest we're not using any more.
=> Trim down .gitignore file

public/.htaccess
This halves our network traffic for JSON API data and since it is built
into the browser and very fast will make Ilios faster for all users.
Wip:
=> Configure apache to compress our API responses

src/Service/IliosFileSystem.php
When this fails with false it throws an exception before that boolean is
an invalid return type. Convert it to an exception instead.
Fixes #2873
Fixes #2870
=> Add type checking to return value

docker-compose.yml, src/Command/UpdateFrontendCommand.php
Missing this second step in the warmup command means that the frontend
wasn't actually installed.
I also added back in a commented out section for docker-composer.yaml
making it a bit easier to test things like this when needed.
=> Fix frontend install in cache warmup

.github/workflows/update-dependenies.yaml
We have dependabot turned off for symfony packages to avoid creating 20
PRs when only one is needed. This will ensure that we catch those
updated every week.
=> Auto Update Dependencies

composer.json, composer.lock, src/Service/Index/LearningMaterials.php, symfony.lock
The fpdf library is abandoned so we can't continue using it to split up
large PDFs any more. Instead we'll just skip indexing like other file
types when they are too large.
=> Stop splitting PDFs for indexing

src/Service/ApiRequestParser.php, tests/AbstractEndpointTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/MeshDescriptorTest.php, tests/Endpoints/UserTest.php, tests/GetEndpointTestable.php
These are expected to be ints or null so when they are sent in the
request we need to cast them from strings.
Fixes #2910
=> Fix limit and offset type errors

src/Controller/API/MeshDescriptors.php, src/Entity/Manager/MeshDescriptorManager.php, src/Entity/Repository/MeshDescriptorRepository.php, tests/AbstractEndpointTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/MeshDescriptorTest.php, tests/Endpoints/UserTest.php, tests/GetEndpointTestable.php
This was returning entities which aren't encodable into JSON api format.
Return DTOs instead and add tests for all the other endpoints that take
a q.
Fixes #2912
=> Fix MeshDescriptor JSON API By Query endpoint

src/Controller/API/Courses.php
The check if this is a number doesn't work with a URL so there is no
route to PUT a course. Removing the check fixes that issue.
Fixes #2915
=> Fix course PUT route

src/EventListener/IndexEntityChanges.php
Use the correct index and import the message class we're using. This got missed in the refactor because this is still commented out for AWS compatibliity.
=> Fix LM index

src/Command/ListConfigValuesCommand.php
Makes it much easier to see what is going into the config if we can see the ENVs that override everything else.
=> List ENV values when listing config values

src/Service/Index/LearningMaterials.php
If we don't specify this it ends up being 1 shared and 1 replica, we
don't really need the replica (or at least we don't know yet if we do)
so it should be disabled for now.
=> Remove the default LM index replica

public/.htaccess, src/Controller/IndexController.php
Removing the leading slash from our links was causing visitors to
/courses/742 to download the file /courses/742/manifest.webmanifest
which would then return the index page and fail. I wasn't able to
determine the purpose of removing that slash and after removing it all
paths appear to be correct.
I also ensured that the .webmanifest file would be served compressed
correctly.
Found and correct apache sending a Content-Language: br/gz header when
those files were served. Since our static assets are never going to be
in a different language removing those fixed the issue.
=> Serve web app manifest correctly

src/Service/ApiResponseBuilder.php, tests/AbstractEndpointTest.php, tests/Endpoints/CourseTest.php, tests/Service/ApiResponseBuilderTest.php
`array_merge` only takes the top key and discards everything else, for our deeply nested include trees we need to merge the entire array.
For example `cohorts.programYear.program,cohorts.programYear.programYearObjectives.objective` was returning
```php
[
'cohorts' => [
'programYear' => [
'programYearObjectives' => [
'objective' => []
]
],
]
```
instead of 
```php
[
'cohorts' => [
'programYear' => [
'programs' => [],
'programYearObjectives' => [
'objective' => []
]
],
]
```
As the second level `programYear` was overwriting the first. Thankfully PHP has `array_merge_recursive` which does exactly what we need!
Added a test to the course endpoint as well for the entire integration chain and made it re-usable figuring we'd have more of these some day.
=> Fix nested includes

src/Classes/JsonApiData.php, src/Service/EndpointResponseNamer.php, src/Service/JsonApiDataShaper.php, tests/AbstractEndpointTest.php, tests/Endpoints/CourseTest.php
When the same data was side loaded twice two copies were being sent to the client. For example `course/1?include=terms.vocabulary,sessions.terms.vocabulary` would include each vocabulary twice and any term that was attached to both the session and the course twice. In the case of loading all of the sessions for a large course this was as much as 500kb of extra data for the client to parse and then ignore.
This change makes the data more aware of itself as it is built allowing for some [significant optimization](https://blackfire.io/profiles/compare/0d91af83-e298-4b3a-9b33-f988be5065bb/graph) as less DB queries are performed and less memory is used making requests 20% faster.
=> Only include side loaded data once

src/Service/CurriculumInventory/Export/XmlPrinter.php
i found this during click testing. 
side note: this area of the application is almost void of test coverage, let's add some whenever we get the time.
=> don't break export if CI report description is NULL

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/future-php.yml, Dockerfile, composer.json, composer.lock, config/packages/monitor.yaml, docs/ilios_php_version_policy.md, docs/install.md, symfony.lock
In alignment with our PHP support policy we're dropping PHP 7.3 and
moving the minimum version to 7.4.
| Production Changes              | From    | To      | Compare                                                               |
|---------------------------------|---------|---------|-----------------------------------------------------------------------|
| aws/aws-sdk-php                 | 3.145.0 | 3.145.2 | [...](https://github.com/aws/aws-sdk-php/compare/3.145.0...3.145.2)   |
| doctrine/cache                  | 1.10.1  | 1.10.2  | [...](https://github.com/doctrine/cache/compare/1.10.1...1.10.2)      |
| doctrine/collections            | 1.6.5   | 1.6.6   | [...](https://github.com/doctrine/collections/compare/1.6.5...1.6.6)  |
| ocramius/proxy-manager          | 2.2.3   | 2.7.1   | …
=> Drop support for PHP 7.3

src/Traits/CalendarEventRepository.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php, tests/Endpoints/UsermaterialsTest.php
When an instructor has a display name we need to send it instead of a
first/last combo.
Fixes #2966
=> Use display name for events

src/Controller/API/Authentications.php, tests/DataLoader/AuthenticationData.php, tests/Endpoints/AuthenticationTest.php
We were double parsing the request for JSON:API data and the second time
the password wasn't filtered out as it is supposed to be. This wasn't
caught in tests because passwords were being removed before being sent
as they aren't public properties.
=> Fix saving records with a password

config/services.yaml, src/Classes/JsonApiData.php, src/Controller/API/CurriculumInventoryReports.php, src/Controller/API/LearningMaterials.php, src/Entity/DTO/CurriculumInventoryReportDTO.php, src/Normalizer/FactoryNormalizer.php, src/Service/CurriculumInventoryReportDecoratorFactory.php, src/Service/JsonApiDataShaper.php, src/Service/SerializerFactory.php, tests/AbstractEndpointTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Fixture/LoadLearningMaterialData.php
We were doing this work in the controller, but that doesn't account for side loaded materials. In order to ensure that all materials are decorated we need to do this work in the serializer instead.
The FactoryNormalizer is built to handle any of our data which has a factory and to transform it and then pass the result back into the serializer to continue to be processed.
Then instead of relying on JsonApiDTONormalizer directly in the JsonApiData shaping process we use the full serializer chain which ensures that side loaded data also passes through the FactoryNormalizer before landing in the JsonApiDTONormalizer.
Fixes #2991
=> Handle LM decoration during serialization

src/Classes/SchoolEvent.php, src/Classes/SessionUser.php, src/Classes/SessionUserInterface.php, src/Controller/SchooleventController.php, src/Entity/Manager/UserManager.php, src/Entity/Repository/UserRepository.php, tests/DataLoader/UserData.php, tests/Endpoints/SchooleventsTest.php
Instead of blanking all materials for everyone this checks the
permissions of a user first. Students who are in the session as well as
student advisors attached to the session or course will now be able to
access all non-draft time released materials when viewing an event
through the school calendar.
Refs ilios/frontend#5102
=> Grant student advisors access to learning materials

src/Entity/LearningMaterial.php, src/Migrations/Version20200728222336.php, tests/Endpoints/LearningMaterialTest.php
We've been allowing an empty string here which was auto created when we
ran NULL through our HTML purifier. Since we're not running null through
the purifier anymore we should allow it as a value for description.
Fixes #3003
=> Allow LM description to be null

src/Controller/API/CurriculumInventoryReports.php
fixes #3002 
our FactoryNormalizer is not jiving with this non-standard payload, so just JSON encode it instead.
=> do not use serializer, just json-encode tables data.

config/swagger/paths/report.yml
While we still need this for the reports UI on the frontend it will be
removed when we refactor and re-imagine that reporting. At that point
this API will be removed as well without a major version bump, it should
be considered removed with the API v3 release.
=> Mark reports API as private

src/Entity/Repository/AuthenticationRepository.php
We were incorrectly rejecting users from logging in when their
username partially matched another user. Example demo123 could log in,
but demo1 could not. The same case insensitivity can be had through a
query expression and avoid this issue.
=> Fix error with authentication username

config/swagger/definitions/CalendarEvent.yml, src/Classes/CalendarEvent.php
This hasn't been populated in a long time and has been marked as
deprecated.
=> Remove deprecated eventClass from CalendarEvent

config/services.yaml
We no longer use this to route requests, they all go to their own
controller now.
=> Remove hardwired list of valid API endpoints

config/swagger/paths/courseobjective.yml, config/swagger/paths/sessionobjective.yml
This matches the other endpoints in the docs by capitalizing the name of
the route.
=> Capitalize API doc tag

Dockerfile
It is now recommended to use the LABEL directive for this purpose.
=> Replace deprecated MAINTAINER instruction in Dockerfile

.github/workflows/ci.yml, .github/workflows/deploy-latest.yml, Dockerfile, docker-compose.yml, docker/fetch-demo-database.sh, docker/ilios-mysql.cnf
Moves both the ilios-mysql and ilios-mysql-demo servers from https://github.com/ilios/docker to this repo so their are built and tagged with the app.
=> Add MySQL as a build stage

Dockerfile, docker-compose.yml
Our php-apache container was missing some crucial modules. I also added
a commented out section to our docker compose config to use this
container.
=> Enable required apache modules

Dockerfile
These aren't included in the other containers since they're specifically
for apache. They're, for sure, needed here though!
=> Copy the necessary htaccess files to the apache containers

.github/workflows/deploy-tag.yml
There is no leading slash on the GITHUB_REF tag.  Also added the
deploying tags to the action name for clarity.
=> Fix regex for extracting tags

phpunit.xml.dist
These can't really be covered by unit tests, we have specific
integrations tests specifically for migrating the DB.
=> Exclude Migrations from Code Coverage Stats

.github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml, Dockerfile, docker-compose.yml, docker/docker-compose-everything.yml, docker/elasticsearch-dev/Dockerfile
We primarily need this for development, but it is a useful indication of
the required plugins that are required in an elasticsearch service
offering.
=> Build and deploy an elasticsearch container

src/Controller/API/LearningMaterials.php, tests/Endpoints/LearningMaterialTest.php
We already had error checking in place for this, unfortuantly after
moving to strict mode the createFile method was throwing an exception
before we could get to it. Sometimes LMs are uploaded twice and the
second time the file doesn't exist anymore.
Fixes #3055
=> Deal with bad file hashes correctly

src/Service/CasAuthentication.php
Even if the ilios instance isn't forcing SSL for all connections we
should require it for the CAS service. This ensures that even when
running behind an SSL terminating load balancer the CAS ticket won't be
exposed in the redirect and that there will be a match with the service
URL on the CAS server.
=> Force SSL for CAS redirect

src/Classes/CalendarEvent.php, tests/Endpoints/UsereventTest.php
This isn't a bool, the only reason tests were passing is because
apparently assertEquals in PHPUnit thinks 2 and true are the same... PHP ¯\\_(ツ)_/¯
Fixes #3104
=> Correctly normalize calendar event session

.github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml
This is an improvement over the github packages as they can be made
publicly available. We still recommend and document the docker
registry, but this is out backup and may be our default in the future.
=> Deploy to new github registry

.github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml
The GITHUB_TOKEN for the github user doesn't work with the new packages
repository.
=> Use zorgbort token to deploy github packages

docker/nginx.conf.template
This should allow our PHP-FPM process to correctly interpret the
original request state through an SSL terminating load balancer or other
proxy.
=> Forward proxy headers from nginx

src/EventListener/SentryCaptureListener.php
If a user is authenticated we can add their ID to our logs and possibly
determine the source of some errors more clearly.
=> Add userId to sentry errors

src/EventListener/SentryCaptureListener.php
There are some cases where the user from $token->getUser() is actually a
string and not a SessionUserInterface, we need to check for that before
attempting to access it.
Fixes #3149
=> Ensure we have a SessionUser before accessing ID

src/Security/JsonWebTokenAuthenticator.php
Returning null from getCredentials isn't allowed, instead we need to
ensure that the token is fully present in the supports method first.
Also cleaned up typing and imports.
Fixes #3151
=> Check for token before using it

docker/apache.conf, docker/nginx.conf.template
Adding configuration settings to both our apache and nginx containers to
limit what info we expose in headers.
=> Restrict webserver info in headers

Dockerfile
PEAR and therefor PECL have been removed in PHP8 and are deprecated in
7.4 so this is how we need to install apcu now.
=> Install apcu manually

Dockerfile
There is an issue with caching in PHP 7.4.11 that I'm attempting to
track down, for now lock our containers at this earlier version so we
can continue to deploy.
=> Lock PHP at v7.4.10

.github/workflows/ci.yml, bin/setup, docs/install.md
The autoloder had diverged from the symfony standard because it wasn't
updated during the last major version sweep.
=> Fix setup command and add tests

Dockerfile
PHP 7.4.13 resolves our issues with preloading and traits so we can
unlock this to build with that latest release.
=> Unlock PHP version

config/services.yaml
This service is becoming private in symfony 5.2 so we can't rely on
auto-injection anymore and have to manually tag this.
=> Clear container deprecation

tests/Command/SendTestEmailCommandTest.php
Not sure why this worked in PHP 7, but it fails in 8.0. Instead of
grabbing the keys from the array we need to extract the address from
each to/from array.
=> Update test for PHP 8

.github/workflows/future-php.yml
=> Add missing extensions for PHP 8 install

tests/Endpoints/CourseTest.php, tests/Service/CourseRolloverTest.php
the fix for the rollover service test should be permanent. i'm kicking the bucket down the road on the the api endpoint tests.
=> updates test vectors for course rollover tests

src/Entity/Alert.php, src/Entity/Authentication.php, src/Entity/Competency.php, src/Entity/Course.php, src/Entity/CourseLearningMaterial.php, src/Entity/CurriculumInventoryAcademicLevel.php, src/Entity/CurriculumInventoryReport.php, src/Entity/CurriculumInventorySequence.php, src/Entity/CurriculumInventorySequenceBlock.php, src/Entity/LearnerGroup.php, src/Entity/LearningMaterial.php, src/Entity/MeshConcept.php, src/Entity/MeshDescriptor.php, src/Entity/MeshTerm.php, src/Entity/Offering.php, src/Entity/Program.php, src/Entity/Report.php, src/Entity/School.php, src/Entity/Session.php, src/Entity/SessionDescription.php, src/Entity/SessionLearningMaterial.php, src/Entity/Term.php, src/Entity/User.php
This is the new pattern as allowEmptyString is deprecated in Symfony
5.2.
=> Validate empty strings correctly

src/Repository/MeshDescriptorRepository.php
`executeUpdate()` has been renamed to `executeStatement()` in Doctrine 3.0.0
see https://github.com/doctrine/dbal/releases/tag/3.0.0
=> replaces deprecated method with its supported equivalent.

config/packages/test/security.yaml, tests/DataLoader/AuthenticationData.php
This cuts a few minutes off our total test run time as it doesn't waste
CPU cycles encoding fake passwords. Thanks Twitter!
=> Don't encode passwords in tests

src/Repository/LearningMaterialRepository.php
This was dropped when moving from Manager to Repository and is needed in
the cleanup strings command.
=> Re-add missing method to LM repository

src/Entity/DTO/SessionDTO.php
This relationship was removed in API v3 and is no longer needed here.
=> Remove unused sessionDescription field

src/Controller/DirectoryController.php
These query params come through as strings, but array_slice requires int
so I've coerced them into the correct type.
=> Force int types on user input

migrations/Version20210201224131.php, src/Entity/Alert.php
currently, alerts cannot be deleted wholesale due to a blocking foreign-key constraint on alert instigators. this removes this constraint by declaring cascading deletes on this relationship instead.
refs #3286
=> Adds cascading deletes to alert recipients relationship.

src/Controller/API/Authentications.php, src/Controller/API/Cohorts.php, src/Controller/API/CurriculumInventoryExports.php, src/Controller/API/CurriculumInventoryReports.php, src/Controller/API/CurriculumInventorySequenceBlocks.php, src/Controller/API/LearningMaterials.php, src/Controller/API/Offerings.php, src/Controller/API/ProgramYears.php, src/Controller/API/ReadWriteController.php, src/Controller/API/Users.php, src/Traits/ApiEntityValidation.php
We were assuming that the validation errors were Stringable, but the
symfony docs indicate that is really a debugging function. I went ahead
and extracted this logic into a trait so it could be applied to the
controllers which don't extend the ReadWriteController as well.
=> Refactor endpoint validation

src/Controller/ConfigController.php, tests/Controller/ConfigControllerTest.php
we need this in the frontend to determine labeling of the year dropdown values in the "new course" component, possibly in other places as well.
=> expose the value of the academic-year flag via the config API endpoint.

.github/workflows/ci.yml
Breaking these up isn't saving us time, but does make finding errors
harder.
WIP:
Also removed composer caching, that wasn't helping.
=> Consolidate PHPUnit tests in CI

src/Service/LdapManager.php
Without this we can't check if the property is falsey later.
Fixes #3350
=> Initialize LDAP before use

.github/workflows/update-dependencies.yaml
This will cause the actions to run, using the GITHUB_TOKEN value doesn't
work anymore.
=> Use Zorgbort PAT token for updates

src/Service/LdapManager.php
Sometimes the firstName can be null in an LDAP record, I'd assume that
lastName can too so I'm checking them both here and only comparing the
strings.
Fixes #3415
=> Ensure we're comparing strings in LDAP search

.github/workflows/ci.yml, Dockerfile, composer.json, composer.lock, config/packages/monitor.yaml, docker/php-fpm-entrypoint, docs/ilios_php_version_policy.md, docs/install.md
inline with out official policy it is time to drop support for PHP 7.4
and move onto PHP 8 full time.
=> Drop PHP 7.4 support

src/Attribute/DTO.php, src/Attribute/Expose.php, src/Attribute/Id.php, src/Attribute/ReadOnly.php, src/Attribute/Related.php, src/Attribute/RemoveMarkup.php, src/Attribute/Type.php, src/Entity/DTO/AamcMethodDTO.php, src/Service/EntityMetadata.php
This is the first step in removing our need for dockblock annotations
and the userland libraries needed to read those tags. Initial benchmarks
put this at about 5% faster for the trivial usecase in our tests, it may
be a bigger performance improvement with complicated multi-object
JSON:API requests.
This is POC at this point with only AamcMethodDTO actually making the
transition, but I've modified out lookup to account first for attributes
and then to fallback to the annotations. This should allow a multi-step
transition of all DTOs to this over time.
=> Allow PHP Attributes to mark DTOs

src/Classes/ElasticSearchBase.php, src/Classes/LocalCachingFilesystemDecorator.php, src/Command/CleanupStringsCommand.php, src/Command/FixLearningMaterialMimeTypesCommand.php, src/Command/UpdateFrontendCommand.php, src/Repository/AuthenticationRepository.php, src/Repository/SchoolConfigRepository.php, src/Security/JsonWebTokenAuthenticator.php, src/Service/CasAuthentication.php, src/Service/Config.php, src/Service/LoggerQueue.php
This is now allowed in PHP so we no longer need to specify an unused
variable in each catch statement.
=> Remove unused variable in catch

config/packages/framework.yaml
This was removed in a config update and it is critically needed so that
https URLs are still generated when SSL is terminated on the load
balancer.
=> Restore configuration for trusted proxies

.github/workflows/deploy-latest.yml
This is the recommended way to handle multi-registry deploys by the
docker action. Also fixed the credentials for Github deploys to use the
action token.
=> Combine container deploys

src/Command/SyncStudentStatusCommand.php, src/Repository/UserRepository.php, tests/Command/SyncStudentStatusCommandTest.php
New users are sometimes added without the correct student status or else
their status changes after they are added. This command can be run with
an LDAP filter to discover all students in the directory and then mark
them as students in Ilios.
Fixes #3564
=> Add command to sync student status

composer.json, composer.lock
Now that 2.0 has been released we can track `@stable` instead of the
pre-release alphas.
=> Return test-fixtures to stable version

Dockerfile
This is required to create the /etc/ldap/ldap.conf file which is
needed to do any kind of ldap work. Adding this package adds the default
file and configures everything to work correctly.
=> Add libldap-common to install

config/packages/prod/doctrine.yaml
this can be removed without substitute.
refs #3616
=> rm obsolete metadata_cache_driver config item.

Dockerfile
This is required here as well as in the PHP base as this container is
standalone.
=> Add messenger transport to php-apache container

src/Encoder/JsonApiEncoder.php
When data was not present or the user didn't have permission to access
it we were throwing a PHP warning here since the array didn't have an
index at 0. By using null coalescing here we can avoid the warning and
still return the same data.
Fixes #3640
=> Improve handling of missing data in JSON:API

src/Service/GraphQL/TypeRegistry.php, src/Service/GraphQL/TypeResolver.php, tests/AbstractEndpointTest.php, tests/DataLoader/AbstractDataLoader.php, tests/DataLoader/DataLoaderInterface.php, tests/GetEndpointTestable.php
Big performance improvement in not loading a bunch of data we don't need. This enabled a query like `"query { schools(id: [1, 3]) { id } }"` which will only load the schools with id 1,3. I made a judgement call to simplify this API and just call it `id` even though it takes an array of IDs. We could also have an `id` and `ids`, but that seems unnecessary at this point.
=> Filter GraphQL results by ID

.github/workflows/deploy-latest.yml, .github/workflows/deploy-tag.yml, .gitignore, Dockerfile
We were relying on the git tag for the version, however it doesn't
actually end up in the image so we need to pass the version in through
the build.
=> Add Version to Docker Build

.github/workflows/deploy-latest.yml
This will allow our containers to run natively on Apple Silicon.
I'm not sure if Github can build this architecture without an emulation layer, but we'll have to merge this to find out. I can't think of any other way to test it.
=> Add ARM builds to our docker builds

.github/workflows/deploy-latest.yml
The official mysql image doens't have an arm64 build for us to draft off
of so we'll have to skip multi-platform building for our images which
extend it.
=> Split mysql containers off for single platform build

config/packages/exercise_html_purifier.yaml, src/Repository/CourseLearningMaterialRepository.php, src/Repository/SessionLearningMaterialRepository.php, tests/Command/CleanupStringsCommandTest.php
These blank constructs like `<p><br /></p>` are often inserted by Froala, but they don't play nice with styling on the frontend. After this change I ran our `CleanupStrings` command against demo data and see:
```
$ bin/console ilios:cleanup-strings --session-description --objective-title --learningmaterial-description --learningmaterial-note --learningmaterial-links
Starting cleanup of objective titles...
159840/159840 [============================] 100%
9999 Objective Titles updated.
Starting cleanup of learning material description...
78350/78350 [============================] 100%
1292 Learning Material Descriptions updated.
Starting cleanup of course learning material notes...
2141/2141 [============================] 100%
0 Course Learning Material Notes updated.
Starting cleanup of …
```
=> Remove HTML spacing elements

.github/workflows/tag_version.yaml
Without this we can't detect the last tag.
=> Fetch the entire git tree when tagging

config/packages/security.yaml, src/Controller/AuthController.php, tests/AbstractEndpointTest.php, tests/Controller/ApiControllerTest.php, tests/Controller/AuthControllerTest.php, tests/Controller/ErrorControllerTest.php, tests/Controller/UploadControllerTest.php, tests/Endpoints/AcademicYearTest.php, tests/Endpoints/AuthenticationTest.php, tests/Endpoints/CurrentSessionTest.php, tests/Endpoints/CurriculumInventoryExportTest.php, tests/Endpoints/SchooleventsTest.php, tests/Endpoints/UsereventTest.php, tests/Endpoints/UsermaterialsTest.php, tests/GetEndpointTestable.php, tests/ReadWriteEndpointTest.php
When we updated our security config a change was needed to default
protect resources as it appears symfony moved to default allow with this
change. I've added a configuration option to protect everything by
default and added some tests to ensure this stays true.
=> Require authentication to access by default

config/bundles.php, config/packages/prod/sentry.yaml
We only need this in production and when it's loaded in tests it throws
an annoying error about the error_handler being removed even though it
is disabled. Ditch it entirely from where we don't need it.
=> Disable Sentry entirely in tests and dev environments

tests/Command/SendTeachingRemindersCommandTest.php
This is legal and the best way, we were relying on the service to be
public, but that is deprecated in future versions of Symfony.
=> Pull twig off the test container

src/Classes/SessionUser.php, src/Classes/SessionUserInterface.php, src/Command/AddUserCommand.php, src/Command/ChangePasswordCommand.php, src/Command/InstallFirstUserCommand.php, src/Controller/API/Authentications.php, src/Service/FormAuthentication.php, tests/Command/AddUserCommandTest.php, tests/Command/ChangePasswordCommandTest.php, tests/Command/InstallFirstUserCommandTest.php, tests/Service/FormAuthenticationTest.php
This is essentially a semantic change to clear up what the service does.
The only iffy part is that the order of interfaces in SessionUser has to
be correct in order for the more specific getPassword with a return type
to be read.
=> Replace password encoder with hasher

tests/Endpoints/AssessmentOptionTest.php
Sometimes the test fails because faker generates the same name for both
PUT attempts. Adding the array key to the data ensures this can't
happen.
=> Add guaranteed uniqueness to test data

src/Service/GraphQL/TypeRegistry.php
Profiled this change and there is no difference between the cached and
uncached versions. This is probably because we use callbacks to build
portions of the schema only when they're needed. This use of callbacks
makes this cache unworkable with Symfony 5.4 so removing the cache makes
us ready to upgrade.
Profile of a fairly large request https://blackfire.io/profiles/compare/237f09e9-dc4a-47b7-97d4-55e61bb54bd9/graph
=> Remove unnecessary cache

config/packages/messenger.yaml
This prevents leaky services like the logger from holding onto memory.
=> Reset the container between messages

tests/Traits/JsonControllerTest.php
Caching this token for each user causes some hard to trace test failures
for user #3 because that user has an invalidateTokensIssuedBefore value
which is set to the current time. If that fixture reloads after this
token is generated they'll be out of sync
Wip:
=> Stop caching test token

tests/Endpoints/CourseTest.php
This method is deprecated by PHP in v8.1. Drop in replacement here,
didn't touch the kludge.
=> Replace strftime usage

composer.json, composer.lock, src/Service/Config.php, symfony.lock, tests/Service/ConfigTest.php
We're only using this in a single place to transform fairly regular
input so I ditched the dependency which hasn't been updated in a while
and replaced it with this method.
=> Replace Stringy lib with a utility method

docs/ilios_quick_setup_for_admins.md
We (and the rest of the world) use LAMP everywhere except in one place where we use L.A.M.P. Use LAMP everywhere.
=> chore: change L.A.M.P. to LAMP

.github/workflows/update-dependencies.yaml
This allows the task to be run on demand when needed to get newer
updates.
=> Add manual dispatch to updating dependencies

composer.json, composer.lock
This was expanded into our dependencies by symfony flex, but we don't
need it directly and don't need to keep it here.
=> Remove indirect dependency

composer.json, composer.lock, phpcs.xml.dist, symfony.lock
This was added to help get to new PHP versions, but we don't need it
anymore.
=> Remove PHP Upgrade Code Sniff

composer.json
was prompted with this during `composer install` after upgrading to latest version of composer (v2.2.3).
```
$ composer install
composer/package-versions-deprecated contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "composer/package-versions-deprecated" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
phpstan/extension-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "phpstan/extension-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
symfony/flex contains a Composer plugin which is currently not in your …
```
=> whitelist which plugins are allowed to execute code during a composer run.

docker-compose.demo.yml, docker-compose.override.yml, docker-compose.yml, docs/ilios_quick_setup_for_admins.md
Using an override system as recommended by docker. This makes it easier to develop Ilios by ensuring that the expected `docker compose up` command will build a working environment and also creates a demo experience which can use `docker compose -f docker-compose.yml -f docker-compose.demo.yml up` to build a demo enivironment both as a sample for what a working Ilios might look like as well as a nice API server to use locally when making changes to the frontend.
=> Improve Docker Development Setup

Dockerfile
Having this world writable prevents mysql from reading it.
=> Fix permissions on mysql config in docker

Dockerfile, docker-compose.override.yml, docker-compose.yml, src/Command/WaitForDatabaseCommand.php, tests/Command/WaitForDatabaseCommandTest.php
Adding a command `Ilios:wait-for-database` which loops indefinitely until the DB is available allows us to unlock the messages and migration docker commands.
=> Wait for database command and docker improvement

docs/ilios_quick_setup_for_admins.md
Because we share the working directory in our development docker setup
using the override file we need to do a bit of pre-setup before starting
the default containers.
=> Docker docs fixup

src/Command/WaitForIndexCommand.php, src/Service/Index/Manager.php, tests/Command/WaitForIndexCommandTest.php
This is useful for a docker container which shouldn't run until there is
an index to run in.
=> Add command to wait for index to be available

src/Service/Index/Curriculum.php
We need to use doSearch here because searching directly on the client
bypasses our protections for there not being a client configured.
=> Use internal method to search

docker-compose.override.yml
This ensures that code changes made locally which would impact this
service are reflected in the container.
=> Use the developer environment for development containers

Dockerfile
This ensures we don't fill the log with garbage while everything is
starting or getting setup.
=> Ask the messenger container to wait for the index

migrations/Version20220202010454.php
"one of these things is not like the others"
```sql
SELECT table_name, table_collation
FROM information_schema.`TABLES`
WHERE table_schema = 'ilios'
AND table_name LIKE 'mesh%';
```
| TABLE\_NAME | TABLE\_COLLATION |
| :--- | :--- |
| mesh\_concept | utf8\_unicode\_ci |
| mesh\_concept\_x\_term | utf8\_general\_ci |
| mesh\_descriptor | utf8\_unicode\_ci |
| mesh\_descriptor\_x\_concept | utf8\_unicode\_ci |
| mesh\_descriptor\_x\_qualifier | utf8\_unicode\_ci |
| mesh\_previous\_indexing | utf8\_unicode\_ci |
| mesh\_qualifier | utf8\_unicode\_ci |
| mesh\_term | utf8\_unicode\_ci |
| mesh\_tree | utf8\_unicode\_ci |
this PR adds a migration that realigns the collation on the `mesh_concept_x_term` table, since the new version of Doctrine ORM is choking on this mismatch during schema …
=> Changes collation on join table to realign it with rest of schema.

src/Controller/IndexController.php
This isn't always present. Fixes #3890
=> Don't require frontend divs to have a class

src/Command/UpdateFrontendCommand.php
The file created timestamp doesn't really have anything to do with the
age of the frontend files. When we download many versions at the same
time the timestamps are network load dependent. So, when copying files
into the frontend directory (particularly VERSION.txt) we want to
overwrite each time.
=> Overwrite newer files when copying assets

Dockerfile, docker/php-apache-entrypoint
Instead of chmoding in the build step I'm stealing this from the FPM
container and doing the setacl and cache clear in the entrypoint.
=> Change the way the apache container boots

src/Controller/SchooleventController.php, src/RelationshipVoter/SchoolEvent.php, tests/Endpoints/SchooleventsTest.php, tests/RelationshipVoter/SchoolEventTest.php
fixes https://github.com/ilios/ilios/issues/3051
in order for the virtual link URLs to be included in the school events payload, the requesting user must be associated with the event's underlying offering or ILM  either as a learner or as an instructor/director/administrator.
=> conditionally blank virtual links in school events.

composer.json, composer.lock, config/services.yaml, src/Classes/LocalCachingFilesystemDecorator.php, src/Command/CleanupS3FilesystemCacheCommand.php, src/Service/FilesystemFactory.php, src/Service/IliosFileSystem.php, symfony.lock, tests/Classes/LocalCachingFilesystemDecoratorTest.php, tests/Command/CleanupS3FilesystemCacheCommandTest.php, tests/Service/FilesystemFactoryTest.php, tests/Service/IliosFileSystemTest.php, tests/Service/NonCachingIliosFileSystemTest.php
Updating to v3 requires a minimum PHP version of 8.0.2 and dropping the
caching adapter. Some API changes that are mostly cosmetic for us.
| Production Changes              | From    | To      | Compare                                                                            |
|---------------------------------|---------|---------|------------------------------------------------------------------------------------|
| aws/aws-sdk-php                 | 3.220.3 | 3.220.4 | [...](https://github.com/aws/aws-sdk-php/compare/3.220.3...3.220.4)                |
| league/flysystem                | 1.1.9   | 3.0.18  | [...](https://github.com/thephpleague/flysystem/compare/1.1.9...3.0.18)            |
| league/flysystem-aws-s3-v3      | 1.0.29  | 3.0.13  | …
=> Update Flysystem to v3

src/Command/UpdateFrontendCommand.php, src/Repository/AuthenticationRepository.php, src/Service/Config.php
In PHP8 this isn't required anymore so if we don't use it we can drop
it.
=> Drop unused exception variable

docker/nginx.conf.template
105M mirrors what we have for PHP and allows files greater than the 1mb
nginx default to be uploaded.
=> Add client_max_body_size to nginx docker config

docs/update.md, src/Command/SetConfigValueCommand.php, src/Monitor/DeprecatedConfigurationOption.php, tests/Command/SetConfigValueCommandTest.php
Added a warning message to our health check and documented this
deprecation, we can remove these configuration options in the next major
release.
In order to make it easier to remove the old options (and anything else)
I added a --remove flag to our set-config-value command which will
delete a config options from the DB.
Fixes #3904
=> Deprecate Google Analytics

docker/nginx.conf.template
Left a colon in here, doesn't work like that.
=> Fix nginx config

Dockerfile, docker/nginx.conf.template
When nginx boots it was imemdiatly searching for the php-fpm host which,
if it wasn't present, would then kill nginx. This doesn't work very well
in our docker setup and can intorduce mysterious failures.
This change stores the php-fpm host as an in-nginx-config variable that
isn't read until it is needed so startup isn't blocked. Because nginx
has it's own internal dns resolution that doesn't fall back to the host
we also need to override the resolve of the server. Docker provides DNS
that works well for this, but I've added it as an environmental variable
as well so it can be overridden at boot time if fargate or some other
task runner doesn't something different.
=> Modify nginx to be more tolerant of missing PHP container

.github/workflows/ci.yml, Dockerfile
This will check to ensure port 80 is open and listening every 5 seconds,
we can use it in CI to ensure the container actually started.
=> Add a healthcheck to nginx

src/Service/JsonWebTokenManager.php, tests/Controller/AuthControllerTest.php, tests/Service/JsonWebTokenManagerTest.php
Currently all of the tokens we generate get their permissions from the
user that generates them. Let's explicitly indicate that so we can
enhance it later by adding specific permissions to the token itself.
Refs #4039
=> Add default user based permissions to all tokens

.env.dev
Having this in both .env and .env.dev makes is annoying on first setup
to change it in the right place. Let's comment out the one in .env.dev
so creating a .env.local is enough to get started.
=> Comment out DB config in dev env file

docker-compose.override.yml, src/Command/UpdateFrontendCommand.php, src/Controller/IndexController.php, src/Monitor/Frontend.php, tests/Controller/IndexControllerTest.php
Instead of splitting this up into various cache and tmp directories I've
consolidated everything into var/frontend. This is makes it possible to
share this directory with containers making it easier to develop and
test ilios.
I also realized that we were still thinking about the active version as
a path to many assets, but it's really just a single JSON file so I
changed the way we share that path with other areas of the application
and was able to drop some constants and make others private.
=> Re-organize how the frontend is stored on disk

composer.json, composer.lock
We needed to pin this to keep doctrine/persistence at v2 for an
incompatibility with liip fixtures in #4034, but that is resolved now.
| Production Changes       | From  | To    | Compare                                                                 |
|--------------------------|-------|-------|-------------------------------------------------------------------------|
| doctrine/doctrine-bundle | 2.6.2 | 2.6.3 | [...](https://github.com/doctrine/DoctrineBundle/compare/2.6.2...2.6.3) |
| doctrine/persistence     | 2.5.3 | 3.0.2 | [...](https://github.com/doctrine/persistence/compare/2.5.3...3.0.2)    |
=> Unpin doctrine bundle

tests/Command/FixLearningMaterialMimeTypesCommandTest.php
Mockery isn't getting the exception instantiation right, but passing an object works
correctly.
fixes #4065
=> pass exception object instead of FQN to Mockery.

src/Command/ImportDefaultDataCommand.php
Turns out that if you run PHPUnit on our test coverage in _random mode_ (like Infection does), the test run may fail with this message
```
There was 1 failure:
1) App\Tests\Command\ImportDefaultDataCommandTest::testExecute
Failed asserting that '\n
[ERROR] The command is already running in another process.                                                             \n
\n
' contains "Completed data import".
```
This happens when the test for the error condition runs before the happy path - we weren't releasing the lock on the command under all circumstances.
This fixes the problem.
=> unlock command before returning.

src/Entity/AamcPcrsInterface.php, src/Entity/AamcResourceTypeInterface.php, src/Entity/AlertChangeTypeInterface.php, src/Entity/AuditLogInterface.php, src/Entity/CourseClerkshipTypeInterface.php, src/Entity/CourseInterface.php, src/Entity/CurriculumInventoryReportInterface.php, src/Entity/LearnerGroupInterface.php, src/Entity/LoggableEntityInterface.php, src/Entity/MeshPreviousIndexingInterface.php, src/Entity/MeshTreeInterface.php, src/Entity/OfferingInterface.php, src/Entity/ProgramInterface.php, src/Entity/SchoolConfigInterface.php, src/Entity/SchoolInterface.php, src/Entity/SessionInterface.php, src/Entity/TermInterface.php, src/Entity/UserInterface.php, src/Entity/VocabularyInterface.php, src/Service/LearningMaterialDecoratorFactory.php, src/Traits/StringableEntityToIdInterface.php
It wasn't super clear to me that everything implementing this interface
knew to return the ID and not some other representation of the object as
a string. I've renamed it for clarity.
=> Change name of stringable entity interface

src/Controller/API/CurriculumInventorySequenceBlocks.php, src/Repository/RepositoryInterface.php, src/Traits/ManagerRepository.php
When a new block hasn't get been persisted we don't need to compare it
by id to all the other blocks (it's id is null).
This prevents us checking the id value before it has been set once the
id is typed.
=> Only compare sequence blocks if necessary

src/Controller/API/CurriculumInventorySequenceBlocks.php
This could never be true as comparing any value for ID to an object
doesn't make sense. We do allow the CIBlock class to cast itself to a
string by its ID, however since getId() is going to return and int and
we're doing a strict comparison I don't believe even PHP magic would
ever evaluate this to true.
=> Remove invalid comparison check

docker/fpm/docker-entrypoint.sh, docker/php-apache-entrypoint, src/Service/TemporaryFileSystem.php, tests/Service/TemporaryFileSystemTest.php
When var/tmp doesn't exist realpath returns false which then attempts to
write ilios files to /uploads instead of /var/tmp/uploads. We need to
create var/tmp in containers, but also be more resilient and create it
if necessary when storing files.
Fixes #4072
=> Fix missing temporary directory

.github/workflows/infection.yml, .gitignore, composer.json, composer.lock, infection.json, symfony.lock
see https://infection.github.io
let's run this on a timer instead of in real-time on PRs, since these will fail right now and will take a long time to run. 
there are options for speeding this up, the most obvious would be to re-use the code coverage generated by PHPUnit in the "coverage" step (will need some work to make that happen), see https://alejandrocelaya.blog/2018/02/17/mutation-testing-with-infection-in-big-php-projects/ for details.
=> Add Infection Tests to our test coverage

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/update-dependencies.yaml, composer.json, composer.lock, config/packages/monitor.yaml, docs/ilios_php_version_policy.md, docs/install.md
In accordance with our PHP version support policy we're no ready to drop
PHP 8.0 and require PHP 8.1 for Ilios.
=> Drop Support for PHP 8.0

.github/workflows/ci.yml
This github specific docker build cache is marked as experimental and
we're consistently seeing random CI failures when mysql or elasticsearch
get updated. Removing this cache for now.
=> Remove Experimental Build Cache

.github/workflows/infection.yml
trying to shake the `The file "index.xml" could not be found: Could not find any "index.xml"  file in "/home/runner/work/ilios/ilios/build/coverage"` warning emitted by this action. 
It appears that command line options are being dropped, so using init values as a (hopefully working) alternative.
=> initialize xdebug mode to coverage instead of using command line params.

docker-compose.demo.yml
Missing this property which is pretty critical to the messages
containers actually working.
=> Configure search on demo docker compose file

src/DependencyInjection/PrefixSeedCompilerPass.php, src/Kernel.php
This ensures that we won't have collisions in a production environment
when doing a deploy. Instead the different versions of the app will
write to different caches.
=> Add our VERSION to the cache prefix seed

.github/workflows/deploy-nightly.yml
This hasn't been published yet and we shouldn't attempt to tag it every
night.
=> Remove redis container from nightly build

.github/workflows/deploy-nightly.yml
Now that there is a live v3.100.0 version of this container we can
re-enable the nightly builds as well.
=> Re-enable nightly deploy of tagged redis container

.github/workflows/auto-merge.yml
For patch and minor updates of things in require-dev we can go ahead and
automerge them when tests pass.
=> Enable automerge for development dependencies

Dockerfile, composer.json
These were removed when the bin/setup command was introduced to work
around a cache clearing issue with our docker container that wasn't
fully noted. As far as I can tell we don't have that issue anymore and
containers are able to build with these scripts in place. This is
important because the asset install is expected by many bundles so we
need to make sure it happens.
edit: The original issue was missing the `ILIOS_DATABSE_URL` config value, but I've copied our approach from the `php-fpm` containers to the `php-apache` containers and created an empty `sqlite` DB URL which will, of course, be overridden in any real app.
=> Restore symfony auto-scripts

src/Classes/JsonApiData.php, src/Service/JsonApiDataShaper.php, tests/Endpoints/CourseTest.php
When we access other data from JSON:API we were loading it even if the
user didn't have permission to access it. Instead we need to filter all
side loaded data through the permissions system.
=> Check permissions on side loaded data

src/Command/CleanupStringsCommand.php, tests/Command/CleanupStringsCommandTest.php
yet another tool for fixing up user input.
fixes https://github.com/ilios/ilios/issues/4117
```bash
$ bin/console ilios:cleanup-string  --objective-title-blankspace
Starting cleanup of objective titles...
168106/168106 [============================] 100%
12551 Objective Titles updated.
```
=> adds command option for trimming surrounding blank space from objective titles

config/packages/web_profiler.yaml
In symfony 6.1 when this is enabled instead of getting the service we
asked for we get a TraceableNormalizer instead which isn't valid.
Easiest way to resume development is to remove this data collection and
the problem it causes for us.
=> Disable serializer data collection

.github/workflows/infection.yml
this attempts to overcome the out-of-memory failures we're currently
seeing with infection tests.
i'm fishing somewhat in the dark here, since i haven't been able to find any info on how these test machines are spec'ed out RAM wise.
=> setup PHP with 1GB max memory consumption.

docker-compose.override.yml
This feature isn't ready to be enabled by default yet, it's not working.
=> Disable DTO Cache in Development Containers

templates/email/teachingreminder.text.twig, tests/Command/SendTeachingRemindersCommandTest.php
=> in teaching reminders, link to session instead of course.

src/Service/JsonWebTokenManager.php, tests/Service/JsonWebTokenManagerTest.php
Sometimes when this token gets generated the userId is a string, we need
to cast it back to an int to satisfy the contract for this method.
Fixes #4268
=> Cast JWT userId into a string

docker/fpm/symfony.dev.ini
Symfony in dev mode records a lot of debugging info for us, we need to
give it more memory for each run.
=> More memory for fpm-dev PHP

config/packages/doctrine_migrations.yaml, symfony.lock
the latest recipe turns off the profiler by default, so let's roll with
that too.
=> updates symfony recipe for doctrine migrations bundle.

Dockerfile
There is new code in composer 2.4.2 that checks if composer is running in a container that isn't working for our php-apache container so we need to set this value ourselves to ensure we can build.
=> Allow composer to run as root in build

config/packages/sentry.yaml
Add AccessDeniedException to the list of sentry ignore errors. This will help reduce the number of spam exceptions posted to sentry.
=> Sentry Ignore AccessDeniedException

.github/workflows/deploy-nightly.yml
Only notify on failure, and send a message instead of a list of step.
=> Refine build failure notifications

src/Command/SyncAllUsersCommand.php, tests/Command/SyncAllUsersCommandTest.php
When a user is in the system twice with the same campus ID we can't ignore the second entry just because it is disabled. This can cause serious database issues when we attempt to update the non-disable account's username or other unique information. We have to stop the sync in this case.
Fixes #4417
=> Prevent double IDs from breaking user sync

.github/workflows/coverage.yml, .github/workflows/future-php.yml, .github/workflows/infection.yml, .github/workflows/update-dependencies.yaml
When these scheduled jobs fail the error notification only goes to the
person who merged the last PR on the workflow file. Instead this will
report these issues to the team ilios slack.
While I was adding these notification I noticed that our future PHP test was running on the wrong version of PHP, updated that as well.
=> Report Workflow Failures to Slack

config/packages/sentry.yaml
Starting with 10% of transactions, lets start collecting some performance data to identify issues.
=> Send performance data to sentry

.github/workflows/coverage.yml, .github/workflows/deploy-nightly.yml, .github/workflows/future-php.yml, .github/workflows/infection.yml, .github/workflows/update-dependencies.yaml
When these tests fail it is much nicer to click a link back to the test instead of having to track it down.
=> Add a Link to the Failed Job

.github/workflows/coverage.yml, .github/workflows/deploy-nightly.yml, .github/workflows/future-php.yml, .github/workflows/infection.yml, .github/workflows/update-dependencies.yaml
Turns out this action doesn't parse markdown so we'll just send the link ugly.
=> Fix job failure message formatting

config/packages/sentry.yaml, config/services.yaml, src/Service/SentryTraceSampler.php
Our sampling is getting overwhelmed with requests for LM files and ICS feeds. These are fairly slow operations and not something we're able to optimize right now. Let's skip sampling these so we can focus on other areas.
=> Adjust Sentry Sampling

src/Service/SentryTraceSampler.php
The array key 'route' doesn't always exist which them emits a PHP warning, fixed with a check.
=> Fix TraceSampler for Console Commands

.github/workflows/deploy-tag.yml
Sentry isn't doing a good job auto-detecting our tags, let's use the version we're already extracting and roll with that.
=> Better Sentry Version Tagging

.github/workflows/ci.yml
With the release today we should start testing against PHP 8.2 to ensure compatibility.
=> Add PHP 8.2 to test matrix

src/Repository/SessionRepository.php, tests/Endpoints/SessionTest.php
Copypasta from the school filter tried to double alias s_courses which breaks when sending both a course and school filter.
=> Fix query alias for session course filter

config/services.yaml
To encompass changes to the filters and content in our GraphQL API. While this API isn't versioned we need the version bump to ensure we load a compatible frontend.
Refs: #4587 #4555 #4573 #4574 #4583 #4581
=> Bump API to v3.8

src/Controller/API/CurriculumInventoryReports.php
According [to the docs](https://zircote.github.io/swagger-php/reference/attributes.html#requestbody) this is supposed to be an array, so I've wrapped it that way. As far as I can tell this value isn't displayed in our docs so I'm not sure where to test.
=> Pass Correct Documentation Attribute Value

Dockerfile, docker-compose.override.yml
For development it's super helpful to have the verbose output of messages being consumed and to include the higher memory and other symfony development PHP config tweaks. I have the container building, but not deploying because I don't know if this is something anyone else would want to use outside of ilios local development.
=> Add a consume-messages-dev container

src/Command/Index/CreateCommand.php, tests/Command/Index/CreateCommandTest.php
Running ilios:index:create without this check will appear to succeed if indexing isn't configured. This can be very confusing. Instead when the index isn't configured we can output a nice warning.
=> Output a Warning when Index is not Configured

composer.json, composer.lock
We're not using annotations directly anymore having moved to attributes across the board.
(hopefully 😉)
=> Drop doctrine/annotations dependency

docker-compose.override.yml, docker/fpm/docker-entrypoint.sh
In order to be able to view uploads and index materials in different containers we have to share the file storage between them. In production this is done with S3 usually, but here I've created a names volume and ensured files are shared there. When the container boots it will create this directory if it doesn't exist, which is required in order to give it good permissions, but shouldn't be an issue for any other reason.
=> Share File Storage Between Containers

tests/AbstractEndpointTest.php, tests/Endpoints/CourseObjectiveTest.php, tests/Endpoints/CourseTest.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/ProgramTest.php, tests/Traits/JsonControllerTest.php
PHPUnit has deprecated these assertions and recommends using property_exists in their place. They will be removed in PHPUnit v10 which has already been released.
Fixes #4643
=> Remove Deprecated ObjectHasAttribute Assertions

Dockerfile
=> Update Opensearch Container to v2

src/Entity/DTO/SessionLearningMaterialDTO.php, tests/Endpoints/CourseLearningMaterialTest.php, tests/Endpoints/SessionLearningMaterialTest.php
Missed an attribute here which made it impossible to traverse to the session in GraphQL. Added some tests too.
=> Fix Session Relationship on SessionLearningMaterial

composer.json
refs https://github.com/ilios/ilios/pull/4705
=> prevent php-http/discovery from executing code during a composer run.

config/packages/sentry.yaml
These are scan attempts and don't need to be logged.
=> Stop sending MethodNotAllowed exceptions to sentry

Dockerfile
PHP 8.1 images are now based on debian bookwork (v12) which doesn't have the netcat package. Instead it has both a netcat-traditional and a netcat-openbsd. I stuck with traditional because we're only using it in our internal healthcheck and it does just one thing.
=> Replace netcat package in admin container

src/Classes/MysqlMigration.php
the name-checking functionality has been deprecated, this is the supported equivalent.
fixes #4865
=> check for database platform by classname, not against name.

src/MessageHandler/CourseIndexHandler.php, src/MessageHandler/LearningMaterialIndexHandler.php, src/MessageHandler/MeshDescriptorIndexHandler.php, src/MessageHandler/UserIndexHandler.php
In Symfony 6.3 using the interface for this is deprecated, we need to use an attribute instead.
=> Replace interface with attribute

config/packages/messenger.yaml
Option "reset_on_message" at "framework.messenger" is deprecated. It does nothing and will be removed in version 7.0.
fixes https://github.com/ilios/ilios/issues/4897
=> rm obsolete/deprecated config option.

.github/dependabot.yml
Instead of ignoring symfony updates we can batch them all together, do the same for docker updates in actions because these all rely on eachother.
=> Group updates from dependabot

src/EventListener/TimestampEntityChanges.php, src/Service/Timestamper.php, tests/Endpoints/AbstractEndpoint.php, tests/Endpoints/LearningMaterialTest.php, tests/Endpoints/MeshConceptTest.php, tests/Endpoints/MeshDescriptorTest.php, tests/Endpoints/MeshQualifierTest.php, tests/Endpoints/MeshTermTest.php, tests/Endpoints/OfferingTest.php, tests/Endpoints/ReportTest.php, tests/Endpoints/SessionTest.php
This creates a few seconds delay in a half dozen tests, but it removes an area of flakeyness from our tests when the mocked clock doesn't do what we expect. Total CI time is about 3min more. Acceptable.
While working on this I made some small changes to the timestamping application code that I think are keep worthy. I've changed the variable name and the way we build a DateTime from a timestamp and I also applied a unique method to the IDs before saving so we don't duplicate a bunch of IDs when we save things in big groups.
=> Remove ClockMock and accept the slight delay

config/packages/security.yaml
since our main firewall is stateless, we don't need to set a user provider on it.
see https://symfony.com/doc/current/security.html#security-user-providers
=> rm unnecessary security config.

src/Controller/API/Users.php, src/Service/ApiRequestParser.php, tests/Endpoints/AbstractEndpoint.php, tests/Endpoints/UserTest.php, tests/Traits/JsonControllerTest.php
We prevent modifying the root status of a user via a PUT request in the users controller, but we were not doing this same check for PATCH. This would allow school administrators to upgrade any user, including themselves, to have root permissions.
I also discovered the our existing tests for PATCH were not working correctly because the rejection could come from the permissions system and not the controller check if the user we tested with lacked the privilege to modify a user.
=> Prevent Changing Root Status Through Patch Request

src/Denormalizer/EntityDenormalizer.php, src/Normalizer/DTONormalizer.php, src/Normalizer/EntityNormalizer.php, src/Normalizer/FactoryNormalizer.php, src/Normalizer/JsonApiDTONormalizer.php
This allows symfony to cache what kinds of objects each normalizer can take which is a performance boost.
Not implementing this method is deprecated and will be required in Symfony 7.
Found a little performance boost here as well, by sending the `[*] = null` we can notify Symfony that for every other thing we not only don't cache it, we don't support it at all.
https://blackfire.io/profiles/compare/d7ed299e-b528-44c9-b8d9-45cedce1b6b8/graph shows a 8% speedup. 🔥
=> Add getSupportedTypes to Normalizers

.github/workflows/ci.yml, .github/workflows/deploy-nightly.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-tag.yml
The build-push-action from docker manages git for us, in most cases this has been fine. However, for our nightly re-builds we've been pulling off of HEAD instead of the tag we expect. I've removed the checkout from most places so it's clearer what is happening and setup the nightly re-build to use the local git context and not re-checkout the code before building.
Fixes #5107
=> Use docker tools for git context on containers

src/Command/UpdateFrontendCommand.php
the method signature in the WarmableInterface changed in Symfony 6.4.
see https://symfony.com/blog/new-in-symfony-6-4-build-dir-improvements
this sets things right again.
refs #5158
=> re-establish interface compliance for warmUp() method.

config/packages/framework.yaml, symfony.lock
the only real change here is to turn annotations off by default, which can be considered prep-work for Symfony v7.
=> updates symfony/framework-bundle recipe.

tests/Service/ApiRequestParserTest.php
Basic test coverage for this service, with clean separation of tests and their data providers.
I went a bit off the beaten path by passing closures as callbacks to some of the test functions.
Feels right in JS, but a bit weird in PHP. Please have a closer look.
fixes https://github.com/ilios/ilios/issues/5121
=> provides test coverage for ApiRequestParser class.

src/Service/EndpointResponseNamer.php, tests/Service/EndpointResponseNamerTest.php
fixes #5175
i did a little bit of cleanup on the service under test while at it.
=> provides test coverage for EndpointResponseNamer service.

composer.json, composer.lock, src/Command/ImportMeshUniverseCommand.php, tests/Command/ImportMeshUniverseCommandTest.php, tests/Service/MeshDescriptorSetTransmogrifierTest.php
the MeSH descriptors for 2024 are out, let's pull them in. 
no schema changes to the DTD again this year.
see https://www.nlm.nih.gov/databases/download/mesh.html for details and data.
=> adds 2024 universe to MeSH importer command, drops support for 2022.

.github/workflows/tag_version.yaml
The critical bit was to add the -a flag to the git commit to correctly stage the changed made in our working directory. While I was here I also replaced the deprecated set-output format and replaced with the now preferred $GITHUB_ENV format for moving information between steps.
=> Fix tagging workflow

templates/email/teachingreminder.text.twig
the link following the amended text does not link to the calendar, but to the sessions details on the course management screen.
follow-up item to #3469
=> correct link description.

.github/release.yml, .github/workflows/create_release.yaml
> The fastest way to a developer's heart is through removal of their code from the project.
— Mark Twain
This removes https://github.com/jrjohnson/generate-github-release-notes from our CI pipeline. Instead, GH's release note generation tools are used.
Please see https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes and https://github.com/ncipollo/release-action?tab=readme-ov-file#release-action for reference.
=> Streamline release notes generation

src/Repository/MeshDescriptorRepository.php
the Descriptor::addPreviousIndexing() method expects a string as an input, it cannot handle NULL.
this puts guard rails around that function call.
fixes #5378 
for reference, see https://github.com/ilios/mesh-parser/commit/87eb37554a3b07c8c955714e3061da914001d6a3#diff-b64ef4fd7da05e3b13283c1ca01fb2cd37cf5b5c43f0f3d47c9f86ad7d2c0401R155
=> prevent NULL from being added to previous-indexing list.

.github/workflows/create_release.yaml
Now that we're relying on github to generate these notes we don't have to mess about with the tag, we can just grab it off the ref. I also pulled in the recommended permissions config from the ncipollo/release-action guide.
=> Remove tag work from release notes

config/services.yaml, src/Classes/CalendarEvent.php, src/Classes/CalendarEventUserContext.php, src/Repository/UserRepository.php, src/Traits/CalendarEventRepository.php, tests/Classes/UserEventTest.php, tests/Endpoints/UsereventTest.php
fixes https://github.com/ilios/ilios/issues/5338
=> adds user contexts to userevents.

src/Controller/ConfigController.php, src/Service/Config.php, tests/Controller/ConfigControllerTest.php
Sometimes campus policy prevents legal name from being displayed, this configuration will allow us to determine this on the UI and hide that info.
Requires https://github.com/ilios/frontend/pull/7794
=> Allow show campus name to be configured by instance

.github/workflows/scan-repo.yml
The project key can't go in an environmental file, it has to be passed into the command. Let's try it this way.
=> Fix sonarqube configuration

docker/messages-entrypoint
When either the DB or index isn't ready it's hard to tell from the container logs. Adding some logging output will make it much easier to identify issues.
=> Add waiting messages to consume container

composer.json, composer.lock, src/Service/CasAuthentication.php
We were allowing a cookie, which can be user defined, to redirect users after CAS authentication. This could potentially be tampered with or set by a bad actor.
By signing these cookies and validating them we remove this possibility and ensure that whatever is supplied in the cookie was created by us.
=> Sign redirect requests for CAS

src/Service/CasAuthentication.php
It's a terrible idea to pass user input to deserialize. Like [super dumb](https://www.php.net/manual/en/function.unserialize.php). I've replace it with json encode and decode and added an additional check to ensure we don't go too deep on bad data.
=> Replace unsafe deserialize

src/Command/AddDirectoryUserCommand.php, src/Command/AddNewStudentsToSchoolCommand.php, src/Command/FindUserCommand.php, src/Service/Directory.php, tests/Command/AddDirectoryUserCommandTest.php, tests/Command/AddNewStudentsToSchoolCommandTest.php, tests/Command/FindUserCommandTest.php, tests/Service/DirectoryTest.php
Adding the display name and replacing output of the first and last name with the preferred version as well as saving the preferred version for new students synced into a school to match the behavior of the user sync command.
Refs #5453
=> Update directory commands to use preferred names

docs/error_reporting.md, src/Controller/IndexController.php, src/Service/SentryBeforeSend.php, templates/index/webindex.html.twig
This will make it much easier to categorize errors in our reporting and alarms.
=> Allow sending an environment with sentry errors

tests/Endpoints/AbstractEndpoint.php
We were not unsetting all the properties on the test object which caused it to get held in memory and was the source of our massive memory leak in tests.
=> Fix Testing Memory Leak

composer.json, composer.lock
v3 of this bundle slows our tests way down as some critical caching has been removed. Locking it at 2.9.0 for now while we work on this upstream.
=> Pin test-fixtures-bundle

.github/workflows/future-php.yml
Using the env in the test name was causing this to fail to ever run or process so we weren't getting the failure messages.
=> Fix future php tests

templates/index/webindex.html.twig
This is always a good idea, we have it on the frontend, but didn't include it in this HTML where almost all of our users load Ilios from. Since this is the default loading language on the frontend I'm ok with setting it to en, when a user changes their language this property gets updated as well.
=> Add missing lang attribute

.env.dev
Symfony loads this files in an order that means settings in a the .env.local file will be overwritten by settings in the .env.dev file. This is almost never what you would expect and leads to needing to specify some things in a .env.dev.local file that could otherwise be consolidated in a single .env.local file. By commenting out all of these vars we avoid this issue.
=> Comment out settings in dev environment

.github/workflows/ci.yml
Let's not get back in a situation with super long tests accidentally. Adding a timeout.
=> Add a timeout to test run

config/packages/messenger.yaml
Messages are moved to the `failure_transport` after failing to index to OpenSearch after the default `max_retries` = 3. Messages retried from the `failure_transport` are discarded permanently once `max_retries` is hit. The `async` and `failed` transport were using the same transport DSN causing Symfony to categorize all messages as already failed, thus discarding them permanently after failure (with retries) instead of saving them to the `failure_transport`.
Updating the queue name for the `failed` transport to `failed`, to separate the `async` and `failed` transport queues within `messenger_messages` table. Queue name is a column in the default, `messenger_messages` table, and keeps one table for multiple transports.
`messenger:stats` will show the number of messages in the queue of each …
=> change failed transport queue from default to failed

src/Classes/OpenSearchBase.php
We're hitting resource limits on open search with our bulk index requests, let's try bumping up this sleep so it isn't necessary to spend more on a larger instance.
=> Increase the sleep time for indexing

.github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-nightly.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-tag.yml, Dockerfile
- Disabled fast failing to containers will build even if one fails
- Added slack messaging when there is a failure
- Use the new GitHub API for passing outputs between jobs
- Updated nginx
- Changed our health check
- Used some new options to change the way we download and run the containers
=> Improvement to container build jobs

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/authentication_and_users.md, docs/custom_cli_commands.md, docs/custom_theming.md, docs/env_vars_and_config.md, docs/error_reporting.md, docs/ilios_api.md, docs/ilios_php_version_policy.md, docs/ilios_quick_setup_for_admins.md, docs/install.md, docs/shibboleth_authentication.md, docs/store_learning_materials_in_s3.md, docs/update.md, docs/upgrade_ilios_2_to_3.md
Documentation files (`./*.md` and `./docs/*.md`) needed some Markdown linting updates (as well as some other formatting fixes).
Markdown rules fixed:
* [MD001 - Header levels should only increment by one level at a time](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md001---header-levels-should-only-increment-by-one-level-at-a-time)
* [MD012 - Multiple consecutive blank lines](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md012---multiple-consecutive-blank-lines)
* [MD022 - Headers should be surrounded by blank lines](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md022---headers-should-be-surrounded-by-blank-lines)
* [MD031 - Fenced code blocks should be surrounded by blank …
=> Fix formatting issues in documentation

.github/workflows/ci.yml
this has become redundant - sonarqube gives us coverage reports as well.
refs #5529
=> rm CodeClimate integation for code coverage stats from workflow.

src/Service/GraphQL/TypeResolver.php, tests/Endpoints/AbstractEndpoint.php, tests/Endpoints/TermTest.php
These were working, but throwing errors which then resulted in null being set, which was what we wanted... anyway, we're checking for null now. I added some tests for this and also added a check to see if there are any errors on other requests.
=> Fix Nullable GraphQL Relationships

templates/base.html.twig, templates/index/error.html.twig
Missing these in a few default templates, adding them to appease the SonarQube linter.
=> Add Language to HTML

src/EventListener/IndexEntityChanges.php
At the start of the sync process we set everyone to an unexamined state and then flip that back after they're synchronized. This causes a lot of churn in our search index as these users get re-indexed every time the job is run. There isn't any need for that.
This change checks the fields that have been modified and skips indexing users where only the examined flag has been set.
Fixes #5664
I don't see a way to test this. Open to ideas.
=> Skip Indexing Unchanged Synced Users

.github/workflows/ci.yml
After extensive dicussion with SQ and with the owners of this service at UCSF we have determined this is the only path forward for scanning pull requests from forks. The exposure risk for this token is very low, essentially only allowing a bad actor to scan code we're already scanning. Hopefully SQ will figure out how to use the pull_request_target trigger at some point, but for now this is our best path forward.
Info on approval process and SQ details is in UCSF web services Jira DEVEXP-144 (inaccessible to most people, but here for reference later if needed).
=> Store SQ Token in Workflow

.github/workflows/ci.yml
We're running out of disk space during our test runs, trying to alleviate this by stopping and removing the running containers.
=> Remove Containers After Testing

tests/Endpoints/AuthenticationTest.php, tests/Endpoints/OfferingTest.php
This feature became available in PHP 8.0, I see no reason not to use it.
=> Run ClassOnThisVariableObjectRector

config/packages/sentry.yaml, symfony.lock
the entire tracing section was removed in v5.0 from the blueprint.
see https://github.com/symfony/recipes-contrib/blob/main/sentry/sentry-symfony/5.0/config/packages/sentry.yaml 
it looks like sentry: tracing: enabled: true is the default anyway, so i removed that whole section from our config as well.
for reference:
```bash
stefan@nichtsnutz: ~/dev/projects/ilios on update_symfony_sentry_recipe
$ bin/console debug:config SentryBundle
Current configuration for "SentryBundle"
========================================
sentry:
dsn: '%env(SENTRY_DSN)%'
options:
before_send: App\Service\SentryBeforeSend
send_default_pii: true
traces_sampler: sentry.callback.traces_sampler
ignore_exceptions:
- Symfony\Component\Security\Core\Exception\AccessDeniedException
- …
```
=> updates recipe symfony/sentry-symfony bundle to v5.0

.github/workflows/ci.yml
This is a workaround for an issue present in doctrine orm v3 where the migration table shows up as missing from the schema and fails this test. Refs #5266.
Tests:
https://github.com/ilios/ilios/actions/runs/11679136817/job/32519798299
Shows a failure as expected when I changed the length of the first name field for a user:
=> Check Schema Differently

tests/Traits/CohortsEntityTest.php, tests/Traits/CompetenciesEntityTest.php, tests/Traits/ConceptsEntityTest.php, tests/Traits/CoursesEntityTest.php, tests/Traits/IlmSessionsEntityTest.php, tests/Traits/LearningMaterialsEntityTest.php, tests/Traits/ProgramYearsEntityTest.php, tests/Traits/ProgramsEntityTest.php, tests/Traits/UsersEntityTest.php
`getObjectForTrait() is deprecated and will be removed in PHPUnit 12 without replacement.`
=> replace calls to deprecated method with supported equivalent.

src/Entity/LearnerGroup.php, src/Entity/Offering.php
not setting is deprecated, and the default will toggle from FALSE to TRUE in Symfony 8.
for reference, please see https://symfony.com/doc/current/reference/constraints/Url.html#requiretld
fixes  https://github.com/ilios/ilios/issues/5831
=> explictly set requireTld on URL assertion attributes.

src/Classes/IndexableCourse.php
partially corrects changes in https://github.com/ilios/ilios/commit/bcb5dc0d
the relevant line of where this attr can be set to NULL: https://github.com/ilios/ilios/blob/master/src/Repository/CourseRepository.php#L597
=> makes clerkship type nullable.

config/packages/sentry.yaml
Add CommandNotFoundException to ignore_exceptions list to ignore Sentry alerting error.
=> add CommandNotFoundException to ignore_exceptions

src/Repository/AuditLogRepository.php
The API for setParameters has changed in the latest doctrine and now requires an ArrayCollection and Parameter objects. Seemed easier to just use the same single invocation we use elsewhere so I replaced it.
Also dropped an extra colon at the end of each of the `to` formats. I think this was a typo.
Fixes #5851
=> Replace Modified Doctrine Parameter API

src/Message/CourseIndexRequest.php, src/MessageHandler/CourseIndexHandler.php, src/Service/Index/Curriculum.php, src/Service/Index/Manager.php, tests/Service/Index/CurriculumTest.php
Improve performance of course indexing by skipping any course that has been indexed already. When we add or update the index with the data in a course we also store the ingestion time. When courses are updated and we put a message in the async queue to be processed we record that time as well. This allows skipping indexing a course if it has been indexed since the message was added to the queue. When a course is being heavily updated and the index process gets a bit behind this can be a real time saver.
=> Skip Re-indexing Courses

.github/workflows/ci.yml
Newly [released](https://www.php.net/releases/8.4/en.php) and ready to officially enter our CI pipeline.
=> Test PHP 8.4

.env.dev, .env.test, .github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-nightly.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-tag.yml, Dockerfile, compose.yaml, composer.json, composer.lock, config/packages/messenger.yaml, config/services.yaml, docs/docker-examples/docker-compose.demo.yml, docs/env_vars_and_config.md, src/Command/ExtractLearningMaterialsTextCommand.php, src/EventListener/IndexEntityChanges.php, src/Exception/LearningMaterialTextExtractorException.php, src/Message/LearningMaterialTextExtractionRequest.php, src/MessageHandler/LearningMaterialTextExtractionHandler.php, src/Service/IliosFileSystem.php, src/Service/LearningMaterialTextExtractor.php, src/Service/TikaFactory.php, tests/Command/ExtractLearningMaterialsTextCommandTest.php, tests/Message/LearningMaterialTextExtractionRequestTest.php, tests/Service/IliosFileSystemTest.php, tests/Service/LearningMaterialTextExtractorTest.php, tests/Service/TikaFactoryTest.php
Adds an Apache Tika container which we use as a service to send learning materials to and extract their text. The extracted text is stored based on the hash of the material, but in a parallel location (to make it easier to manager and see the impact of the materials).
The process for extraction runs asynchronously like our search index through smyfonys messenger system and is queued when a new material is added or when a command is run to build the index. The extraction process checks to see if the file exists first and assumes it is correct and doesn't attempt to re-extract.
Wip:
=> Extract Text from Learning Materials

.github/workflows/ci.yml
Using this composer command we can ensure that the lock file is up to date and working.
- `no-check-all`: remove errors where we use `@stable` for the version 
- `no-check-version`: ignores that we store the version in our composer.json file - this isn't recommended for unpublished packages but it's where we track this critical data.
=> Validate Composer Lock File

.github/dependabot.yml
This will keep us from getting anything but patch version updates for symfony, we'll have to keep track of the larger version upgrades ourselves. This is necessary to prevent weird partial updates when our extras.symfony.version value in composer isn't updated to match the new symfony version.
=> Ignore Major and Minor Symfony Updates

compose.yaml
This is setup for development. It's useful as a way to test queries and explore the index visually. Primarily it's purpose is to create visualizations for data, like log files, that are part of the index. We'll probably never use it for that, but I've found it useful in development.
I've disabled security as this is strictly for development.
=> Add Opensearch Dashboard

tests/Endpoints/CourseTest.php
i decided to move the test fixture dates forward instead of updating the code to calculate these on the fly based on the current date. for this, we'd have to refactor the `CourseRollover` service in order to make its date calculation functionality available in tests. might be worthwhile to do as a follow-up item, or we can keep this as as-is and do this adjustment to the test fxtures once a year.
=> moves year and related dates forward in course rollover test fixtures.

.github/workflows/ci.yml, .github/workflows/deploy-latest.yml, .github/workflows/deploy-nightly.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-tag.yml, Dockerfile
Updating the version of our emulators to address an issue with the Linux kernel in the latest GitHub action release preventing QEMU from emulating sporadically that was breaking our ability to build our containers. 
To align tests: Use the same QEMU to build containers in CI as we do in deployment and actually build the arm container with the emulator platform.
=> Fix Deploy and Align Tests

src/Controller/API/CurriculumInventorySequenceBlocks.php, src/Normalizer/DTONormalizer.php, src/Service/CurriculumInventory/Export/XmlPrinter.php, src/Service/GraphQL/DTOInfo.php
Instead of creating these closures from an array PHP [now allows this syntax](https://wiki.php.net/rfc/first_class_callable_syntax), which does the same thing with the `...` notation acting to unpack any arguments passed in.
=> Use FirstClassCallable Syntax

.github/workflows/ci.yml
This doesn't quite match how we build containers, but since we're building for a single platform here anyway I think this is a good step and should result in faster overall builds. It also allows us to test the arm containers the same way we test the amd ones.
Refs:
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-24-image.md
Takes our CI run time down from 1hr to 20m which seems well worth the slight compromise of not building our CI containers with the same emulation layer we use to build for release.
=> Use Github arm Runners in CI

tests/Endpoints/CourseTest.php
This finds likes from the session and course objectives, which is part of the filter.
Added this while working on #4540 and it's nice, so let's keep it.
=> Add Test for Deeper Course Mesh Filter

.github/workflows/tag_version.yaml
The `composer config` command only updates `composer.json` and not the lock file. Running update with the `--lock` option should update the lock file without updating any packages.
=> Update Lock File When Tagging Version

Dockerfile, compose.yaml, docs/docker-examples/docker-compose.demo.yml
Docker images are available for v8 that stay up to date with the latest release which is better for our containers. I also discovered that, while it is required for a fresh install, serverVersion isn't needed when a database already exists. Which is the case when we use the demo DB. So I've removed it from those compose setups to make it easier to stay in sync.
=> Float MySQL Docker Version

src/Classes/OpenSearchBase.php
This fixes the immediate issue in #6060 as this exception wasn't getting trapped so it was bubbling up and blocking the delete. I'm leaving the issue open however because the session not being in the index yet doesn't mean it won't be in very soon so we need to enqueue these deletes as well. Saving that for another PR.
=> Replace Opensearch Exception

config/packages/messenger.yaml, src/EventListener/IndexEntityChanges.php, src/Message/CourseDeleteRequest.php, src/Message/LearningMaterialDeleteRequest.php, src/Message/SessionDeleteRequest.php, src/MessageHandler/CourseDeleteHandler.php, src/MessageHandler/LearningMaterialDeleteHandler.php, src/MessageHandler/SessionDeleteHandler.php, tests/Message/CourseDeleteRequestTest.php, tests/Message/LearningMaterialDeleteRequestTest.php, tests/Message/SessionDeleteRequestTest.php, tests/MessageHandler/CourseDeleteHandlerTest.php, tests/MessageHandler/LearningMaterialDeleteHandlerTest.php, tests/MessageHandler/SessionDeleteHandlerTest.php
Doing these instantly can mean the delete request lands before the index request (as in deleting a freshly created session). Because the indexing request is in the queue things that have been deleted can still be found in the index making for a confusing search experience.
Fixes #6060
=> Enqueue Index Deletes

config/packages/messenger.yaml, config/packages/test/messenger.yaml, src/Classes/OpenSearchBase.php, src/Command/Index/DropCommand.php, src/Command/Index/UpdateCommand.php, src/EventListener/IndexEntityChanges.php, src/Message/CourseIndexRequest.php, src/Message/UserIndexRequest.php, src/Service/Index/Curriculum.php, src/Service/Index/LearningMaterials.php, src/Service/Index/Manager.php, src/Service/Index/Mesh.php, src/Service/Index/Users.php, tests/Command/Index/DropCommandTest.php, tests/EventListener/IndexEntityChangesTest.php, tests/Service/Index/CurriculumTest.php, tests/Service/Index/UsersTest.php
Extracting a lot of the useful stuff in #5480 without the learning material index changes. I tried to salvage the original intent in commits, but several rebases and dropping LM commits made my only partially successful.
Along with preventing re-indexing of courses and users the biggest changes in here are in [e567861b4c3dc0085bfa85dca731ea64f1c3eb46] and [9a3b55dda8d43834787ffc1b2b91e3fae2a142c6] which are intended to improve results. This will need to be tested. These changes are nearly 5 years old at this point and include many things I thought were already merged.
=> Index Improvements

Dockerfile, compose.yaml
In order to work with building message consumers we need a dev container that doesn't cache the PHP and prevent changes from showing up.
=> Create a Development Message Consumer

src/Classes/OpenSearchBase.php
We increased this to see if it would improve resource utilization, but it did not. Return it to the open search suggested 2 second value.
Reverts #5509
=> Reduce Bulk Sleep Time

phpunit.dist.xml
This seems useful and makes it far easier to debug when you cause a warning with code PHPUnit is executing.
=> Display Details That Trigger Warnings

src/Classes/OpenSearchBase.php, src/Command/ExtractLearningMaterialsTextCommand.php, src/Command/Index/CourseCommand.php, src/Command/Index/DetectMissingCommand.php, src/Message/CourseIndexRequest.php, src/Message/LearningMaterialIndexRequest.php, src/Message/LearningMaterialTextExtractionRequest.php, src/MessageHandler/LearningMaterialIndexHandler.php, src/MessageHandler/LearningMaterialTextExtractionHandler.php, src/Repository/CourseRepository.php, src/Repository/SessionRepository.php, src/Service/Index/Curriculum.php, src/Service/Index/LearningMaterials.php, src/Service/LearningMaterialTextExtractor.php, tests/Command/ExtractLearningMaterialsTextCommandTest.php, tests/Command/Index/CourseCommandTest.php, tests/Command/Index/DetectMissingCommandTest.php, tests/Message/LearningMaterialIndexRequestTest.php, tests/Message/LearningMaterialTextExtractionRequestTest.php, tests/MessageHandler/LearningMaterialIndexHandlerTest.php, tests/MessageHandler/LearningMaterialTextExtractionHandlerTest.php, tests/Service/Index/CurriculumTest.php, tests/Service/Index/LearningMaterialsTest.php, tests/Service/Index/UsersTest.php, tests/Service/LearningMaterialTextExtractorTest.php
Course and session materials are indexed into their own index, and then extracted during session indexing and included for search. This is made possible by good cleaning of the material text, and compression of the data to stay within common open search limits. 
wip:
=> Make Materials Searchable

compose.yaml
When developing locally it's very useful to have messages consumed quickly, docker is happy to launch several containers for us to do this work so let's use them.
=> Create Replica Message Consumers

src/Service/Index/LearningMaterials.php, tests/Service/Index/LearningMaterialsTest.php
This is an unnecessary extra step, once converted to text and compressed no materials in our very large sample are over a few megabytes. We can go ahead and index them as is.
=> Stop Splitting Materials

src/EventListener/IndexEntityChanges.php, src/Service/Index/LearningMaterials.php, tests/EventListener/IndexEntityChangesTest.php, tests/Service/Index/LearningMaterialsTest.php
We were sending indexing requests for all materials on save, limit this to just files and add a nice exception if this gets messed up in the future.
Fixes #6222
=> Prevent Indexing Non File Materials

config/packages/messenger.yaml, src/EventListener/IndexEntityChanges.php
This was added to work around issues with the doctrine middleware on the default bus, however it fell out of use accidentally during a codemod and appears to no longer be needed. Removing as well as the related code comments.
=> Remove the dispatch.bus Configuration

src/Repository/LearningMaterialRepository.php, src/Service/Index/LearningMaterials.php, tests/Repository/LearningMaterialsRepositoryTest.php, tests/Service/Index/LearningMaterialsTest.php
After a material is indexed grab all the courses it's associated with and re-index them as well to ensure the contents of the material are attached to the course.
Fixes #6226
=> Index Courses After Materials

config/packages/messenger.yaml, src/MessageHandler/CourseIndexHandler.php, tests/MessageHandler/CourseIndexHandlerTest.php
Slightly modified the retry failure settings, but the main thrust of this change is to split up courses that fail to index as a group into smaller individual parts.
=> Improved Failed Index Message Handling

.github/workflows/ci.yml, .github/workflows/future-php.yml, .github/workflows/infection.yml, CONTRIBUTING.md, composer.json, composer.lock, phpunit.dist.xml, symfony.lock, tests/bootstrap.php
This is the new symfony flex recipe for phpunit 12, it drops the bridge in favor of the internal deprecation handler in PHPUnit and takes ownership of bin/phpunit which is now being used in all of our jobs.
As part of the change to for this recipe a new doctrine/deprecations recipe was added as well. I've included it in this change as it's related and it modifies the PHPUnit configuration as well.
=> Update phpunit/phpunit Recipe

src/Command/Index/DetectMissingCommand.php, src/Repository/SessionRepository.php, src/Service/Index/Curriculum.php, src/Service/Index/LearningMaterials.php, tests/Command/Index/DetectMissingCommandTest.php, tests/Repository/SessionRepositoryTest.php, tests/Service/Index/CurriculumTest.php, tests/Service/Index/LearningMaterialsTest.php
Fixes #6258 
The scroll API we were using wasn't working here, I found a way to *very* quickly get all the ids using aggregators and then fixed the display output of the command itself and added an option to index anything that is detected as missing. This did require a change to the way we index courses and sessions. I had the IDs as keywords, but they need to be integers in order to use a range filter on them (which is the only way I could find to ensure we get every single sessions and course as we aggregate the ids).
=> Rewrite of DetectMissing Command

src/Command/Index/CourseCommand.php, src/Command/Index/DetectMissingCommand.php, src/MessageHandler/CourseIndexHandler.php, src/Service/Index/Curriculum.php, tests/Command/Index/CourseCommandTest.php, tests/Command/Index/DetectMissingCommandTest.php, tests/MessageHandler/CourseIndexHandlerTest.php, tests/Service/Index/CurriculumTest.php
When a course has been indexed more recently than the queued message we don't need to index it again. Before we were loading the data for indexing in the handler, but this meant loading it for every course even those that would be skipped. Instead We now pass a list of course IDs into the indexer, check for duplicates, and re-index if needed.
This is especially important now that learning material indexing triggers all courses to get re-indexed. So on an initial load every course could be indexed many many times.
WIP:
=> Improve ReIndex Performance for Courses

src/Command/Index/DetectMissingCommand.php
When only one item is missing having these extra advances is very confusing. These steps don't take any time, so remove the advance and count correctly.
=> Fix Progress Bar in Detect Missing

.github/workflows/tag_version.yaml
As we do a composer update after changing the tag to get a new lock file we need to have the same version of PHP installed as required by Ilios.
=> Align PHP Version in Tag Workflow

config/packages/messenger.yaml, docker/messages-entrypoint, docs/update.md, src/Command/Index/DropCommand.php, src/Message/CourseDeleteRequest.php, src/Message/CourseIndexRequest.php, src/Message/LearningMaterialDeleteRequest.php, src/Message/LearningMaterialIndexRequest.php, src/Message/LearningMaterialTextExtractionRequest.php, src/Message/MeshDescriptorIndexRequest.php, src/Message/SessionDeleteRequest.php, src/Message/UserIndexRequest.php, src/MessageHandler/LearningMaterialTextExtractionHandler.php, src/Service/Index/LearningMaterials.php, tests/Command/Index/DropCommandTest.php, tests/MessageHandler/LearningMaterialTextExtractionHandlerTest.php, tests/Service/Index/LearningMaterialsTest.php
Using a combination of middleware and splitting the transports this ensures everything gets consumed in the right order. It does complicate running the message consumer, but this feels ok to me for the result.
=> Improve Messenger Configuration for Indexing

composer.json, composer.lock
some dependencies, like the api docs bundle, continue to require this package. but we don't need to declare this dependency explicitly since we're not using it directly.
refs #6307
=> rm explicitly declared dependency on symfony/property-info

src/Command/SendTeachingRemindersCommand.php, tests/Endpoints/ProgramYearTest.php
refs #6335 
as of PHP 8.4.0, depending on the default value is deprecated.
please see https://www.php.net/manual/en/function.str-getcsv.php for further details.
=> explicitly sets escape character to the current default value.

src/Service/CurriculumInventory/VerificationPreviewBuilder.php, tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php
this prevents the report generator from breaking on unmapped session types, at the expense of "silently swallowing" unmapped data.
fixes #6362
=> ignore data points derived from session types that are not mapped AAMc methods

Dockerfile
[Debian Trixie](https://www.debian.org/News/2025/20250809) was released this week and is now the underlying OS for our `php:8.4-apache` and `php:8.4-fpm` images. Needed to make a few tweaks to support this new OS.
=> Support for Debian Trixie

Dockerfile
turns out removing this lib post-install is too aggressive.
fixes #6426 
to test:
```bash
docker compose up -d
docker exec -it ilios-php-1 /bin/bash
php -v  #observe that the intl-related warning is gone
php -m | grep intl # observe that `intl` is listed in the output
```
then do the same again with the messages container
```bash
docker exec -it ilios-messages-1 /bin/bash
php -v  #observe that the intl-related warning is gone
php -m | grep intl # observe that `intl` is listed in the output
```
=> do not remove intl dev libs post-install, as this breaks php-intl.

src/Service/LearningMaterialTextExtractor.php, tests/Service/LearningMaterialTextExtractorTest.php
When a material can't be extracted, but there are no errors tika will return and empty string. This can also happen when the extracted text only contains junk. In that case we need to store something to prevent errors when we try and read an empty file.
Fixes #6421
=> Handle Empty LM Text Extraction Better

docker/messages-entrypoint
While we were trapping signals for the message consumer we weren't doing the same for our waiters. This forced a delay when restarting containers when either the index or db aren't available.
Augment the entrypoint here to trap signals and then send them to a backgrounded process for each waiter. While these processes are running we wait for them to either finish or exit.
This is way more complicated, but seems to work.
=> Exit Messenger Container Gracefully

src/Service/Index/Curriculum.php
This number as way too high and was removing otherwise good matches, especially unique single words in large sessions. It doesn't seem to be required at all and I'm getting good results and performance.
=> Remove the Minimum Search Score
